### ISSUE TITLE
[Bug] It took forever to call a rust sync method on Mac Release

### ISSUE THREAD

**Issue by kingfisherphuoc** [fzyzcjy/flutter_rust_bridge#1030]
### Describe the bug

I am testing the template repo on Mac. In the debug mode, the template worked well. However, when I tested a release version, I got an infinite time call as in the image below:

<img width="1393" alt="Screenshot 2023-02-07 at 11 02 19" src="https://user-images.githubusercontent.com/962484/217145684-1fd1d67c-3973-4d33-8b4f-0e3c732a14b5.png">

These are the steps to reproduce the issue:

1. `flutter clean && flutter pub get && flutter build macos` to build macos.
2. Open `macos/Runner.xcworkspace` file with xcode
3. in xcode: `product -> archive`, then open `archive` in the finder and show the package  contents of the archive
4. Open `Products/Applications/flutter_rust_bridge_template.app` app and see the result. 

Any ideas?

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
no error log
```

**Comment by fzyzcjy** [comment]
Maybe have a look at logs. For example, it can be because symbols are wrongly stripped

**Comment by kingfisherphuoc** [comment]
@fzyzcjy can you please explain how to check the logs? The debug build worked great. When archiving using Xcode, tbh, I dont know where to see the log.

**Comment by fzyzcjy** [comment]
It is a classical flutter and/or rust problem about how to see logs, so maybe google that

**Comment by kingfisherphuoc** [comment]
@fzyzcjy this is the log file: [log.txt](https://github.com/fzyzcjy/flutter_rust_bridge/files/10672840/log.txt). Does it make any sense?

**Comment by fzyzcjy** [comment]
well I mean runtime log not log when archieving it

**Comment by kingfisherphuoc** [comment]
Ok, I changed the code a little bit to show the log to the screen widget:

```
Invalid argument(s): Failed to lookup symbol 'store_dart_post_cobject': dlsym(RTLD_DEFAULT, store_dart_post_cobject): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:34)
#1      NativeWire._store_dart_post_cobjectPtr (package:flutter_rust_bridge_template/bridge_generated.dart:142)
#2      NativeWire._store_dart_post_cobject (package:flutter_rust_bridge_template/bridge_generated.dart)
#3      NativeWire.store_dart_post_cobject (package:flutter_rust_bridge_template/bridge_generated.dart)
#4      StoreDartPostCObjectExt.storeDartPostCObject (package:flutter_rust_bridge/src/ffi/io.dart:18)
#5      FlutterRustBridgeBase._setUpRustToDartComm (package:flutter_rust_bridge/src/basic.dart:60)
#6      new FlutterRustBridgeBase (package:flutter_rust_bridge/src/basic.dart:28)
#7      new NativePlatform (package:flutter_rust_bridge_template/bridge_generated.dart:98)
#8      new NativeImpl (package:flutter_rust_bridge_template/bridge_generated.dart:37)
#9      api (package:flutter_rust_bridge_template/ffi.dart:19)
#10     _MyHomePageState.test (package:flutter_rust_bridge_template/main.dart)
#11     _MyHomePageState.initState (package:flutter_rust_bridge_template/main.dart:61)
#12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015)
#13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
#16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6300)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
#21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
#22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
#23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
#25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6300)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
#28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6300)
#29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
```

This is how I test:

```
@override
  void initState() {
    super.initState();
    test();
  }

  Future<void> test() async {
    try {
      var test = await api.platform();
      setState(() {
        text = test.name;
      });
      // isRelease = api.rustReleaseMode();
    } catch (e, stacktrace) {
      // platform = Future(() => e.toString());
      setState(() {
        text = e.toString() + "\n" + stacktrace.toString();
      });
    }
  }
```

**Comment by kingfisherphuoc** [comment]
@kingfisherphuoc thanks. The steps below solved the issue.
```
When creating a release archive (IPA), the symbols are stripped by Xcode.

In Xcode, go to Target Runner > Build Settings > Strip Style.
Change from All Symbols to Non-Global Symbols.
```

**Comment by fzyzcjy** [comment]
You are welcome. IMHO they are already in tutorial: https://github.com/search?q=repo%3Afzyzcjy%2Fflutter_rust_bridge+strip+language%3AMarkdown&type=code&l=Markdown Where do you think we should add?

**Comment by kingfisherphuoc** [comment]
well, in my experience, this issue should be considered as a must-have part of the tutorial. IMO, It should be put in the part 5 [Integrating with iOS/MacOS](https://cjycode.com/flutter_rust_bridge/integrate/ios.html#integrating-with-iosmacos). One more issue that I noticed is that part `5.4.2 - linking the project` is not correct with Mac. If I used exactly the same in the tutorial, my build crashed on other macbooks.

**Comment by fzyzcjy** [comment]
> as a must-have part of the tutorial

Looks reasonable!

cc @Desdaemon who wrote the helpful tutorial - what do you think?
