### ISSUE TITLE
[Bug] build.rs generate code failed!

### ISSUE THREAD

**Issue by toplinuxsir** [fzyzcjy/flutter_rust_bridge#1123]
### Describe the bug

when under the native folder, run cargo build , error as bellow
```
thread 'main' panicked at 'assertion failed: all_configs.iter().enumerate().all(|(index, config)|\n        config.block_index == BlockIndex(index))', C:\Users\users\.cargo\registry\src\github.com-1ecc6299db9ec823\flutter_rust_bridge_codegen-1.69.0\src/lib.rs:66:5
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
when under the native folder, run cargo build , error as bellow

thread 'main' panicked at 'assertion failed: all_configs.iter().enumerate().all(|(index, config)|\n        config.block_index == BlockIndex(index))', C:\Users\users\.cargo\registry\src\github.com-1ecc6299db9ec823\flutter_rust_bridge_codegen-1.69.0\src/lib.rs:66:5
```
```


### To Reproduce

when under the native folder, run cargo build , error as bellow
```
thread 'main' panicked at 'assertion failed: all_configs.iter().enumerate().all(|(index, config)|\n        config.block_index == BlockIndex(index))', C:\Users\users\.cargo\registry\src\github.com-1ecc6299db9ec823\flutter_rust_bridge_codegen-1.69.0\src/lib.rs:66:5
```

### Expected behavior

when under the native folder, run cargo build , error as bellow
```
thread 'main' panicked at 'assertion failed: all_configs.iter().enumerate().all(|(index, config)|\n        config.block_index == BlockIndex(index))', C:\Users\users\.cargo\registry\src\github.com-1ecc6299db9ec823\flutter_rust_bridge_codegen-1.69.0\src/lib.rs:66:5
```

### Generated binding code

```shell
when under the native folder, run cargo build , error as bellow

thread 'main' panicked at 'assertion failed: all_configs.iter().enumerate().all(|(index, config)|\n        config.block_index == BlockIndex(index))', C:\Users\users\.cargo\registry\src\github.com-1ecc6299db9ec823\flutter_rust_bridge_codegen-1.69.0\src/lib.rs:66:5
```
```


### OS

windows 11

### Version of `flutter_rust_bridge_codegen`

1.69

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.7.7, on Microsoft Windows [版本 10.0.22621.1413], locale zh-CN)
    • Flutter version 3.7.7 on channel stable at D:\soft\flutter_windows_2.0.1-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (6 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.4)
    • Visual Studio at j:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32014.148
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at J:\soft\android-studio-2020.3.1.20-windows\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22621.1413]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.65
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.69

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

### Version of `clang++`

15

### Version of `ffigen`

7.2.7

**Comment by fzyzcjy** [comment]
Looks like the ordering of multi blocks is incorrect. Could you please show your build.rs?

also cc @dbsxdbsx - shall we add a bit more friendly error message in this case, e.g. explain to the users how they should provide ordering

**Comment by toplinuxsir** [comment]
> Looks like the ordering of multi blocks is incorrect. Could you please show your build.rs?
> 
> also cc @dbsxdbsx - shall we add a bit more friendly error message in this case, e.g. explain to the users how they should provide ordering

````
use lib_flutter_rust_bridge_codegen::*;

use std::path::Path;

const RUST_INPUT: &str = "src/api.rs";
const RUST_INPUT_PLC: &str = "src/plc.rs";
const RUST_OUTPUT: &str = "src/bridge_generated.rs";
const RUST_OUTPUT_PLC: &str = "src/bridge_generated_plc.rs";

const DART_OUTPUT: &str = "../lib/src/native/bridge_generated.dart";
const DART_OUTPUT_PLC: &str = "../lib/src/native/bridge_generated_plc.dart";

const CLASSNAME_API: &str = "ApiClass";
const CLASSNAME_API_PLC: &str = "PLCClass";

fn capitalize_first_letter(s: &str) -> String {
    s[0..1].to_uppercase() + &s[1..]
}

fn main() {
    // Only rerun when the API file changes.
    println!("cargo:rerun-if-changed={},{}", RUST_INPUT, RUST_INPUT_PLC);
    let configs = config_parse(RawOpts {
        rust_input: vec![RUST_INPUT.to_string(), RUST_INPUT_PLC.into()],
        rust_output: Some(vec![RUST_OUTPUT.into(), RUST_OUTPUT_PLC.into()]),
        dart_output: vec![DART_OUTPUT.to_string(), DART_OUTPUT_PLC.into()],
        class_name: Some(vec![CLASSNAME_API.into(), CLASSNAME_API_PLC.into()]),

        wasm: false,

        /*  c_output: Some(vec![
            "../ios/Runner/bridge_generated.native.h".into(),
            "../macos/Runner/bridge_generated.native.h".into(),
        ]),*/
        ..Default::default()
    });
    if let Ok(symbols) = get_symbols_if_no_duplicates(&configs) {
        for config in &configs {
            let gen_res = frb_codegen(config, &symbols);
            if let Ok(()) = gen_res {
                println!("generate:{} ok!", config.rust_input_path);
                let profile = std::env::var("PROFILE").unwrap();
                let c_profile = capitalize_first_letter(&profile);
                let package_name = "native"; //std::env::var("CARGO_PKG_NAME ").unwrap();
                let target_file = format!("{}.dll", package_name);
                let src = Path::new(".")
                    .join("target")
                    .join(&profile)
                    .join(&target_file);
                let to = Path::new("..")
                    .join("build")
                    .join("windows")
                    .join("runner")
                    .join(c_profile)
                    .join(&target_file);

                println!(
                    "copy from :{}, to: {}, from exits:{:?}, to exits: {}",
                    src.to_str().unwrap(),
                    to.to_str().unwrap(),
                    src.is_file(),
                    to.is_file(),
                );

                //fs::copy(src, to).expect("copy file error!");

                //let src = "target/"
            } else {
                println!("build error: {:?}", gen_res);
            }
        }
    }
}

```
