### ISSUE TITLE
[Bug] cargo ndk cannot find ndk home for some reason?

### ISSUE THREAD

**Issue by polvallverdu** [fzyzcjy/flutter_rust_bridge#1151]
### Describe the bug

When building with `cargo ndk -o ../android/app/src/main/jniLibs build` there is no issue, and cargo ndk can automatically find ndk by itself, but when running `flutter run` it seems not to be able to find it.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
Launching lib\main.dart on 2107113SG in debug mode...
[2023-04-01T21:59:12Z INFO  cargo_ndk::cli] Using NDK at path: "C:\Users\pvall\AppData\Local\Android\sdk\ndk" (ANDROID_NDK_HOME)
thread 'main' panicked at 'could not resolve NDK version: Os { code: 123, kind: InvalidFilename, message: "The filename, directory name, or volume label syntax is incorrect." }', C:\Users\pvall\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-ndk-3.0.1\src\cli.rs:273:53
stack backtrace:
   0:     0x7ff6a2e70012 - <unknown>
   1:     0x7ff6a2e8fd5b - <unknown>
   2:     0x7ff6a2e6bb8a - <unknown>
   3:     0x7ff6a2e6fd5b - <unknown>
   4:     0x7ff6a2e72b39 - <unknown>
   5:     0x7ff6a2e727bb - <unknown>
   6:     0x7ff6a2e733d0 - <unknown>
   7:     0x7ff6a2e7315e - <unknown>
   8:     0x7ff6a2e70d0f - <unknown>
   9:     0x7ff6a2e72e10 - <unknown>
  10:     0x7ff6a2e9e475 - <unknown>
  11:     0x7ff6a2e9e996 - <unknown>
  12:     0x7ff6a2d88cef - <unknown>
  13:     0x7ff6a2d92865 - <unknown>
  14:     0x7ff6a2d81e56 - <unknown>
  15:     0x7ff6a2d922cc - <unknown>
  16:     0x7ff6a2e6559e - <unknown>
  17:     0x7ff6a2d9291c - <unknown>
  18:     0x7ff6a2e975b0 - <unknown>
  19:     0x7ffaa9ec55a0 - BaseThreadInitThunk
  20:     0x7ffaaa18485b - RtlUserThreadStart

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:cargoBuildDebug'.
> Process 'command 'cargo'' finished with non-zero exit value 101

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleDebug'...                              3.1s
Exception: Gradle task assembleDebug failed with exit code 1
```
```


### To Reproduce

_No response_

### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

Windows

### Version of `flutter_rust_bridge_codegen`

_No response_

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Version of `ffigen`

_No response_

### Additional context

_No response_

**Comment by fzyzcjy** [comment]
Hmm maybe try to show debug logs?

**Comment by polvallverdu** [comment]
There's no more info
```
[2023-04-02T09:11:27Z INFO  cargo_ndk::cli] Using NDK at path: "C:\Users\pvall\AppData\Local\Android\sdk\ndk" (ANDROID_NDK_HOME)
thread 'main' panicked at 'could not resolve NDK version: Os { code: 123, kind: InvalidFilename, message: "The filename, directory name, or volume label syntax is incorrect." }', C:\Users\pvall\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-ndk-3.0.1\src\cli.rs:273:53
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:cargoBuildDebug'.
> Process 'command 'cargo'' finished with non-zero exit value 101

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleDebug'...                              3.4s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by fzyzcjy** [comment]
Well, maybe "Codegen logs with RUST_LOG=debug environment variable" (which usually contains a ton of lines of logs)

**Comment by polvallverdu** [comment]
Still nothing:

```
PS D:\vscode\XXXX> $env:RUST_LOG
debug
PS D:\vscode\XXXX> flutter run  
Launching lib\main.dart on 2107113SG in debug mode...
[2023-04-02T10:03:59Z INFO  cargo_ndk::cli] Using NDK at path: "C:\Users\pvall\AppData\Local\Android\sdk\ndk" (ANDROID_NDK_HOME)
thread 'main' panicked at 'could not resolve NDK version: Os { code: 123, kind: InvalidFilename, message: "The filename, directory name, or volume label syntax is incorrect." }', C:\Users\pvall\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-ndk-3.0.1\src\cli.rs:273:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:cargoBuildDebug'.
> Process 'command 'cargo'' finished with non-zero exit value 101

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleDebug'...                              3.3s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by polvallverdu** [comment]
ok, my god. it was because on my `gradle.properties` the path was between `"`
