### ISSUE TITLE
[Bug] `Invalid argument(s): Failed to lookup symbol 'store_dart_post_cobject': dlsym(RTLD_DEFAULT, store_dart_post_cobject): symbol not found` while attempting to run in release mode on macOS

### ISSUE THREAD

**Issue by Adrian-Samoticha** [fzyzcjy/flutter_rust_bridge#1153]
### Describe the bug

I am attempting to run the [`flutter_rust_bridge_template`](https://github.com/Desdaemon/flutter_rust_bridge_template) (commit SHA: `2679c10741318cd40a0d1fa149cc3d37fa0d40b1`) on macOS 13.2.1 (22D68).

The project runs correctly in debug mode, but in profile/release mode, it fails with the following error:

<details>
<summary>Console output</summary>

```
Building macOS application...
flutter: Invalid argument(s): Failed to lookup symbol 'store_dart_post_cobject': dlsym(RTLD_DEFAULT, store_dart_post_cobject): symbol not found
flutter: #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33)
flutter: #1      NativeWire._store_dart_post_cobjectPtr (package:flutter_rust_bridge_template/bridge_generated.io.dart:58)
flutter: #2      NativeWire._store_dart_post_cobject (package:flutter_rust_bridge_template/bridge_generated.io.dart)
flutter: #3      NativeWire.store_dart_post_cobject (package:flutter_rust_bridge_template/bridge_generated.io.dart)
flutter: #4      StoreDartPostCObjectExt.storeDartPostCObject (package:flutter_rust_bridge/src/ffi/io.dart:18)
flutter: #5      FlutterRustBridgeBase._setUpRustToDartComm (package:flutter_rust_bridge/src/basic.dart:60)
flutter: #6      new FlutterRustBridgeBase (package:flutter_rust_bridge/src/basic.dart:28)
flutter: #7      new NativePlatform (package:flutter_rust_bridge_template/bridge_generated.io.dart:15)
flutter: #8      new NativeImpl (package:flutter_rust_bridge_template/bridge_generated.dart:16)
flutter: #9      api (package:flutter_rust_bridge_template/ffi.dart:20)
flutter: #10     _MyHomePageState.initState (package:flutter_rust_bridge_template/main.dart)
flutter: #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5101)
flutter: #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #19     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #31     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #32     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #37     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512)
flutter: #38     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524)
flutter: #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #43     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #49     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #51     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #53     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #54     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #56     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #59     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #60     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #62     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #64     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #65     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #67     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #70     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #71     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #73     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #75     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #76     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #78     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #81     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #83     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
flutter: #89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
flutter: #90     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #92     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
flutter: #93     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #95     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #96     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
flutter: #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #98     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
```

</details>

I have found that in earlier versions of flutter_rust_bridge, the readme advised running `cargo build` in this situation, however that did not resolve my problem.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
Not applicable, as I am attempting to run the flutter_rust_bridge_template which ships with already generated code.
```

### To Reproduce

1. Run `git clone https://github.com/Desdaemon/flutter_rust_bridge_template.git`.
2. Run `cd flutter_rust_bridge_template`.
3. Run `flutter run --profile`.

### Expected behavior

I expected the program to behave similarly to how it does in debug mode.

### OS

macOS 13.2.1 (Apple M1 chip)

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.7.9, on macOS 13.2.1 22D68 darwin-arm64, locale en-US)
    • Flutter version 3.7.9 on channel stable at /Users/adriansamoticha/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62bd79521d (4 days ago), 2023-03-30 10:59:36 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/adriansamoticha/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 13.2.1 22D68 darwin-arm64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### Version of `clang++`

Apple clang version 14.0.0 (clang-1400.0.29.202)

### Version of `ffigen`

7.2.9

**Comment by fzyzcjy** [comment]
Firstly I guess it is symbol stripping problem. Have you configured that?

**Comment by fzyzcjy** [comment]
Hmm I am discussing symbol *stripping* not *linking*. https://cjycode.com/flutter_rust_bridge/integrate/ios_headers.html?highlight=strip#stripping-ios-symbols Does this work?

**Comment by fzyzcjy** [comment]
Also cc @Desdaemon who made that helpful template (if the template is missing something to be configured)

**Comment by Desdaemon** [comment]
I think I'm getting an idea of what's happening. I'll have to borrow an iPhone for its release mode, but for now I can try to debug on my machine.

**Comment by Desdaemon** [comment]
Should be fixed by [`c72216c`](https://github.com/Desdaemon/flutter_rust_bridge_template/commit/c72216c23ae4399a5e088643f4f36be447).

**Comment by fzyzcjy** [comment]
🎉 

(Btw looks that link is 404)

![image](https://user-images.githubusercontent.com/5236035/229656454-19a4f861-f747-4c40-a95e-849607808ea5.png)

**Comment by Adrian-Samoticha** [comment]
That does indeed fix it, thank you very much. :)
