### ISSUE TITLE
Issue with OPENSSL when building for Android

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#1171]
Win10. Rust 1.68.2 Flutter 3.7.7 Dart 2.19.4 

After presetting from [tutorial](https://cjycode.com/flutter_rust_bridge/tutorial/setup_android.html),  the last command in the tutorial `cargo ndk -o ../android/app/src/main/jniLibs build` occurs error:
```
$ cargo ndk -o ./android/app/src/main/jniLibs build
[2023-04-12T07:48:17Z INFO  cargo_ndk::cli] Using NDK at path: C:\Users\dbsx
[2023-04-12T07:48:17Z INFO  cargo_ndk::cli] NDK API level: 21
[2023-04-12T07:48:17Z INFO  cargo_ndk::cli] Building targets: armeabi-v7a, a
[2023-04-12T07:48:17Z INFO  cargo_ndk::cli] Building armeabi-v7a (armv7-linu
   Compiling openssl-sys v0.9.80
   Compiling anyhow v1.0.66
   Compiling form_urlencoded v1.1.0
   Compiling pin-project v1.0.12
   Compiling httparse v1.8.0
   Compiling h2 v0.3.15
   Compiling unicode-normalization v0.1.22
   Compiling futures-channel v0.3.25
   Compiling http-body v0.4.5
error: failed to run custom build command for `openssl-sys v0.9.80`

Caused by:
  process didn't exit successfully: `D:\DATA\BaiduSyncdisk\project\personal\805939fcc8559\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rustc-cfg=openssl
  cargo:rerun-if-env-changed=ARMV7_LINUX_ANDROIDEABI_OPENSSL_LIB_DIR
  ARMV7_LINUX_ANDROIDEABI_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR = C:\Program Files\OpenSSL-Win64\lib
  cargo:rerun-if-env-changed=ARMV7_LINUX_ANDROIDEABI_OPENSSL_INCLUDE_DIR
  ARMV7_LINUX_ANDROIDEABI_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=ARMV7_LINUX_ANDROIDEABI_OPENSSL_DIR
  ARMV7_LINUX_ANDROIDEABI_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR = C:\Program Files\OpenSSL-Win64
  cargo:rustc-link-search=native=C:\Program Files\OpenSSL-Win64\lib
  cargo:include=C:\Program Files\OpenSSL-Win64\include
  cargo:rerun-if-changed=build/expando.c
  OPT_LEVEL = Some("0")
  TARGET = Some("armv7-linux-androideabi")
  HOST = Some("x86_64-pc-windows-msvc")
  cargo:rerun-if-env-changed=CC_armv7-linux-androideabi
  CC_armv7-linux-androideabi = Some("C:\\Users\\dbsx\\AppData\\Local\\Androi\\bin\\armv7a-linux-androideabi21-clang.cmd")
  cargo:rerun-if-env-changed=CFLAGS_armv7-linux-androideabi
  CFLAGS_armv7-linux-androideabi = None
  cargo:rerun-if-env-changed=CFLAGS_armv7_linux_androideabi
  CFLAGS_armv7_linux_androideabi = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  running: "C:\\Users\\dbsx\\AppData\\Local\\Android\\sdk\\ndk\\25.2.9519653et=armv7a-linux-androideabi21" "-O0" "-DANDROID" "-ffunction-sections" "-fdainux-androideabi" "-I" "C:\\Program Files\\OpenSSL-Win64\\include" "-Wall" "
  exit code: 0
  version: 3_1_0
  cargo:rustc-cfg=osslconf="OPENSSL_NO_SSL3_METHOD"
  cargo:conf=OPENSSL_NO_SSL3_METHOD
  cargo:rustc-cfg=ossl300
  cargo:rustc-cfg=ossl101
  cargo:rustc-cfg=ossl102
  cargo:rustc-cfg=ossl102f
  cargo:rustc-cfg=ossl102h
  cargo:rustc-cfg=ossl110
  cargo:rustc-cfg=ossl110f
  cargo:rustc-cfg=ossl110g
  cargo:rustc-cfg=ossl110h
  cargo:rustc-cfg=ossl111
  cargo:rustc-cfg=ossl111b
  cargo:rustc-cfg=ossl111c
  cargo:version_number=30100000
  cargo:rerun-if-env-changed=ARMV7_LINUX_ANDROIDEABI_OPENSSL_LIBS
  ARMV7_LINUX_ANDROIDEABI_OPENSSL_LIBS unset
  cargo:rerun-if-env-changed=OPENSSL_LIBS
  OPENSSL_LIBS unset
  cargo:rerun-if-env-changed=ARMV7_LINUX_ANDROIDEABI_OPENSSL_STATIC
  ARMV7_LINUX_ANDROIDEABI_OPENSSL_STATIC unset
  cargo:rerun-if-env-changed=OPENSSL_STATIC


  OPENSSL_STATIC unset

  --- stderr
  thread 'main' panicked at 'OpenSSL libdir at `["C:\\Program Files\\OpenSSL-Win64\\lib"]` does not contain the required files to either statically or dynamically link OpenSSL', C:\Users\dbsx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openssl-sys-0.9.80\build/main.rs:401:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
[2023-04-12T07:48:24Z INFO  cargo_ndk::cli] If the build failed due to a missing target, you can run
this command:
[2023-04-12T07:48:24Z INFO  cargo_ndk::cli]
[2023-04-12T07:48:24Z INFO  cargo_ndk::cli]     rustup target install armv7-linux-androideabi
```
It is easy to see it is related to [rust_openssl](https://github.com/sfackler/rust-openssl). But I have no idea how to solve it even I've already set `OPENSSL_DIR` and `OPENSSL_DIR_LIB`, like I posted issue [here](https://github.com/sfackler/rust-openssl/issues/1793).

The 1st I got the issue, seems... occur around Jan this year, when I ran `flutter run` on win10 with an Android emulator.  I think this issue needs to be mentioned also in the tutorial.

**Comment by dbsxdbsx** [comment]
Update:
After setting `OPENSSL_STATIC` with `0`, new issue occurred:
```
error: linking with `C:\Users\dbsx\AppData\Local\Android\sdk\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\armv7a-linux-androideabi21-clang.cmd` failed: exit code: 1
  |
  = note: "C:\\Users\\dbsx\\AppData\\Local\\Android\\sdk\\ndk\\25.2.9519653\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\armv7a-linux-androideabi21-clang.cmd" "-Wl,--version-script=C:\\Users\\dbsx\\AppData\\Local\\Temp\\rustc92tHH7\\list" "-march=armv7-a" "C:\\Users\\dbsx\\AppData\\Local\\Temp\\rustc92tHH7\\symbols.o" "D:\\DATA\\BaiduSyncdisk\\project\\personal\\TV_APP_PROJECT\\xiao_dong_tv\\native\\target\\armv7-linux-androideabi\\debug\\deps\\native.10fi7v6a36vwx69c.rcgu.o"

...
...
...

\\Users\\dbsx\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\armv7-linux-androideabi\\lib\\libcore-926fb9036d3ac37aac06d13.rlib" "C:\\Users\\dbsx\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\armv7-linux-androideabi\\lib\\libcstack"ompiler_builtins-ac37aac6e2dcbd64.rlib" "-Wl,-Bdynamic" "-lssl" "-lcrypto" "-ldl" "-llog" "-lunwind" "-ldl" "-lm" "-lc" "-Wl,--eh-ATA\\Baframe-hdr" "-Wl,-znoexecstack" "-L" "C:\\Users\\dbsx\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\armv7-linu"-Wl,--x-androideabi\\lib" "-o" "D:\\DATA\\BaiduSyncdisk\\project\\personal\\TV_APP_PROJECT\\xiao_dong_tv\\native\\target\\armv7-linux-androideabi\\debug\\deps\\libnative.so" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: ld: error: unable to find library -lssl
          ld: error: unable to find library -lcrypto
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


warning: `native` (lib) generated 2 warnings
error: could not compile `native` due to previous error; 2 warnings emitted
[2023-04-12T08:09:40Z INFO  cargo_ndk::cli] If the build failed due to a missing target, you can run this command:
[2023-04-12T08:09:40Z INFO  cargo_ndk::cli]
[2023-04-12T08:09:40Z INFO  cargo_ndk::cli]     rustup target install armv7-linux-androideabi
```

**Comment by fzyzcjy** [comment]
Hmm interesting... Does it happen using the tutorial code without any change? 

Btw I guess it is a Rust OpenSSL + android bug (unrelated to frb core), but yes if it happens for our tutorial, we should somehow fix it, or just simply remove this dependency.

**Comment by dbsxdbsx** [comment]
I guess this issue occured since December.20th 2022, when [0.9.8](https://github.com/sfackler/rust-openssl/releases/tag/openssl-sys-v0.9.80) released.   Before, I didn't even realize this crate. But now I am not sure which crate use openssl-sys-v0.9.80.

**Comment by fzyzcjy** [comment]
> I am not sure which crate use openssl-sys-v0.9.80.

If you mean examples inside this repo - then maybe just remove that crate and see compile errors, or use https://doc.rust-lang.org/cargo/commands/cargo-tree.html

**Comment by fzyzcjy** [comment]
Seems related: https://github.com/fzyzcjy/flutter_rust_bridge/discussions/1158#discussioncomment-5607244

**Comment by erikas-taroza** [comment]
I have trouble building OpenSSL locally as well (worked fine at some point). Building it on the GitHub Actions machines works as expected.

**Comment by w-ensink** [comment]
In our app we use pre-build binaries and point the openssl crate to those via environment variables set in `.cargo/config.toml`.

**Comment by erikas-taroza** [comment]
I needed to do some debugging on Android for my project. I tried out [cross](https://github.com/cross-rs/cross) and I was able to build locally. Looks like this might be an issue with `cargo-ndk`.

**Comment by igor-yusupov** [comment]
> 

Can you please describe how to build with cross? Or what to do to fix the cargo-ndk bug?

**Comment by igor-yusupov** [comment]
@erikas-taroza 
Can you please describe how to build with cross? Or what to do to fix the cargo-ndk bug?

**Comment by igor-yusupov** [comment]
> cross build --target aarch64-linux-android --release
Unfortunately, I got the same error

**Comment by igor-yusupov** [comment]
> > @erikas-taroza Can you please describe how to build with cross? Or what to do to fix the cargo-ndk bug?
> 
> ```
> cross build --target aarch64-linux-android --release
> ```

Unfortunately, I got the same error

**Comment by w-ensink** [comment]
Get [this repo](https://github.com/KDAB/android_openssl) and either put the files in your project or make it a submodule. 
Then you can point the openssl crate to them by providing them via environment variables:
```bash
export OPENSSL_DIR="<path_to>/openssl/ssl_3"
export AARCH64_LINUX_ANDROID_OPENSSL_LIB_DIR="<path_to>/openssl/ssl_3/arm64-v8a"

cargo b --target aarch64-linux-android --release
```

You can then automate this passing of variables by using `.cargo/config.toml`:
```
[env]
OPENSSL_DIR  = { value = "../android/openssl/ssl_3", relative = true }
AARCH64_LINUX_ANDROID_OPENSSL_LIB_DIR = { value = "../android/openssl/ssl_3/arm64-v8a", relative = true }
```
Now cargo will set the environment variables for you before building.

This worked for me.

**Comment by Roms1383** [comment]
Got a very similar issue on `M1 Pro` on first updating my project after months of inactivity:

<details><summary>Click to see error</summary>

```sh
error: failed to run custom build command for `libsqlite3-sys v0.26.0`

Caused by:
  process didn't exit successfully: `/Users/romain/Development/lab/cerclo-app/native/target/debug/build/libsqlite3-sys-0362c2df44bd4e53/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=sqlcipher/sqlite3.c
  cargo:rerun-if-changed=sqlite3/wasm32-wasi-vfs.c

  --- stderr
  thread 'main' panicked at 'OpenSSL library directory does not exist: /opt/homebrew/Cellar/openssl@1.1/1.1.1q/lib', /Users/romain/.cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.26.0/build.rs:161:25
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```
  
</details>

`libsqlite3-sys v0.26.0` is the culprit because it drags `openssl` in its wake, because I use:
```toml
[dependencies]
rusqlite = { version = "0.29.0", features = [
  "bundled-sqlcipher-vendored-openssl",
  "uuid",
  "chrono",
] }
```

I first tried setting `OPENSSL_DIR` or `OPENSSL_LIB_DIR` as suggested but for some reason it didn't fix (really it should work, I probably messed up something at some point).

Another way to fix it is to create symlinks to your openssl. In my case version `1.1` as seen in the error.

I checked with `brew search openssl@1.1` but version `1.1.1q` is no longer available.

So I checked `brew list openssl@1.1` and got the following result:

```sh
/opt/homebrew/Cellar/openssl@1.1/1.1.1t/.bottle/etc/ (7 files)
/opt/homebrew/Cellar/openssl@1.1/1.1.1t/bin/c_rehash
/opt/homebrew/Cellar/openssl@1.1/1.1.1t/bin/openssl
/opt/homebrew/Cellar/openssl@1.1/1.1.1t/include/openssl/ (104 files)
/opt/homebrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.1.1.dylib
/opt/homebrew/Cellar/openssl@1.1/1.1.1t/lib/libssl.1.1.dylib
/opt/homebrew/Cellar/openssl@1.1/1.1.1t/lib/engines-1.1/ (2 files)
/opt/homebrew/Cellar/openssl@1.1/1.1.1t/lib/pkgconfig/ (3 files)
/opt/homebrew/Cellar/openssl@1.1/1.1.1t/lib/ (4 other files)
/opt/homebrew/Cellar/openssl@1.1/1.1.1t/share/doc/ (3985 files)
/opt/homebrew/Cellar/openssl@1.1/1.1.1t/share/man/ (3985 files)
```

Ok so now I just need to create empty dirs:

```sh
mkdir -p /opt/homebrew/Cellar/openssl@1.1/1.1.1q/lib
mkdir -p /opt/homebrew/Cellar/openssl@1.1/1.1.1q/include
```
and symlinks to existing dirs on my machine:

```sh
ln -s /opt/homebrew/Cellar/openssl@1.1/1.1.1t/lib /opt/homebrew/Cellar/openssl@1.1/1.1.1q/lib
ln -s /opt/homebrew/Cellar/openssl@1.1/1.1.1t/include /opt/homebrew/Cellar/openssl@1.1/1.1.1q/include
```

And boom :boom: ! It builds :tada:

Hope this helps :)
