### ISSUE TITLE
`SyncReturn` produces `FfiException(...NoSuchMethodError:...` on the web

### ISSUE THREAD

**Issue by temeddix** [fzyzcjy/flutter_rust_bridge#1218]
### Discussed in https://github.com/fzyzcjy/flutter_rust_bridge/discussions/1217

I'm using Flutter 3.10, Rust 1.69 on Windows.

I followed everything from the docs and `flutter_rust_bridge_template` and then used `dart run flutter_rust_bridge:serve` command, but the web target produces this error in the browser.
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/66480156/0d311712-6958-44a4-b483-b87dfb7342fd)

This is the chrome devtools log
```log
main.dart.js:12984 Uncaught FfiException(EXECUTE_SYNC_ABORT, NoSuchMethodError: method not found: 'wire_prepare_channels$0' on null, TypeError: Cannot read properties of undefined (reading 'wire_prepare_channels$0')
    at Object.wire_prepare_channels$0$x (http://localhost:8080/main.dart.js:34786:42)
    at BridgeImpl_prepareChannels_closure.call$0 (http://localhost:8080/main.dart.js:108389:16)
    at BridgePlatform.executeSync$1$1 (http://localhost:8080/main.dart.js:107210:35)
    at BridgePlatform.executeSync$1 (http://localhost:8080/main.dart.js:107239:19)
    at BridgeImpl.prepareChannels$0 (http://localhost:8080/main.dart.js:108350:29)
    at http://localhost:8080/main.dart.js:33459:42
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:11588:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:58398:12)
    at Object._asyncStartSync (http://localhost:8080/main.dart.js:11552:20)
    at Object.organizeRustRelatedThings (http://localhost:8080/main.dart.js:33475:16))
    at Object.wrapException (http://localhost:8080/main.dart.js:8819:17)
    at BridgePlatform.executeSync$1$1 (http://localhost:8080/main.dart.js:107215:17)
    at BridgePlatform.executeSync$1 (http://localhost:8080/main.dart.js:107239:19)
    at BridgeImpl.prepareChannels$0 (http://localhost:8080/main.dart.js:108350:29)
    at http://localhost:8080/main.dart.js:33459:42
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:11588:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:58398:12)
    at Object._asyncStartSync (http://localhost:8080/main.dart.js:11552:20)
    at Object.organizeRustRelatedThings (http://localhost:8080/main.dart.js:33475:16)
    at http://localhost:8080/main.dart.js:33491:38
```

And this is my `api.rs` file
```rust
use flutter_rust_bridge::RustOpaque;
use flutter_rust_bridge::StreamSink;
use flutter_rust_bridge::SyncReturn;
use ref_thread_local::ref_thread_local;
use ref_thread_local::RefThreadLocal;
use std::cell::RefCell;
use std::collections::HashMap;
pub use std::sync::Mutex;
use tokio::sync::mpsc::channel;
use tokio::sync::mpsc::Receiver;
use tokio::sync::mpsc::Sender;
...
#[derive(Debug)]
pub struct EndpointsOnRustThread {
    pub user_action_receiver: Receiver<(String, String)>,
    pub viewmodel_update_sender: Sender<(String, Vec<u8>)>,
}
...
pub fn prepare_channels() -> SyncReturn<RustOpaque<Mutex<EndpointsOnRustThread>>> {
    // Thread 0 running Dart
    let (user_action_sender, user_action_receiver) = channel(1024);
    let refcell = USER_ACTION_SENDER.borrow();
    refcell.replace(Some(user_action_sender));
    let (viewmodel_update_sender, viewmodel_update_receiver) = channel(1024);
    let refcell = VIEWMODEL_UPDATE_RECEIVER.borrow();
    refcell.replace(Some(viewmodel_update_receiver));
    let endpoints_on_rust_thread = EndpointsOnRustThread {
        user_action_receiver,
        viewmodel_update_sender,
    };
    SyncReturn(RustOpaque::new(Mutex::new(endpoints_on_rust_thread)))
}
...
```
My code works very well when compiled to native platforms. It's only the web that produces this error. According to @fzyzcjy in the discussion, this looks like a bug.

**Comment by temeddix** [comment]
I tried running my code on Windows PC and macbook.

When compiling for Windows, Linux, macOS, iOS, Android, the code works just fine. But when I tried running the code on the web on macbook but the same error occurs.

**Comment by temeddix** [comment]
https://github.com/cunarist/app-template/blob/main/native/hub/src/bridge/api.rs
The code can be seen here.

**Comment by fzyzcjy** [comment]
Hmm wait, why I did not reply to this for 4 days? It must have slip through the net :/

**Comment by fzyzcjy** [comment]
So, maybe we can try to make a minimal reproducible sample. For example, will remove the SyncReturn solve the problem? Or RustOpaque, etc.

**Comment by temeddix** [comment]
Okay I will do the tests later :)

The entire code in the repo works for 5 native targets, it's only the web that's the problem.

Compiling for the web works fine, but that error occurs in the browser when running with `flutter_rust_bridge:serve`

**Comment by fzyzcjy** [comment]
Web is indeed quite different from native platforms (thanks to the work of @Desdaemon) in the world of Flutter, so I do expect Web has some special bugs while all native platforms work well ...

**Comment by temeddix** [comment]
I see, I kind of understand the difference of web because I did contribute some of the code in 1.63.

I will upload any relevant infos after testing, thank you for your reply :)

**Comment by fzyzcjy** [comment]
Hmm, so if SyncReturn is the bug, does this cause error:

```
pub fn prepare_channels() -> RustOpaque<i32> {
    123
}
```

**Comment by temeddix** [comment]
```rust
pub fn prepare_channels() -> RustOpaque<i32> {
    RustOpaque::new(123)
}
```

I can confirm that this signature doesn't block the app's startup.

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/66480156/2381c659-b5c2-4c0e-aa8a-53ea089fc773)

**Comment by fzyzcjy** [comment]
Oops, I mean `SyncReturn<i32>` not `RustOpaque<i32>`, sorry for that... Indeed, my thought is that, we may need to further simplify reproducible samples. For example, if we guess SyncReturn is the source of bug, we should test sth like `fn f() -> SyncReturn<i32> { 123 }`, s.t. we ensure RustOpaque, Mutex, code body etc are the sources of bug.

**Comment by temeddix** [comment]
Okay, I can help with creating reproducible samples. If you want something more, please tell me the list of function signatures that you want to inspect.

```
pub fn prepare_channels() -> SyncReturn<i32> {
    SyncReturn(3)
}
```

Yes, this indeed blocks the web app
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/66480156/a1c9ca56-7e48-4a1f-8b08-dd6f5947266a)

This is the chrome devtools log
```
Uncaught FfiException(EXECUTE_SYNC_ABORT, NoSuchMethodError: method not found: 'wire_prepare_channels$0' on null, TypeError: Cannot read properties of undefined (reading 'wire_prepare_channels$0')
    at Object.wire_prepare_channels$0$x (http://localhost:8080/main.dart.js:34770:42)
    at BridgeImpl_prepareChannels_closure.call$0 (http://localhost:8080/main.dart.js:108441:16)
    at BridgePlatform.executeSync$1$1 (http://localhost:8080/main.dart.js:107094:35)
    at BridgePlatform.executeSync$1 (http://localhost:8080/main.dart.js:107123:19)
    at BridgeImpl.prepareChannels$0 (http://localhost:8080/main.dart.js:108380:29)
    at http://localhost:8080/main.dart.js:33444:42
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:11588:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:58341:12)
    at Object._asyncStartSync (http://localhost:8080/main.dart.js:11552:20)
    at Object.organizeRustRelatedThings (http://localhost:8080/main.dart.js:33461:16))
    at Object.wrapException (http://localhost:8080/main.dart.js:8819:17)
    at BridgePlatform.executeSync$1$1 (http://localhost:8080/main.dart.js:107099:17)
    at BridgePlatform.executeSync$1 (http://localhost:8080/main.dart.js:107123:19)
    at BridgeImpl.prepareChannels$0 (http://localhost:8080/main.dart.js:108380:29)
    at http://localhost:8080/main.dart.js:33444:42
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:11588:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:58341:12)
    at Object._asyncStartSync (http://localhost:8080/main.dart.js:11552:20)
    at Object.organizeRustRelatedThings (http://localhost:8080/main.dart.js:33461:16)
    at http://localhost:8080/main.dart.js:34231:38
```

**Comment by fzyzcjy** [comment]
Ok, so it seems like `SyncReturn` does not work on Web. Firstly cc @Desdaemon - is it a known limitation (e.g. SyncReturn is not implemented), or a bug where SyncReturn should have worked?

In addition, @temeddix have you checked the pure_dart/with_flutter examples - CI ensures they pass on Web, and do they contain SyncReturn?

**Comment by temeddix** [comment]
I'm using a folder structure like this:

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/66480156/13473e85-44a6-4ea2-b27e-9cd50454a5ee)

It _is_ a bit different from the recommended structure. Could this be the cause?

The full code is at https://github.com/cunarist/app-template/tree/main/native/hub/src

**Comment by temeddix** [comment]
I will do the `pure_dart` test in a bit

**Comment by fzyzcjy** [comment]
> It is a bit different from the recommended structure. Could this be the cause?

I guess no, but anyway, by making a reproducible sample we can be clearer about that

**Comment by temeddix** [comment]
I will upload this `pure_dart` example output as a text file, since it's too long

[output.txt](https://github.com/fzyzcjy/flutter_rust_bridge/files/11574647/output.txt)
