### ISSUE TITLE
[Bug] Cannot convert JsValue into JsArray

### ISSUE THREAD

**Issue by Andrflor** [fzyzcjy/flutter_rust_bridge#1235]
### Describe the bug

When i use a function with String as argument it works perfectly on web.
When i use a function with List\<String> as argument it crashes trying to convert JsValue to JsArray

```
panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(Object)', src/binding/bridge_generated.web.rs:38:9

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (http://localhost:5000/pkg/extractor.js:460:21)
    at http://localhost:5000/pkg/extractor_bg.wasm:wasm-function[1139]:0xce5e0
    at http://localhost:5000/pkg/extractor_bg.wasm:wasm-function[547]:0xb9e3d
    at http://localhost:5000/pkg/extractor_bg.wasm:wasm-function[903]:0xc2b7e
    at http://localhost:5000/pkg/extractor_bg.wasm:wasm-function[715]:0xbe834
    at http://localhost:5000/pkg/extractor_bg.wasm:wasm-function[212]:0x7bf64
    at http://localhost:5000/pkg/extractor_bg.wasm:wasm-function[168]:0x6e9a5
    at __exports.wire_process_lines (http://localhost:5000/pkg/extractor.js:218:10)
    at d8.NB (http://localhost:5000/main.dart.js:55029:20)
    at Object.cAm (http://localhost:5000/main.dart.js:42841:27)
```

Here is the incriminated unwarp

```rust
impl Wire2Api<Vec<String>> for JsValue {
    fn wire2api(self) -> Vec<String> {
        self.dyn_into::<JsArray>()
            .unwrap()
            .iter()
            .map(Wire2Api::wire2api)
            .collect()
    }
}
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
flutter_rust_bridge_codegen -r native/src/binding/api.rs -d lib/bridge_generated.dart -c ios/Classes/bridge_generated.h -e macos/Runner --wasm --skip-add-mod-to-lib --dart-decl-output lib/bridge-definitions.dart
2023/06/06 08:01:34 [WARN] Skipping unresolvable module web (tried /home/andrflor/projects/extractor/native/src/binding/web.rs, /home/andrflor/projects/extractor/native/src/binding/web/mod.rs, /home/andrflor/projects/extractor/native/src/binding/bridge_generated/web.rs, /home/andrflor/projects/extractor/native/src/binding/bridge_generated/web/mod.rs, )
2023/06/06 08:01:34 [WARN] Skipping unresolvable module io (tried /home/andrflor/projects/extractor/native/src/binding/io.rs, /home/andrflor/projects/extractor/native/src/binding/io/mod.rs, /home/andrflor/projects/extractor/native/src/binding/bridge_generated/io.rs, /home/andrflor/projects/extractor/native/src/binding/bridge_generated/io/mod.rs, )
2023/06/06 08:01:35 [INFO] Phase: Validate config(s)
2023/06/06 08:01:35 [INFO] Picked config: Opts { rust_input_path: "/home/andrflor/projects/extractor/native/src/binding/api.rs", dart_output_path: "/home/andrflor/projects/extractor/lib/bridge_generated.dart", dart_decl_output_path: Some("/home/andrflor/projects/extractor/lib/bridge-definitions.dart"), c_output_path: ["/home/andrflor/projects/extractor/ios/Classes/bridge_generated.h", "macos/Runner/bridge_generated.h"], rust_crate_dir: "/home/andrflor/projects/extractor/native", rust_output_path: "/home/andrflor/projects/extractor/native/src/binding/bridge_generated.rs", class_name: "Extractor", dart_format_line_length: 80, dart_enums_style: false, skip_add_mod_to_lib: true, llvm_path: ["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/msys64/mingw64"], llvm_compiler_opts: "", manifest_path: "/home/andrflor/projects/extractor/native/Cargo.toml", dart_root: Some("/home/andrflor/projects/extractor"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: false, wasm_enabled: true, inline_rust: false, bridge_in_method: true, extra_headers: "" }
2023/06/06 08:01:35 [INFO] Phase: Parse source code to AST, then to IR
2023/06/06 08:01:35 [WARN] Skipping unresolvable module web (tried /home/andrflor/projects/extractor/native/src/binding/web.rs, /home/andrflor/projects/extractor/native/src/binding/web/mod.rs, /home/andrflor/projects/extractor/native/src/binding/bridge_generated/web.rs, /home/andrflor/projects/extractor/native/src/binding/bridge_generated/web/mod.rs, )
2023/06/06 08:01:35 [WARN] Skipping unresolvable module io (tried /home/andrflor/projects/extractor/native/src/binding/io.rs, /home/andrflor/projects/extractor/native/src/binding/io/mod.rs, /home/andrflor/projects/extractor/native/src/binding/bridge_generated/io.rs, /home/andrflor/projects/extractor/native/src/binding/bridge_generated/io/mod.rs, )
2023/06/06 08:01:35 [INFO] Phase: Transform IR
2023/06/06 08:01:35 [INFO] Phase: Generate Rust code
2023/06/06 08:01:35 [INFO] Phase: Generate Dart code
Flutter 3.11.0-19.0.pre • channel master • https://github.com/flutter/flutter.git
Framework • revision 0b7415356e (3 days ago) • 2023-06-03 07:16:37 -0400
Engine • revision c838a1b059
Tools • Dart 3.1.0 (build 3.1.0-166.0.dev) • DevTools 2.24.0
2023/06/06 08:01:36 [INFO] Phase: Generating Dart bindings for Rust
Deprecated. Use `dart run` instead.
Running in Directory: '/home/andrflor/projects/extractor'
Input Headers: [/tmp/.tmpHuNcFv.h]
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: DartCObject, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct DartCObject, usr: c:@S@DartCObject
[WARNING]: No definition found for declaration - (Cursor) spelling: DartCObject, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct DartCObject, usr: c:@S@DartCObject
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: DartCObject, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct DartCObject, usr: c:@S@DartCObject
[WARNING]: Generated declaration '_Dart_Handle' start's with '_' and therefore will be private.
Finished, Bindings generated in /tmp/.tmpmZXmKz
the path is "/home/andrflor/projects/extractor/ios/Classes/bridge_generated.h"
the path is "macos/Runner/bridge_generated.h"
2023/06/06 08:01:38 [INFO] Phase: Running build_runner
2023/06/06 08:01:38 [INFO] Running build_runner at /home/andrflor/projects/extractor
Deprecated. Use `dart run` instead.
[INFO] Generating build script completed, took 260ms
[WARNING] Invalidated precompiled build script due to missing asset graph.
[INFO] Precompiling build script... completed, took 634ms
[INFO] Building new asset graph completed, took 1.5s
[INFO] Checking for unexpected pre-existing outputs. completed, took 0ms
[INFO] Running build completed, took 17.7s
[INFO] Caching finalized dependency graph completed, took 234ms
[INFO] Succeeded after 17.9s with 10 outputs (15859 actions)
2023/06/06 08:02:00 [INFO] Phase: Formatting Dart code
Formatted /home/andrflor/projects/extractor/lib/bridge_generated.dart
Formatted /home/andrflor/projects/extractor/lib/bridge-definitions.dart
Formatted /home/andrflor/projects/extractor/lib/bridge_generated.web.dart
Formatted /home/andrflor/projects/extractor/lib/bridge_generated.io.dart
Formatted 5 files (4 changed) in 0.35 seconds.
2023/06/06 08:02:01 [INFO] Success!
2023/06/06 08:02:01 [INFO] Now go and use it :)
```

### To Reproduce

Just try to get a function that takes a List of string on web

### Expected behavior

Should get string vector

### OS

Web

### Version of `flutter_rust_bridge_codegen`

1.45.3 -> 1.77.1

### Version of `clang++`

15.0.7

### Version of `ffigen`

8.0.1

**Comment by fzyzcjy** [comment]
Looks like a bug, also cc @Desdaemon who implemented the helpful Web part. Feel free to create a PR!
