### ISSUE TITLE
[Bug] Codegen fails for SyncReturn<Result<T, E>>

### ISSUE THREAD

**Issue by DontBreakAlex** [fzyzcjy/flutter_rust_bridge#1236]
### Describe the bug

Codegen fails for this function:
```Rust
pub fn bug() -> SyncReturn<Result<i32>> {
	SyncReturn(Ok(0))
}
```
This is quite suprising because this works fine:
```Rust
pub fn bug() -> Result<i32> {
	Ok(0)
}
```
and it looks like that the codegen should be handled by the inner type:
https://github.com/fzyzcjy/flutter_rust_bridge/blob/7dea25d68cc0433f653cc673da4440759b94e09e/frb_codegen/src/ir/ty_sync_return.rs#L19-L30

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
RUST_LOG=debug just gen
flutter pub get
Resolving dependencies... 
  collection 1.17.1 (1.17.2 available)
  ffigen 7.2.11 (8.0.2 available)
  file 6.1.4 (7.0.0 available)
  http 0.13.6 (1.0.0 available)
  matcher 0.12.15 (0.12.16 available)
  material_color_utilities 0.2.0 (0.5.0 available)
  puppeteer 2.24.0 (3.0.0 available)
  source_span 1.9.1 (1.10.0 available)
  test_api 0.5.1 (0.6.0 available)
Got dependencies!
flutter_rust_bridge_codegen --rust-input native/src/api.rs --dart-output lib/bridge_generated.dart --c-output ios/Runner/bridge_generated.h --extra-c-output-path macos/Runner/ --dart-decl-output lib/bridge_definitions.dart --wasm
2023/06/06 11:39:18 [DEBUG] configs=[Opts { rust_input_path: "/home/alexandre/Downloads/flutter_rust_bridge_template/native/src/api.rs", dart_output_path: "/home/alexandre/Downloads/flutter_rust_bridge_template/lib/bridge_generated.dart", dart_decl_output_path: Some("/home/alexandre/Downloads/flutter_rust_bridge_template/lib/bridge_definitions.dart"), c_output_path: ["/home/alexandre/Downloads/flutter_rust_bridge_template/ios/Runner/bridge_generated.h", "macos/Runner/bridge_generated.h"], rust_crate_dir: "/home/alexandre/Downloads/flutter_rust_bridge_template/native", rust_output_path: "/home/alexandre/Downloads/flutter_rust_bridge_template/native/src/bridge_generated.rs", class_name: "Native", dart_format_line_length: 80, dart_enums_style: false, skip_add_mod_to_lib: false, llvm_path: ["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/msys64/mingw64"], llvm_compiler_opts: "", manifest_path: "/home/alexandre/Downloads/flutter_rust_bridge_template/native/Cargo.toml", dart_root: Some("/home/alexandre/Downloads/flutter_rust_bridge_template"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: false, wasm_enabled: true, inline_rust: false, bridge_in_method: true, extra_headers: "" }]
2023/06/06 11:39:18 [DEBUG] Trying to parse "/home/alexandre/Downloads/flutter_rust_bridge_template/native/src/api.rs"
2023/06/06 11:39:18 [DEBUG] Trying to parse "/home/alexandre/Downloads/flutter_rust_bridge_template/native/src/bridge_generated.rs"
2023/06/06 11:39:18 [WARN] Skipping unresolvable module web (tried /home/alexandre/Downloads/flutter_rust_bridge_template/native/src/web.rs, /home/alexandre/Downloads/flutter_rust_bridge_template/native/src/web/mod.rs, /home/alexandre/Downloads/flutter_rust_bridge_template/native/src/bridge_generated/web.rs, /home/alexandre/Downloads/flutter_rust_bridge_template/native/src/bridge_generated/web/mod.rs, )
2023/06/06 11:39:18 [WARN] Skipping unresolvable module io (tried /home/alexandre/Downloads/flutter_rust_bridge_template/native/src/io.rs, /home/alexandre/Downloads/flutter_rust_bridge_template/native/src/io/mod.rs, /home/alexandre/Downloads/flutter_rust_bridge_template/native/src/bridge_generated/io.rs, /home/alexandre/Downloads/flutter_rust_bridge_template/native/src/bridge_generated/io/mod.rs, )
2023/06/06 11:39:18 [DEBUG] parse_function function name: Ident { sym: platform, span: bytes(679..687) }
2023/06/06 11:39:18 [DEBUG] parse_function function name: Ident { sym: rust_release_mode, span: bytes(2411..2428) }
2023/06/06 11:39:18 [DEBUG] parse_function function name: Ident { sym: bug, span: bytes(2483..2486) }
2023/06/06 11:39:18 [ERROR] panicked at 'not yet implemented: generate code for type "Result < i32 , Error >"', frb_codegen/src/ir/ty_unencodable.rs:59:9
thread 'main' panicked at 'not yet implemented: generate code for type "Result < i32 , Error >"', frb_codegen/src/ir/ty_unencodable.rs:59:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: Recipe `gen` failed on line 11 with exit code 101
```

### To Reproduce

Clone this repo and run the codegen: https://github.com/DontBreakAlex/flutter_rust_bridge_template

### Expected behavior

The codegen should work

### OS

Linux

### Version of `flutter_rust_bridge_codegen`

1.77.1

**Comment by fzyzcjy** [comment]
Looks like a bug. Feel free to PR!

**Comment by DontBreakAlex** [comment]
Do you have any idea of why this does not work ? Where should I start looking ?

**Comment by fzyzcjy** [comment]
It says "not implemented". Thus, I suggest using the stack trace (RUST_BACKTRACE=1) to see which line is not implemented and work on it.

**Comment by DontBreakAlex** [comment]
But is it really "not implemented"? I don't think so, the docs say this should work, plus SyncReturn is supposed to delegate to the underlying type, which is Result<i32>, which is definitely implemented. Seeing that the panic is in frb_codegen/src/ir/ty_unencodable.rs:59:9, I would guess that the issue is more likely to be an issue in dispatching somewhere...

**Comment by fzyzcjy** [comment]
Looks reasonable. Then maybe firstly have a look at https://cjycode.com/flutter_rust_bridge/contributing/design.html. Then print/debug on each phase. For example, is the parser correct? Is the code generator correct? etc
