### ISSUE TITLE
[Bug] having two streams

### ISSUE THREAD

**Issue by JustSimplyKyle** [fzyzcjy/flutter_rust_bridge#1282]
### Describe the bug

When having two streams, it doesn't compile successfully.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
2023/07/14 13:00:14 [DEBUG] configs=[Opts { rust_input_path: "/home/kyle/coding/era-connect/app/native/src/api.rs", dart_output_path: "/home/kyle/coding/era-connect/app/lib/bridge_generated.dart", dart_decl_output_path: Some("/home/kyle/coding/era-connect/app/lib/bridge_definitions.dart"), c_output_path: ["/home/kyle/coding/era-connect/app/macos/Runner/bridge_generated.h"], rust_crate_dir: "/home/kyle/coding/era-connect/app/native", rust_output_path: "/home/kyle/coding/era-connect/app/native/src/bridge_generated.rs", class_name: "Native", dart_format_line_length: 80, dart_enums_style: false, skip_add_mod_to_lib: false, llvm_path: ["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/msys64/mingw64"], llvm_compiler_opts: "", manifest_path: "/home/kyle/coding/era-connect/app/native/Cargo.toml", dart_root: Some("/home/kyle/coding/era-connect/app"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: false, wasm_enabled: false, inline_rust: false, bridge_in_method: true, extra_headers: "", dart3: true }]
2023/07/14 13:00:14 [DEBUG] Trying to parse "/home/kyle/coding/era-connect/app/native/src/api.rs"
2023/07/14 13:00:14 [DEBUG] Trying to parse "/home/kyle/coding/era-connect/app/native/src/api/download/mod.rs"
2023/07/14 13:00:14 [DEBUG] Trying to parse "/home/kyle/coding/era-connect/app/native/src/api/download/assets.rs"
2023/07/14 13:00:14 [DEBUG] Trying to parse "/home/kyle/coding/era-connect/app/native/src/api/download/library.rs"
2023/07/14 13:00:14 [DEBUG] Trying to parse "/home/kyle/coding/era-connect/app/native/src/api/download/rules.rs"
2023/07/14 13:00:14 [DEBUG] Trying to parse "/home/kyle/coding/era-connect/app/native/src/api/download/util.rs"
2023/07/14 13:00:14 [DEBUG] Trying to parse "/home/kyle/coding/era-connect/app/native/src/api/vanilla.rs"
2023/07/14 13:00:14 [DEBUG] Trying to parse "/home/kyle/coding/era-connect/app/native/src/bridge_generated.rs"
2023/07/14 13:00:14 [WARN] Skipping unresolvable module io (tried /home/kyle/coding/era-connect/app/native/src/io.rs, /home/kyle/coding/era-connect/app/native/src/io/mod.rs, /home/kyle/coding/era-connect/app/native/src/bridge_generated/io.rs, /home/kyle/coding/era-connect/app/native/src/bridge_generated/io/mod.rs, )
2023/07/14 13:00:14 [DEBUG] parse_function function name: Ident(test)
2023/07/14 13:00:14 [DEBUG] parse_function function name: Ident(launch_quilt)
2023/07/14 13:00:14 [ERROR] panicked at 'insertion index (is 1) should be <= len (is 0)', library/alloc/src/vec/mod.rs:1451:13
thread 'main' panicked at 'insertion index (is 1) should be <= len (is 0)', library/alloc/src/vec/mod.rs:1451:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: Recipe `gen` failed on line 9 with exit code 101
```

### To Reproduce

```rust
#[tokio::main(flavor = "current_thread")]
pub async fn test(
    stream: StreamSink<Progress>,
    stream1: StreamSink<RustOpaque<(LaunchArgs, JvmArgs, GameArgs)>>,
) -> anyhow::Result<()> {
    let c = prepare_vanilla_download().await.unwrap();
    let b = run_download(stream, c).await.unwrap();
    let k = RustOpaque::new(b);
    stream1.add(k);
    Ok(())
}
```
this is not a reproducible, but I think it's pretty obvious.(all types here are all supported by flutter_rust_bridge)

### Expected behavior

to return a tuple or something!

### OS

Arch Linux 6.3.7

### Version of `flutter_rust_bridge_codegen`

1.78.0

### Flutter info

```shell
[!] Flutter (Channel stable, 3.10.6, on Arch Linux 6.3.7-273-tkg-pds, locale en_US.UTF-8)
    • Flutter version 3.10.6 on channel stable at /opt/flutter
    ! Warning: `dart` on your path resolves to /opt/dart-sdk/bin/dart, which is not inside your current Flutter SDK checkout at /opt/flutter. Consider adding /opt/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (31 hours ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✗] Android toolchain - develop for Android devices
    • Android SDK at /opt/android-sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Arch Linux 6.3.7-273-tkg-pds

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.
```

### Version of `clang++`

15.0.7

### Version of `ffigen`

8.0.2

### Additional context

I also tried moving the stream1 to SyncReturn, even tho that compiles, it doesn't "return" the type. 

```rust
#[tokio::main(flavor = "current_thread")]
pub async fn test(
    stream: StreamSink<Progress>,
    stream1: StreamSink<RustOpaque<(LaunchArgs, JvmArgs, GameArgs)>>,
) -> anyhow::Result<()> {
    let c = prepare_vanilla_download().await.unwrap();
    let b = run_download(stream, c).await.unwrap();
    let k = RustOpaque::new(b);
    stream1.add(k);
    Ok(())
}
#[tokio::main(flavor = "current_thread")]
pub async fn launch_quilt(
    stream: StreamSink<Progress>,
    quilt_prepare: RustOpaque<(LaunchArgs, JvmArgs, GameArgs)>,
) -> anyhow::Result<DownloadArgs> {
    let d = prepare_quilt_download(
        "1.20.1".to_string(),
        quilt_prepare.0,
        quilt_prepare.1,
        quilt_prepare.2,
    )
    .await?;
    run_download(stream, d);
    Ok(d)
}
```

**Comment by fzyzcjy** [comment]
IIRC only one stream is supported currently. You can do something like 

```
enum MyItem {
  A(FirstTypeYouWantToSentToStream),
  B(SecondTypeYouWantToSentToStream),
}

stream: StreamSink<MyItem>

**Comment by fzyzcjy** [comment]
> Thanks for the tip! Maybe mention this somewhere on the book? Or shall this enum workaround made automatically by the codegen?

Sure! Feel free to PR to the book, e.g. be in the stream section

> One more question, would a tuple work?

Give it a try ;) It only take a minute

**Comment by JustSimplyKyle** [comment]
huh, surprisngly it doesn't work
```rust
error[E0277]: the trait bound `(vanilla::Progress, LaunchArgs, JvmArgs, GameArgs): flutter_rust_bridge::IntoDart` is not satisfied
   --> src/api/vanilla.rs:495:11
    |
495 |     sink: StreamSink<(Progress, LaunchArgs, JvmArgs, GameArgs)>,
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `flutter_rust_bridge::IntoDart` is not implemented for `(vanilla::Progress, LaunchArgs, JvmArgs, GameArgs)`
    |
    = help: the following other types implement trait `flutter_rust_bridge::IntoDart`:
              ()
              (A, B)
              (A, B, C)
              (A, B, C, D)
              (A, B, C, D, E)
              (A, B, C, D, E, F)
              (A, B, C, D, E, F, G)
              (A, B, C, D, E, F, G, H)
            and 3 others
note: required by a bound in `StreamSink`
   --> /home/kyle/.cargo/registry/src/github.com-1ecc6299db9ec823/flutter_rust_bridge-1.78.0/src/rust2dart.rs:97:26
    |
97  | pub struct StreamSink<T: IntoDart> {
    |                          ^^^^^^^^ required by this bound in `StreamSink`
```

**Comment by fzyzcjy** [comment]
Hmm, feel free to fix it! As for the IntoDart problem, it seems somehow similar to https://github.com/fzyzcjy/flutter_rust_bridge/pull/1281

**Comment by MnlPhlp** [comment]
Probably yes. Are those types with a mirror macro somewhere?
You probably need that and then pass the generated mirror_... Version to the Stream.
Take a look at the added tests in frb_example/pure_dart/rust/src/api.rs in #1281

**Comment by MnlPhlp** [comment]
That will also not work until that pr is merged though :D

**Comment by MnlPhlp** [comment]
This should be fixed by #1285. That PR will allow the tuple approach to work (without explicitly using the mirror_ types)

**Comment by fzyzcjy** [comment]
@MnlPhlp Then maybe we can add a test about this issue, s.t. we can be 100% sure it will never regress

**Comment by MnlPhlp** [comment]
@fzyzcjy There is already a test added for a StreamSink using external Types in a struct. I will add one for a tuple too
