### ISSUE TITLE
[Bug] panicked at 'Failed to parse function argument type `&[f32;3]`'

### ISSUE THREAD

**Issue by Solido** [fzyzcjy/flutter_rust_bridge#1284]
### Describe the bug

Hi!

First I would like to thank you for this awesome tool!

I'm calling `flutter_rust_bridge_codegen` on a rust lib and get

```
[ERROR] panicked at 'Failed to parse function argument type `&[f32;3]`', /Users/r/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-1.78.0/src/parser/mod.rs:219:21
thread 'main' panicked at 'Failed to parse function argument type `&[f32;3]`', /Users/r/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-1.78.0/src/parser/mod.rs:219:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: lib_flutter_rust_bridge_codegen::parser::Parser::parse_function
   3: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   4: lib_flutter_rust_bridge_codegen::parser::parse
   5: lib_flutter_rust_bridge_codegen::config::opts::Opts::get_ir_file
   6: lib_flutter_rust_bridge_codegen::utils::misc::get_symbols_if_no_duplicates
   7: flutter_rust_bridge_codegen::main
```

### To Reproduce

``` rust
pub fn method(rgb: &[f32; 3]) -> [f32; 7] ...
```

_No response_

### OS

MacOS

### Version of `flutter_rust_bridge_codegen`

latest

### Flutter info

```shell
latest
```

### Version of `clang++`

14.0.3

### Version of `ffigen`

latest

**Comment by fzyzcjy** [comment]
IIRC frb does not support `&` yet? Because we should own the data, not borrow (from Dart).
