### ISSUE TITLE
[Bug] Failed to load dynamic library 'libflutter_rust_bridge_example.so': dlopen failed: library "libflutter_rust_bridge_example.so" not found

### ISSUE THREAD

**Issue by Sola-AIGithub** [fzyzcjy/flutter_rust_bridge#1289]
### Describe the bug

When I followed steps for Android from the CI and the first tutorial, and I had checked the file `libflutter_rust_bridge_example.so` is  in `android\app\src\main\jniLibs\arm64-v8a`. It really exist but I still get `"libflutter_rust_bridge_example.so" not found` in my Android Studio Flamingo ver.2022.2.1 Patch 2

```rust
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
W/FlutterActivityAndFragmentDelegate(28996): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Debug service listening on ws://127.0.0.1:60250/2fXOI5yjFTc=/ws
Syncing files to device sdk gphone x86 64...
E/flutter (28996): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libflutter_rust_bridge_example.so': dlopen failed: library "libflutter_rust_bridge_example.so" not found
E/flutter (28996): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter (28996): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter (28996): #2      loadLibForFlutter (package:flutter_rust_bridge/src/load/load.io.dart:11:26)
E/flutter (28996): #3      dylib (package:flutter_rust_bridge_example/ffi.io.dart:7:20)
E/flutter (28996): #4      dylib (package:flutter_rust_bridge_example/ffi.io.dart)
E/flutter (28996): #5      api (package:flutter_rust_bridge_example/ffi.io.dart:8:47)
E/flutter (28996): #6      api (package:flutter_rust_bridge_example/ffi.io.dart)
E/flutter (28996): #7      _MyAppState._callExampleFfiTwo (package:flutter_rust_bridge_example/main.dart:47:32)
E/flutter (28996): #8      _MyAppState.initState (package:flutter_rust_bridge_example/main.dart:31:5)
E/flutter (28996): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5219:55)
E/flutter (28996): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter (28996): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter (28996): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter (28996): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
E/flutter (28996): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
E/flutter (28996): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
E/flutter (28996): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter (28996): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter (28996): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter (28996): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
E/flutter (28996): #20     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
E/flutter (28996): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
E/flutter (28996): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
E/flutter (28996): #23     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5242:11)
E/flutter (28996): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter (28996): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter (28996): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter (28996): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
E/flutter (28996): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
E/flutter (28996): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
E/flutter (28996): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter (28996): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter (28996): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter (28996): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
E/flutter (28996): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
E/flutter (28996): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
E/flutter (28996): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter (28996): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter (28996): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter (28996): #39     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1240:16)
E/flutter (28996): #40     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1209:5)
E/flutter (28996): #41     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1156:18)
E/flutter (28996): #42     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2720:19)
E/flutter (28996): #43     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1155:13)
E/flutter (28996): #44     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:988:7)
E/flutter (28996): #45     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:968:7)
E/flutter (28996): #46     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (28996): #47     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (28996): #48     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (28996): #49     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
E/flutter (28996): 
E/flutter (28996): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libflutter_rust_bridge_example.so': dlopen failed: library "libflutter_rust_bridge_example.so" not found
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
This bug is not with the bridge codegen
```

### To Reproduce

`git clone https://github.com/fzyzcjy/flutter_rust_bridge && cd flutter_rust_bridge/frb_example/with_flutter`

add 2 lines in to `with_flutter\android\gradle.properties`

`ANDROID_NDK=(C:\Users\Sola.EQ-RD-SOLA\AppData\Local\Android\Sdk)`

`org.gradle.jvmargs=-Xmx1536M --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED`

then do the `Tutorial`

`cargo install cargo-ndk`
`rustup target add aarch64-linux-android`
`rustup target add armv7-linux-androideabi`
`rustup target add x86_64-linux-android`
`rustup target add i686-linux-android`
`cargo ndk -o ../android/app/src/main/jniLibs build`
`flutter pub get`
`flutter run`
`flutter build apk`

### Expected behavior

Android Studio virtual machine displays a mandelbrot image in the first card, and no errors in the console.

### OS

x86_64-pc-windows-msvc

### Version of `flutter_rust_bridge_codegen`

flutter_rust_bridge = { workspace = true, features = ["chrono"]}

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.10.5, on Microsoft Windows [版本 10.0.22621.1992], locale zh-TW)
    • Flutter version 3.10.5 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Sola.EQ-RD-SOLA\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at C:\Users\Sola.EQ-RD-SOLA\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[✓] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [版本 10.0.22621.1992]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 114.0.1823.82

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Version of `clang++`

16.0.6

### Additional context

I have checked the following 2 posts and tried their solutions, but none of them worked

`https://github.com/fzyzcjy/flutter_rust_bridge/issues/385`

`https://stackoverflow.com/questions/72273201/flutter-error-when-building-libflutter-rust-bridge-example-for-android-failed-t`

I skipped the process of directory operations in Reproduce, please forgive me.

**Comment by fzyzcjy** [comment]
> I had checked the file libflutter_rust_bridge_example.so is in android\app\src\main\jniLibs\arm64-v8a
Syncing files to device sdk gphone x86 64...

seems you need to ensure it is in the x64 folder

**Comment by Sola-AIGithub** [comment]
Thanks a lot! I tried `cargo ndk -t armeabi-v7a -t arm64-v8a -t x86_64 -t x86 -o ../android/app/src/main/jniLibs build` then x86 and x86_64 folder appeared so did `libflutter_rust_bridge_example.so` files. The Android Studio worked like Windows application!
