### ISSUE TITLE
[ERROR]  Failed to lookup symbol 'clang_createIndex': /lib/x86_64-linux-gnu/libclang-cpp.so.14: undefined symbol: clang_createIndex

### ISSUE THREAD

**Issue by acidicly** [fzyzcjy/flutter_rust_bridge#1293]
Hey, I am running the following command : ```flutter_rust_bridge_codegen --rust-input rust/src/api.rs --dart-output lib/generated_api.dart  --skip-deps-check``` and it errors with the following:
```
Invalid argument(s): Failed to lookup symbol 'clang_createIndex': /lib/x86_64-linux-gnu/libclang-cpp.so.14: undefined symbol: clang_createIndex
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      Clang._clang_createIndexPtr (package:ffigen/src/header_parser/clang_bindings/clang_bindings.dart:108:70)
#2      Clang._clang_createIndexPtr (package:ffigen/src/header_parser/clang_bindings/clang_bindings.dart)
#3      Clang._clang_createIndex (package:ffigen/src/header_parser/clang_bindings/clang_bindings.dart:111:7)
#4      Clang._clang_createIndex (package:ffigen/src/header_parser/clang_bindings/clang_bindings.dart)
#5      Clang.clang_createIndex (package:ffigen/src/header_parser/clang_bindings/clang_bindings.dart:101:12)
#6      parseToBindings (package:ffigen/src/header_parser/parser.dart:56:23)
#7      parse (package:ffigen/src/header_parser/parser.dart:25:20)
#8      main (package:ffigen/src/executables/ffigen.dart:55:19)
```

**Comment by acidicly** [comment]
Installing ```sudo apt-get install libclang-dev``` fixes this. Sorry for opening this issue!
