### ISSUE TITLE
[Bug] Thread 'main' panicked at 'not yet implemented: generate code for type "serde_json :: Value"'

### ISSUE THREAD

**Issue by ashim-kr-saha** [fzyzcjy/flutter_rust_bridge#1295]
### Describe the bug

Not able to generate code when `serde_json::Value` as type. eg

```rust

pub fn list(query: HttpQuery) {
}

pub struct HttpQuery {
    pub select: Option<serde_json::Value>,
}
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
failed to run custom build command for `native v0.1.0 (/Users/user/Desktop/Repo/github.com/project/native)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/user/Desktop/Repo/github.com/project/native/target/debug/build/native-f7d1a7747dfd1e6b/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=src/api.rs

  --- stderr
  thread 'main' panicked at 'not yet implemented: generate code for type "serde_json :: Value"', /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-1.79.0/src/ir/ty_unencodable.rs:59:9
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
     1: core::panicking::panic_fmt
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
     2: <lib_flutter_rust_bridge_codegen::ir::ty_unencodable::IrTypeUnencodable as lib_flutter_rust_bridge_codegen::ir::ty::IrTypeTrait>::safe_ident
     3: <lib_flutter_rust_bridge_codegen::ir::ty::IrType as lib_flutter_rust_bridge_codegen::ir::ty::IrTypeTrait>::safe_ident
     4: lib_flutter_rust_bridge_codegen::ir::file::IrFile::distinct_types::{{closure}}
     5: lib_flutter_rust_bridge_codegen::ir::ty::IrType::visit_types
     6: <lib_flutter_rust_bridge_codegen::ir::ty_struct::IrTypeStructRef as lib_flutter_rust_bridge_codegen::ir::ty::IrTypeTrait>::visit_children_types
     7: <lib_flutter_rust_bridge_codegen::ir::ty::IrType as lib_flutter_rust_bridge_codegen::ir::ty::IrTypeTrait>::visit_children_types
     8: lib_flutter_rust_bridge_codegen::ir::ty::IrType::visit_types
     9: lib_flutter_rust_bridge_codegen::ir::file::IrFile::visit_types
    10: lib_flutter_rust_bridge_codegen::ir::file::IrFile::distinct_types
    11: lib_flutter_rust_bridge_codegen::generator::rust::Generator::generate
    12: lib_flutter_rust_bridge_codegen::generator::rust::generate
    13: lib_flutter_rust_bridge_codegen::ir::file::IrFile::generate_rust
    14: lib_flutter_rust_bridge_codegen::ir::file::IrFile::get_all_symbols
    15: lib_flutter_rust_bridge_codegen::utils::misc::get_symbols_if_no_duplicates
    16: build_script_build::main
    17: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Generated binding code

```shell
fn main() {
    // Only rerun when the API file changes.
    println!("cargo:rerun-if-changed={}", RUST_INPUT);
    let configs = config_parse(RawOpts {
        rust_input: vec![RUST_INPUT.to_string()],
        dart_output: vec![DART_OUTPUT.to_string()],
        wasm: true,
        dart_decl_output: Some(DART_DECL_OUTPUT.into()),
        c_output: Some(vec![C_OUTPUT.into()]),
        extra_c_output_path: Some(vec![EXTRA_C_OUTPUT_PATH.into()]),
        ..Default::default()
    });
    if let Ok(symbols) = get_symbols_if_no_duplicates(&configs) {
        for config in &configs {
            frb_codegen(config, &symbols).unwrap();
        }
    }
}
```

### OS

MacOS

### Version of `flutter_rust_bridge_codegen`

1.78.0

### Flutter info

```shell
✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F82 darwin-arm64, locale en-IN)
    • Flutter version 3.10.6 on channel stable at /Users/ashim/development/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision f468f3366c (2 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version null

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Version of `clang++`

Apple clang version 14.0.3 (clang-1403.0.22.14.1)

### Version of `ffigen`

ffigen: ^8.0.0

**Comment by ashim-kr-saha** [comment]
It is related to https://github.com/fzyzcjy/flutter_rust_bridge/issues/1073

**Comment by fzyzcjy** [comment]
Looks likes frb does not understand Value. Maybe have a try on the "mirror" feature?

**Comment by erikas-taroza** [comment]
Having a similar issue. I am currently on v1.71.0. I updated to v1.79.0 and got a similar message. I think my error is caused by a RustOpaque. But, I haven't changed that code in a while. This issue started happening recently.

[Here is the log](https://github.com/erikas-taroza/simple_audio/actions/runs/5652264228/job/15311612414) from my CI on v1.71.0

**Comment by fzyzcjy** [comment]
Hmm firstly could you please bisect which exact version causes this bug? Secondly, without a deep dig I guess it may be related to https://github.com/fzyzcjy/flutter_rust_bridge/pull/1285.
