### ISSUE TITLE
[Bug] Thread 'main' panicked at 'not yet implemented: generate code for type std::process::Child

### ISSUE THREAD

**Issue by lannb** [fzyzcjy/flutter_rust_bridge#1346]
### Describe the bug

Not able to generate code when std::process::Child as type. eg

`pub struct Vocab {
    pub process: Option<std::process::Child>
}`

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
[ERROR] panicked at 'not yet implemented: generate code for type "std::process::Child"', C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\flutter_rust_bridge_codegen-1.81.0\src\ir\ty_unencodable.rs:59:9
thread 'main' panicked at 'not yet implemented: generate code for type "std::process::Child"', C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\flutter_rust_bridge_codegen-1.81.0\src\ir\ty_unencodable.rs:59:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### OS

Windows

### Version of `flutter_rust_bridge_codegen`

1.81.0

### Flutter info

```shell
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22000.2295], locale
    en-US)
    • Flutter version 3.10.5 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\VGM VietBible\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.29)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community        
    • Visual Studio Community 2019 version 16.11.33927.289
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\VGM VietBible\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.22000.2295]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.111
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.62

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

### Version of `ffigen`

8.0.0

**Comment by fzyzcjy** [comment]
Looks like this cannot be transformed from/to a Dart class, since it is so special (and represents native resource).

Thus, what about using the `Opaque` feature?

**Comment by lannb** [comment]
@fzyzcjy  I tried using the Opaque feature, but I still get that error.

**Comment by fzyzcjy** [comment]
Could you please show a minimal reproducible sample with opaque?

**Comment by lannb** [comment]
@fzyzcjy This is my sample with opaque

`trait ChildOperations {
    fn do_something(&mut self);
}

impl ChildOperations for std::process::Child {
    fn do_something(&mut self) {}
}

pub struct Vocab {
    pub process: Option<Box<dyn ChildOperations>>,
}

impl Vocab {
    pub fn set_local_directory(self, dir: Option<String>) -> Vocab {
        let cmd = Command::new("sh")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .current_dir(dir.as_ref().unwrap())
            .spawn()
            .ok()
            .unwrap();

        return Vocab {
            process: Some(Box::new(cmd)),
            ..self
        };
    }
}`

**Comment by fzyzcjy** [comment]
```
    pub process: Option<Box<dyn ChildOperations>>,
```

it does not seem to use `Opaque`?

**Comment by lannb** [comment]
In Rust, the concept of type erasure and creating opaque types is achieved through traits and associated types, so I think that Rust does not have a specific "opaque" word like some other languages do

**Comment by fzyzcjy** [comment]
Well I mean

https://cjycode.com/flutter_rust_bridge/feature/lang_rust_opaque.html
https://cjycode.com/flutter_rust_bridge/feature/lang_dart_opaque.html
