### ISSUE TITLE
Windows CI fails because corrosion requires a higher cmake version

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#1360]
eg https://github.com/fzyzcjy/flutter_rust_bridge/actions/runs/6211404276/job/16860557313

<details>

```
[+29242 ms] -- The CXX compiler identification is MSVC 19.29.30152.0
[ +436 ms] -- Detecting CXX compiler ABI info
[+1894 ms] -- Detecting CXX compiler ABI info - done
[   +2 ms] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
[  +33 ms] -- Detecting CXX compile features
[  +63 ms] -- Detecting CXX compile features - done
[+5503 ms] CMake Error at D:/a/flutter_rust_bridge/flutter_rust_bridge/frb_example/with_flutter/build/windows/_deps/corrosion-src/CMakeLists.txt:1 (cmake_minimum_required):
[        ] -- Configuring incomplete, errors occurred!
[   +1 ms]   CMake 3.22 or higher is required.  You are running version
[        ] See also "D:/a/flutter_rust_bridge/flutter_rust_bridge/frb_example/with_flutter/build/windows/CMakeFiles/CMakeOutput.log".
[        ]   3.20.21032501-MSVC_2
[  +21 ms] Building Windows application... (completed in 37.2s)
❌ loading D:/a/flutter_rust_bridge/flutter_rust_bridge/frb_example/with_flutter/integration_test/main.dart (failed)
  Exception: Unable to generate build files
  package:flutter_tools/src/base/common.dart 10:3                    throwToolExit
  package:flutter_tools/src/windows/build_windows.dart 176:5         _runCmakeGeneration
  ===== asynchronous gap ===========================
  package:flutter_tools/src/windows/build_windows.dart 85:5          buildWindows
  ===== asynchronous gap ===========================
  package:flutter_tools/src/windows/windows_device.dart 56:5         WindowsDevice.buildForDevice
  ===== asynchronous gap ===========================
  package:flutter_tools/src/desktop_device.dart 119:7                DesktopDevice.startApp
  ===== asynchronous gap ===========================
  package:flutter_tools/src/test/integration_test_device.dart 55:39  IntegrationTestTestDevice.start
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 338:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1391:47                      _rootRun
  dart:async/zone.dart 1301:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 336:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 291:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1399:13                      _rootRun
  dart:async/zone.dart 1301:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 290:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 189:12      _RawReceivePort._handleMessage
```

</details>

**Comment by fzyzcjy** [comment]
Firstly, cc @Desdaemon - maybe we should bump some versions? In addition to the in-tree example, maybe https://github.com/Desdaemon/flutter_rust_bridge_template should also be updated

**Comment by mberry** [comment]
I'm getting this issue despite having a higher cmake version.

```shell
ubuntu@flutter:~/flutter_rust_bridge/frb_example/with_flutter$ flutter run
Launching lib/main.dart on Linux in debug mode...
CMake Error at /home/ubuntu/flutter_rust_bridge/frb_example/with_flutter/build/linux/x64/debug/_deps/corrosion-src/CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.22 or higher is required.  You are running version 3.16.3


Building Linux application...                                           
Exception: Unable to generate build files
ubuntu@flutter:~/flutter_rust_bridge/frb_example/with_flutter$ cmake --version
cmake version 3.27.6

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by fzyzcjy** [comment]
>   CMake 3.22 or higher is required.  You are running version 3.16.3

Hmm just a guess: maybe it is because the build system somehow pick 3.16 even if there are newer versions?

**Comment by mberry** [comment]
For note: I'm running this in an ubuntu 22.04 LXD container, from what  I can tell there is no other cmake on the system. 

Bash can call it correctly and print the version, have tried parsing the build scripts but coming up short here as to why it happens.

**Comment by mberry** [comment]
It could be snap thing

```shell
ubuntu@flutter:~$ which cmake
/snap/bin/cmake
```

**Comment by fzyzcjy** [comment]
That's weird... Maybe run`flutter run --verbose`, and try to print out more other debugging information related to how flutter calls cmake? 

This may also be a problem related to Flutter, if we can successfully reproduce the problem that, a flutter linux project cannot pick the latest cmake.

**Comment by mberry** [comment]
Alright, wall of text inbound: 

```shell
ubuntu@flutter:~/flutter_rust_bridge/frb_example/with_flutter$ flutter run --verbose
[  +27 ms] executing: uname -m
[   +4 ms] Exit code 0 from: uname -m
[        ] x86_64
[ +103 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +97 ms] executing: /home/ubuntu/android/platform-tools/adb devices -l
[  +56 ms] List of devices attached


           * daemon not running; starting now at tcp:5037
           * daemon started successfully
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +98 ms] Skipping pub get: version match.
[ +172 ms] Found plugin integration_test at
/home/ubuntu/snap/flutter/common/flutter/packages/integration_test/
[  +78 ms] Found plugin integration_test at
/home/ubuntu/snap/flutter/common/flutter/packages/integration_test/
[  +47 ms] Found plugin integration_test at
/home/ubuntu/snap/flutter/common/flutter/packages/integration_test/
[  +66 ms] Generating
/home/ubuntu/flutter_rust_bridge/frb_example/with_flutter/android/app/src/main/java/io/flutter/p
lugins/GeneratedPluginRegistrant.java
[  +94 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[   +5 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The
following inputs have updated contents:
/home/ubuntu/flutter_rust_bridge/frb_example/with_flutter/.dart_tool/package_config_subset}
[  +38 ms] Found plugin integration_test at
/home/ubuntu/snap/flutter/common/flutter/packages/integration_test/
[   +5 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +2 ms] complete
[   +3 ms] Launching lib/main.dart on Linux in debug mode...
[   +4 ms] /home/ubuntu/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/home/ubuntu/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.s
napshot --sdk-root
/home/ubuntu/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--incremental --target=flutter --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/a794cf2681c6c9fe7b260e0e84
de96298dc9c18b/ --output-dill /tmp/flutter_tools.OMKOJL/flutter_tool.DMBSDF/app.dill --packages
/home/ubuntu/flutter_rust_bridge/frb_example/with_flutter/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill
build/d1e25e033e83e0237fd5ee906d81ede1.cache.dill.track.dill --verbosity=error
--enable-experiment=alternative-invalidation-strategy
[  +22 ms] Building Linux application...
[  +14 ms] <- compile package:flutter_rust_bridge_example/main.dart
[   +3 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
-DFLUTTER_TARGET_PLATFORM=linux-x64
/home/ubuntu/flutter_rust_bridge/frb_example/with_flutter/linux
[+2965 ms] CMake Error at
/home/ubuntu/flutter_rust_bridge/frb_example/with_flutter/build/linux/x64/debug/_deps/corrosion-
src/CMakeLists.txt:1 (cmake_minimum_required):
[   +2 ms]   CMake 3.22 or higher is required.  You are running version 3.16.3
[        ] -- Configuring incomplete, errors occurred!
[        ] See also
"/home/ubuntu/flutter_rust_bridge/frb_example/with_flutter/build/linux/x64/debug/CMakeFiles/CMak
eOutput.log".
[        ] See also
"/home/ubuntu/flutter_rust_bridge/frb_example/with_flutter/build/linux/x64/debug/CMakeFiles/CMak
eError.log".
[  +16 ms] Building Linux application... (completed in 2,991ms)
[+7730 ms] Exception: Unable to generate build files
[   +2 ms] "flutter run" took 11,602ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +124 ms] ensureAnalyticsSent: 114ms
[        ] Running 1 shutdown hook
[   +9 ms] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by fzyzcjy** [comment]
As mentioned above, maybe we can somehow make a reproducible sample without frb, then we are sure it is a problem with flutter+cmake+linux, and create an issue there.

**Comment by mberry** [comment]
flutter works fine, it's definitely frb that's raising this error

**Comment by mberry** [comment]
"hello world" can run without problems

**Comment by fzyzcjy** [comment]
> flutter works fine, it's definitely frb that's raising this error

Do you mean flutter itself, or flutter with code that requires high cmake version? A minimal reproducible sample may be:

1. create a empty flutter project
2. modify its linux part, probably its cmake files, to print out the cmake version it is using

If the cmake version it is using is lower than what we expect, then we reproduce the bug

**Comment by mberry** [comment]
Yeah flutter can run without any issue.

Flutter Rust Bridge is falling over though?

**Comment by fzyzcjy** [comment]
Sure, that means the flutter itself is installed correctly. So does the "A minimal reproducible sample may be" run well or not?

**Comment by fzyzcjy** [comment]
Looks like @Desdaemon has found a workaround: https://github.com/fzyzcjy/flutter_rust_bridge/pull/1388/files#diff-09f03850fd0479559024e37c49430bf58bd94063b0353a21c1e5e11aab3fb0a2

**Comment by fzyzcjy** [comment]
v2 CI passes :)
