### ISSUE TITLE
[Bug] flutter_rust_bridge_codegen failed: Could not expand rust code at path: <<path>> "cargo" "expand --theme=none --ugly" failed

### ISSUE THREAD

**Issue by druidamix** [fzyzcjy/flutter_rust_bridge#1447]
### Describe the bug

On executing:
flutter_rust_bridge_codegen -v -r native/src/api.rs -d lib/bridge_generated.dart  --dart-decl-output lib/bridge_definitions.dart
it says:

2023/12/18 14:53:46 [INFO] Running cargo expand in '/home/druida/AndroidStudioProjects/demo/native/native'
2023/12/18 14:53:46 [ERROR] panicked at frb_codegen/src/commands.rs:327:13:
Could not expand rust code at path /home/druida/AndroidStudioProjects/demo/native/native: "cargo" "expand --theme=none --ugly" failed

thread 'main' panicked at frb_codegen/src/commands.rs:327:13:
Could not expand rust code at path /home/druida/AndroidStudioProjects/demo/native/native: "cargo" "expand --theme=none --ugly" failed

Running manually cargo expand --theme=none --ugly **--bin**, seems to work

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
Running with backtrace and verbose:
 RUST_BACKTRACE=1 flutter_rust_bridge_codegen -v -r native/src/api.rs -d lib/bridge_generated.dart  --dart-decl-output lib/bridge_definitions.dart
2023/12/18 14:55:26 [DEBUG] configs=[Opts { rust_input_path: "/home/druida/AndroidStudioProjects/demo/native/native/src/api.rs", dart_output_path: "/home/druida/AndroidStudioProjects/demo/native/lib/bridge_generated.dart", dart_decl_output_path: Some("/home/druida/AndroidStudioProjects/demo/native/lib/bridge_definitions.dart"), c_output_path: ["/tmp/.tmpwfBAwZ.h"], rust_crate_dir: "/home/druida/AndroidStudioProjects/demo/native", rust_output_path: "/home/druida/AndroidStudioProjects/demo/native/native/src/bridge_generated.rs", class_name: "Demo", dart_format_line_length: 80, dart_enums_style: false, skip_add_mod_to_lib: false, llvm_path: ["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/msys64/mingw64"], llvm_compiler_opts: "", manifest_path: "/home/druida/AndroidStudioProjects/demo/native/Cargo.toml", dart_root: Some("/home/druida/AndroidStudioProjects/demo"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: false, wasm_enabled: false, inline_rust: false, bridge_in_method: true, extra_headers: "", dart3: true, keep_going: false }]
2023/12/18 14:55:26 [INFO] Running cargo expand in '/home/druida/AndroidStudioProjects/demo/native/native'
2023/12/18 14:55:26 [DEBUG] execute command: bin=cargo args="expand --theme=none --ugly" current_dir=Some("/home/druida/AndroidStudioProjects/demo/native/native") cmd=cd "/home/druida/AndroidStudioProjects/demo/native/native" && "cargo" "expand" "--theme=none" "--ugly"
2023/12/18 14:55:26 [ERROR] panicked at frb_codegen/src/commands.rs:327:13:
Could not expand rust code at path /home/druida/AndroidStudioProjects/demo/native/native: "cargo" "expand --theme=none --ugly" failed

thread 'main' panicked at frb_codegen/src/commands.rs:327:13:
Could not expand rust code at path /home/druida/AndroidStudioProjects/demo/native/native: "cargo" "expand --theme=none --ugly" failed

stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: lib_flutter_rust_bridge_codegen::utils::misc::read_rust_file
   3: lib_flutter_rust_bridge_codegen::config::opts::Opts::get_ir_file
   4: lib_flutter_rust_bridge_codegen::utils::misc::get_symbols_if_no_duplicates
   5: flutter_rust_bridge_codegen::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### OS

Archlinux

### Version of `flutter_rust_bridge_codegen`

1.82.6

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.16.4, on Arch Linux 6.6.7-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.16.4 on channel stable at /home/druida/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (7 days ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/druida/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/druida/Android/Sdk
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6
    • cmake version 3.28.1
    • ninja version 1.11.1
    • pkg-config version 2.1.0

[✓] Android Studio (version 2023.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 77.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 6.6.7-arch1-1
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Version of `clang++`

16.0.6

**Comment by fzyzcjy** [comment]
> Running manually cargo expand --theme=none --ugly --bin, seems to work

Hmm, does `--lib` work for you (manually)? Because the rust code is eventually a library for Dart/Flutter to use

**Comment by druidamix** [comment]
Thank you. I'll wait.

**Comment by fzyzcjy** [comment]
You are welcome!
