### ISSUE TITLE
Failed to lookup symbol 'wire_hello': error code 127

### ISSUE THREAD

**Issue by dunef-io** [fzyzcjy/flutter_rust_bridge#1466]
### Describe the bug

When I rename the function name from the example snippet from greet to something else, the following error occurs:

PanicException(EXECUTE_SYNC_ABORT Invalid argument(s): Failed to lookup symbol 'wire_hello': error code 127 #0

My rust code is the following:

```rust
#[flutter_rust_bridge::frb(sync)] // Synchronous mode for simplicity of the demo
pub fn hello(name: String) -> String {
    format!("Hello, {name}!")
}
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
PanicException(EXECUTE_SYNC_ABORT Invalid argument(s): Failed to lookup symbol 'wire_hello': error code 127 #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      RustLibWire._wire_helloPtr (package:flutter_candle/src/rust/frb_generated.io.dart:147:53)
#2      RustLibWire._wire_helloPtr (package:flutter_candle/src/rust/frb_generated.io.dart)      
#3      RustLibWire._wire_hello (package:flutter_candle/src/rust/frb_generated.io.dart:148:28)  
#4      RustLibWire._wire_hello (package:flutter_candle/src/rust/frb_generated.io.dart)
#5      RustLibWire.wire_hello (package:flutter_candle/src/rust/frb_generated.io.dart:139:12)   
#6      RustLibApiImpl.hello.<anonymous closure> (package:flutter_candle/src/rust/frb_generated.dart:75:21)
#7      BaseHandler.executeSync (package:flutter_rust_bridge/src/main_components/handler.dart:27:32)
#8      RustLibApiImpl.hello (package:flutter_candle/src/rust/frb_generated.dart:72:20)
#9      hello (package:flutter_candle/src/rust/api/simple.dart:10:26)
#10     main (package:flutter_candle/main.dart:10:22)
<asynchronous suspension>
)
#0      BaseHandler.executeSync (package:flutter_rust_bridge/src/main_components/handler.dart:33:7)
#1      RustLibApiImpl.hello (package:flutter_candle/src/rust/frb_generated.dart:72:20)
#2      hello (package:flutter_candle/src/rust/api/simple.dart:10:26)
#3      main (package:flutter_candle/main.dart:10:22)
<asynchronous suspension>
```

**Comment by fzyzcjy** [comment]
Hi, did you run `flutter_rust_bridge_codegen generate`?

**Comment by fzyzcjy** [comment]
Did you stop and fully re-run flutter app, i.e. `flutter run`?

**Comment by dunef-io** [comment]
Ahh okay, yes now it's working, thank you!

**Comment by fzyzcjy** [comment]
You are welcome!
