### ISSUE TITLE
Wrong rust library name is used in dart, if a custom crate name is provided in integrate command.

### ISSUE THREAD

**Issue by M-Tarasov** [fzyzcjy/flutter_rust_bridge#1668]
### Describe the bug

The `kDefaultExternalLibraryLoaderConfig` variable is initialized with `stem = 'rust_lib'` even if an alternative cargo name was provided.

### Steps to reproduce

1. create an empty flutter app;
2. add flutter-rust-bridge support using `flutter_rust_bridge_codegen integrate --rust-crate-name custom_name_api`;
3. try to start app using `flutter run`

### Logs

```shell
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'librust_lib.so': librust_lib.so: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      new ExternalLibrary.open (package:flutter_rust_bridge/src/platform_types/_io.dart:39:47)
#3      loadExternalLibraryRaw.<anonymous closure> (package:flutter_rust_bridge/src/loader/_io.dart:80:46)
#4      loadExternalLibraryRaw.tryAssumingNonPackaged (package:flutter_rust_bridge/src/loader/_io.dart:49:22)
#5      loadExternalLibraryRaw (package:flutter_rust_bridge/src/loader/_io.dart:79:12)
#6      loadExternalLibrary (package:flutter_rust_bridge/src/loader/_io.dart:14:10)
#7      BaseEntrypoint._loadDefaultExternalLibrary (package:flutter_rust_bridge/src/main_components/entrypoint.dart:95:13)
#8      BaseEntrypoint.initImpl (package:flutter_rust_bridge/src/main_components/entrypoint.dart:45:31)
#9      RustLib.init (package:life_os/src/rust/frb_generated.dart:25:20)
#10     main (package:life_os/main.dart:135:17)
#11     _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
#12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

### Generated binding code

```shell
static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
```

### OS

linux

**Comment by fzyzcjy** [comment]
To be fixed in https://github.com/fzyzcjy/flutter_rust_bridge/pull/1669

Before it is fixed, maybe you can run `flutter_rust_bridge_codegen generate` on the folder, and it should fix it.
