### ISSUE TITLE
Undefined symbols error when added rust lib to cargo.toml - FRB v2 

### ISSUE THREAD

**Issue by Mnieme** [fzyzcjy/flutter_rust_bridge#1690]
To begin with, I'd like to express my appreciation for this project—it's truly fantastic. The one-liner integration works seamlessly and is a game changer.

I'm uncertain whether I've stumbled upon a bug or if I may have overlooked a step or a section in the v2 documentation. Specifically, when attempting to use a Rust library in a Flutter project with FRB v2, I encounter a linking error.

> Failed to build iOS app
> Error (Xcode): Undefined symbols:
> 
> Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
> 
> Could not build the application for the simulator.
> Error launching application on iPhone 15 Pro.

I'm aiming to use the Rust library gettext-rs within a Flutter project. 
I've come across the issue https://github.com/fzyzcjy/flutter_rust_bridge/pull/1678. However, in my case, the error I've encountered doesn't provide much assistance in identifying the missing flag.

`cargo build` works fine in rust project, so my assumption is there is some linking missing during generating cocoa pods stuff,

I'd like to just ask if there are some more complex library like in this case what are the necessary steps to make sure its compiled and linked in Xcode project?

( FRB version: 2.0.0-dev.21 )

**Comment by fzyzcjy** [comment]
You are welcome and happy to hear that!

Firstly, frb does not require specific Rust+Dart integration approaches, and it seems that you are using Cargokit for compilation here.

Could you please provide more `verbose` logs (e.g.`flutter run --verbose`) and paste here? Then maybe we can know what undefined symbol it is. For example, after knowing what exact symbol, maybe we know how to add specific things like #1678.

**Comment by Mnieme** [comment]
Thank you for the quick reply. I've attached the logs. The logs were quite extensive, but I assume that these 500 lines of error are crucial. Here are the results for 'flutter run -verbose.

```
           The following build commands failed:
                Ld /Users/Mnieme/Library/Developer/Xcode/DerivedData/Runner-creykikysqjnqjawhljiwgshbegp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/rust_builder.build/Objects-normal/arm64/Binary/rust_builder normal arm64 (in target 'rust_builder' from project 'Pods')
           (1 failure)
[   +9 ms] Running Xcode build... (completed in 4.4s)
[        ] Xcode build done.                                            4.4s
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun xcresulttool get --path /var/folders/_3/_7fpy4tn56v3lh2zswf01z_h0000gn/T/flutter_tools.IKE61q/flutter_ios_build_temp_dir63p9HN/temporary_xcresult_bundle --format json
[  +22 ms] {
             "_type" : {
               "_name" : "ActionsInvocationRecord"
             },
             "actions" : {
               "_type" : {
                 "_name" : "Array"
               },
               "_values" : [
                 {
                   "_type" : {
                     "_name" : "ActionRecord"
                   },
                   "actionResult" : {
                     "_type" : {
                       "_name" : "ActionResult"
                     },
                     "coverage" : {
                       "_type" : {
                         "_name" : "CodeCoverageInfo"
                       }
                     },
                     "issues" : {
                       "_type" : {
                         "_name" : "ResultIssueSummaries"
                       }
                     },
                     "metrics" : {
                       "_type" : {
                         "_name" : "ResultMetrics"
                       }
                     },
                     "resultName" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "action"
                     },
                     "status" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "notRequested"
                     }
                   },
                   "buildResult" : {
                     "_type" : {
                       "_name" : "ActionResult"
                     },
                     "coverage" : {
                       "_type" : {
                         "_name" : "CodeCoverageInfo"
                       }
                     },
                     "issues" : {
                       "_type" : {
                         "_name" : "ResultIssueSummaries"
                       },
                       "errorSummaries" : {
                         "_type" : {
                           "_name" : "Array"
                         },
                         "_values" : [
                           {
                             "_type" : {
                               "_name" : "IssueSummary"
                             },
                             "issueType" : {
                               "_type" : {
                                 "_name" : "String"
                               },
                               "_value" : "Error"
                             },
                             "message" : {
                               "_type" : {
                                 "_name" : "String"
                               },
                               "_value" : "Undefined symbols:"
                             }
                           },
                           {
                             "_type" : {
                               "_name" : "IssueSummary"
                             },
                             "issueType" : {
                               "_type" : {
                                 "_name" : "String"
                               },
                               "_value" : "Error"
                             },
                             "message" : {
                               "_type" : {
                                 "_name" : "String"
                               },
                               "_value" : "Linker command failed with exit code 1 (use -v to see invocation)"
                             }
                           }
                         ]
                       }
                     },
                     "logRef" : {
                       "_type" : {
                         "_name" : "Reference"
                       },
                       "id" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "0~-0pkMb0OHnBS06JKrQFdbRvVGU7cshYE1JuxcaQz65m8-PDhnlHRiMBAvA4Q3QTj-JMLTavAscjtooB27bwiSw=="
                       },
                       "targetType" : {
                         "_type" : {
                           "_name" : "TypeDefinition"
                         },
                         "name" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "ActivityLogSection"
                         }
                       }
                     },
                     "metrics" : {
                       "_type" : {
                         "_name" : "ResultMetrics"
                       },
                       "errorCount" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "2"
                       }
                     },
                     "resultName" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "build"
                     },
                     "status" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "failed"
                     }
                   },
                   "endedTime" : {
                     "_type" : {
                       "_name" : "Date"
                     },
                     "_value" : "2024-01-22T09:50:42.297+0100"
                   },
                   "runDestination" : {
                     "_type" : {
                       "_name" : "ActionRunDestinationRecord"
                     },
                     "displayName" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "iPhone 15 Pro"
                     },
                     "localComputerRecord" : {
                       "_type" : {
                         "_name" : "ActionDeviceRecord"
                       },
                       "busSpeedInMHz" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "cpuCount" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "1"
                       },
                       "cpuKind" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "Apple M1 Pro"
                       },
                       "cpuSpeedInMHz" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "identifier" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "00006000-000828641ED8801E"
                       },
                       "isConcreteDevice" : {
                         "_type" : {
                           "_name" : "Bool"
                         },
                         "_value" : "true"
                       },
                       "logicalCPUCoresPerPackage" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "10"
                       },
                       "modelCode" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "MacBookPro18,3"
                       },
                       "modelName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "MacBook Pro"
                       },
                       "modelUTI" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "com.apple.macbookpro-14-2021"
                       },
                       "name" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "My Mac"
                       },
                       "nativeArchitecture" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "arm64e"
                       },
                       "operatingSystemVersion" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "14.2.1"
                       },
                       "operatingSystemVersionWithBuildNumber" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "14.2.1 (23C71)"
                       },
                       "physicalCPUCoresPerPackage" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "10"
                       },
                       "platformRecord" : {
                         "_type" : {
                           "_name" : "ActionPlatformRecord"
                         },
                         "identifier" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "com.apple.platform.macosx"
                         },
                         "userDescription" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "macOS"
                         }
                       },
                       "ramSizeInMegabytes" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "16384"
                       }
                     },
                     "targetArchitecture" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "arm64"
                     },
                     "targetDeviceRecord" : {
                       "_type" : {
                         "_name" : "ActionDeviceRecord"
                       },
                       "busSpeedInMHz" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "cpuCount" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "cpuSpeedInMHz" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "identifier" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "23FDE6E5-EC70-4814-B965-1D55D812050F"
                       },
                       "isConcreteDevice" : {
                         "_type" : {
                           "_name" : "Bool"
                         },
                         "_value" : "true"
                       },
                       "logicalCPUCoresPerPackage" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "modelCode" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "iPhone16,1"
                       },
                       "modelName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "iPhone 15 Pro"
                       },
                       "modelUTI" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "com.apple.iphone-15-pro-1"
                       },
                       "name" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "iPhone 15 Pro"
                       },
                       "nativeArchitecture" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "arm64"
                       },
                       "operatingSystemVersion" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "17.0.1"
                       },
                       "operatingSystemVersionWithBuildNumber" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "17.0.1 (21A342)"
                       },
                       "physicalCPUCoresPerPackage" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "platformRecord" : {
                         "_type" : {
                           "_name" : "ActionPlatformRecord"
                         },
                         "identifier" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "com.apple.platform.iphonesimulator"
                         },
                         "userDescription" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "iOS Simulator"
                         }
                       },
                       "ramSizeInMegabytes" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       }
                     },
                     "targetSDKRecord" : {
                       "_type" : {
                         "_name" : "ActionSDKRecord"
                       },
                       "identifier" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "iphonesimulator17.2"
                       },
                       "name" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "Simulator - iOS 17.2"
                       },
                       "operatingSystemVersion" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "17.2"
                       }
                     }
                   },
                   "schemeCommandName" : {
                     "_type" : {
                       "_name" : "String"
                     },
                     "_value" : "Run"
                   },
                   "schemeTaskName" : {
                     "_type" : {
                       "_name" : "String"
                     },
                     "_value" : "Build"
                   },
                   "startedTime" : {
                     "_type" : {
                       "_name" : "Date"
                     },
                     "_value" : "2024-01-22T09:50:38.648+0100"
                   },
                   "title" : {
                     "_type" : {
                       "_name" : "String"
                     },
                     "_value" : "Build \"Runner\""
                   }
                 }
               ]
             },
             "issues" : {
               "_type" : {
                 "_name" : "ResultIssueSummaries"
               },
               "errorSummaries" : {
                 "_type" : {
                   "_name" : "Array"
                 },
                 "_values" : [
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Error"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Undefined symbols:"
                     }
                   },
                   {
                     "_type" : {
                       "_name" : "IssueSummary"
                     },
                     "issueType" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Error"
                     },
                     "message" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "Linker command failed with exit code 1 (use -v to see invocation)"
                     }
                   }
                 ]
               }
             },
             "metadataRef" : {
               "_type" : {
                 "_name" : "Reference"
               },
               "id" : {
                 "_type" : {
                   "_name" : "String"
                 },
                 "_value" : "0~3-w_NRnf6UD3ImgyRxTI-W7MyOPEhy3YPFVFacnpH45600v0keT-nRvIK_eTfQS5SiJEnXDOULB3zuN7Yyu25w=="
               },
               "targetType" : {
                 "_type" : {
                   "_name" : "TypeDefinition"
                 },
                 "name" : {
                   "_type" : {
                     "_name" : "String"
                   },
                   "_value" : "ActionsInvocationMetadata"
                 }
               }
             },
             "metrics" : {
               "_type" : {
                 "_name" : "ResultMetrics"
               },
               "errorCount" : {
                 "_type" : {
                   "_name" : "Int"
                 },
                 "_value" : "2"
               }
             }
           }
[   +3 ms] Failed to build iOS app
[   +1 ms] "flutter run" took 12,170ms.
[   +1 ms] Error (Xcode): Undefined symbols:

[        ] Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

[   +1 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 15 Pro.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:790:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[  +52 ms] ensureAnalyticsSent: 51ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1

```

**Comment by fzyzcjy** [comment]
Hmm that's weird, I original expected to see more error details about which symbol is missing... What about using xcode to compile and see what the GUI says - I sometimes get some useful messages from there

**Comment by Mnieme** [comment]
Xcode does not provide much more details:
<img width="836" alt="image" src="https://github.com/fzyzcjy/flutter_rust_bridge/assets/157290063/d5148aa7-9dad-485b-9bd9-04ecea2ec855">

I am also little bit confused. I checked the other project I mentioned in the issue, it works but I guess with older version of frb the compiled libs are linked directly in project Xcode (build phases, link binary with libraries)

**Comment by fzyzcjy** [comment]
Hmm, another attempt may be to look at the compilation artifact (e.g. the .a file)... Btw, is cargokit / rust compilation itself ok? (e.g. put the full log in a gist.github.com to have a look)

**Comment by Mnieme** [comment]
I am not sure if cargokit compilation is ok, here is a full log: https://gist.github.com/Mnieme/95596470f571f72591025123cf3537b7

**Comment by fzyzcjy** [comment]
Hmm I only find

           BASEDIR: /Users/Mnieme/projects/frb_libs/demo_app/rust_builder/cargokit
           CAEGOKIT_TOOL_TEMP_DIR: /Users/Mnieme/Library/Developer/Xcode/DerivedData/Runner-creykikysqjnqjawhljiwgshbegp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/rust_builder.build/build_tool

Could you please `flutter clean` and re-run `flutter run --verbose` to ensure everything compiles from the fresh.

Btw it may also be helpful to ask in cargokit repo and/or the repo of the library you are using as well, since this seems not to be very related to flutter_rust_bridge core.

**Comment by Mnieme** [comment]
I performed a clean build, and the new logs can be found here: https://gist.github.com/Mnieme/667cc45f2afc9dfca4cdb6567d2f6510. Thank you for assisting me with this issue. I'll also reach out to the cargokit community for further help.

**Comment by fzyzcjy** [comment]
> I performed a clean build, and the new logs can be found here:

Hmm same missing information...

            INFO: Building rust_lib for aarch64-apple-ios-sim
            INFO: Building rust_lib for x86_64-apple-ios

and seems that rust itself compiles, so it looks like it compiles but not links.

> Could you just point me what exactly is failing in cargokit process part?

Frb's default Rust+Flutter template uses cargokit (there are other Rust+Flutter approaches discussed in the doc), and here the problem seems that "Rust+Flutter cannot work well".

**Comment by MateusHBR** [comment]
@Mnieme did you tried to add those libraries that are in the build.rs?

https://github.com/tazz4843/whisper-rs/blob/master/sys/build.rs

When I had problems with CPAL that was merged in this example https://github.com/fzyzcjy/flutter_rust_bridge/pull/1678, I've looked the build.rs related to the framework to know which Apple frameworks were necessary to link https://github.com/fzyzcjy/flutter_rust_bridge/pull/1678
