### ISSUE TITLE
Failed to execute `flutter run` when using &mut inside Rust code

### ISSUE THREAD

**Issue by dreamqip** [fzyzcjy/flutter_rust_bridge#1735]
### Describe the bug

The documentation suggests [link](https://cjycode.com/flutter_rust_bridge/#example-2-show-off-skills-) that `&mut` should be working. However, the error occurs when trying to run the project, specifically indicating an issue with the &mut part of the code. If we comment out a method with `&mut` usage, everything works fine.

### Steps to reproduce

1. Clone https://github.com/dreamqip/flutter-rust-reproduction
2. Run `flutter run`

### Logs

```shell
SEVERE: ================================================================================
SEVERE: Cargokit BuildTool failed with error:
SEVERE: --------------------------------------------------------------------------------
SEVERE: External Command: rustup "run" "stable" "cargo" "build" "--manifest-path" "/Users/lorem/Desktop/rust_flutter/rust/Cargo.toml" "-p" "rust_lib" "--target" "aarch64-linux-android" "--target-dir" "/Users/lorem/Desktop/rust_flutter/build/rust_builder/build"
SEVERE: Returned Exit Code: 101
SEVERE: --------------------------------------------------------------------------------
SEVERE: STDOUT:
SEVERE: --------------------------------------------------------------------------------
SEVERE: STDERR:
SEVERE: Compiling rust_lib v0.1.0 (/Users/lorem/Desktop/rust_flutter/rust)
SEVERE: error[E0308]: mismatched types
SEVERE:   --> src/frb_generated.rs:67:77
SEVERE:    |
SEVERE: 67 |                     Result::<_, ()>::Ok(crate::api::simple::Example::answer(&api_that))
SEVERE:    |                                         ----------------------------------- ^^^^^^^^^ types differ in mutability
SEVERE:    |                                         |
SEVERE:    |                                         arguments to this function are incorrect
SEVERE:    |
SEVERE:    = note: expected mutable reference `&mut Example`
SEVERE:                       found reference `&Example`
SEVERE: note: method defined here
SEVERE:   --> src/api/simple.rs:21:12
SEVERE:    |
SEVERE: 21 |     pub fn answer(&mut self) {
SEVERE:    |            ^^^^^^ ---------
SEVERE: 
SEVERE: For more information about this error, try `rustc --explain E0308`.
SEVERE: error: could not compile `rust_lib` (lib) due to previous error
SEVERE: --------------------------------------------------------------------------------
SEVERE: #0      runCommand (package:build_tool/src/util.dart:121:5)
SEVERE: #1      RustBuilder.build (package:build_tool/src/builder.dart:142:5)
SEVERE: <asynchronous suspension>
SEVERE: #2      ArtifactProvider.getArtifacts (package:build_tool/src/artifacts_provider.dart:71:25)
SEVERE: <asynchronous suspension>
SEVERE: #3      BuildGradle.build (package:build_tool/src/build_gradle.dart:35:23)
SEVERE: <asynchronous suspension>
SEVERE: #4      BuildGradleCommand.runBuildCommand (package:build_tool/src/build_tool.dart:65:5)
SEVERE: <asynchronous suspension>
SEVERE: #5      BuildCommand.run (package:build_tool/src/build_tool.dart:37:5)
SEVERE: <asynchronous suspension>
SEVERE: #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
SEVERE: <asynchronous suspension>
SEVERE: #7      runMain (package:build_tool/src/build_tool.dart:251:5)
SEVERE: <asynchronous suspension>
SEVERE: --------------------------------------------------------------------------------
SEVERE: BuildTool arguments: [build-gradle]
SEVERE: ================================================================================

FAILURE: Build failed with an exception.

* Where:
Script '/Users/lorem/Desktop/rust_flutter/rust_builder/cargokit/gradle/plugin.gradle' line: 62

* What went wrong:
Execution failed for task ':rust_builder:cargokitCargoBuildRust_libDebug'.
> Process 'command '/Users/lorem/Desktop/rust_flutter/rust_builder/cargokit/gradle/../run_build_tool.sh'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

### Generated binding code

```shell
// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.23.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.greet(name: name, hint: hint);

class Example {
  final int number;

  const Example({
    required this.number,
  });

  Future<void> answer({dynamic hint}) => RustLib.instance.api.exampleAnswer(
        that: this,
      );

  static Future<void> boo({dynamic hint}) =>
      RustLib.instance.api.exampleBoo(hint: hint);

  Future<int> getNumber({dynamic hint}) =>
      RustLib.instance.api.exampleGetNumber(
        that: this,
      );

  @override
  int get hashCode => number.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Example &&
          runtimeType == other.runtimeType &&
          number == other.number;
}
```

### OS

MacOS

### Version of `flutter_rust_bridge_codegen`

2.0.0-dev.23

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale en-GB)
    • Flutter version 3.16.9 on channel stable at /Users/lorem/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (12 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/lorem/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

### Version of `clang++`

15

**Comment by pantemon** [comment]
I've got the same problem. I saw an issue about allowing support for &mut self so I think it's just not supported. Did anyone solve this problem?

**Comment by fzyzcjy** [comment]
```
SEVERE: note: method defined here
SEVERE:   --> src/api/simple.rs:21:12
SEVERE:    |
SEVERE: 21 |     pub fn answer(&mut self) {
SEVERE:    |            ^^^^^^ ---------
```

Hmm, but https://github.com/dreamqip/flutter-rust-reproduction/blob/main/rust/src/api/simple.rs seems not to have line 21. Could you please provide a minimal reproducible sample?

**Comment by fzyzcjy** [comment]
@pantemon Could you please show a minimal sample? This should be supported, and is well tested.

One scenario I may expect it to not work is that, when a struct is *not* opaque. Then, it is meaningless to be mut - since the struct is copied. But it is good to add hints (e.g. show clear errors) for that. With a minimal reproducible sample, it will be easier to see what concrete scenario it is.

**Comment by dreamqip** [comment]
@fzyzcjy Oh, I see. I must've pushed the wrong code, here's the working example [link](https://github.com/dreamqip/rust_flutter)

**Comment by fzyzcjy** [comment]
https://github.com/dreamqip/rust_flutter/blob/23a773ba78824443f76d343a45c3edaf810bd070/rust/src/api/simple.rs#L12

I see. Then it is because the scenario I mentioned above. One way is to make `Example` have `#[frb(opaque)]`, another way is to not use &mut.

**Comment by dreamqip** [comment]
> [dreamqip/rust_flutter@`23a773b`/rust/src/api/simple.rs#L12](https://github.com/dreamqip/rust_flutter/blob/23a773ba78824443f76d343a45c3edaf810bd070/rust/src/api/simple.rs#L12)
> 
> I see. Then it is because the scenario I mentioned above. One way is to make `Example` have `#[frb(opaque)]`, another way is to not use &mut.

Thank you so much for the explanation! I've done as you said, and now I'm getting the error `The class 'Example' doesn't have an unnamed constructor.` How should I initiate a class with `#[frb(opaque)]`?

**Comment by fzyzcjy** [comment]
> How should I initiate a class with #[frb(opaque)]?

What about

```
impl Example {
 pub fn new() -> Example { Example { ... } }
}
```

**Comment by dreamqip** [comment]
Thank you again for the quick response and this amazing project. You're the best!

**Comment by fzyzcjy** [comment]
You are welcome!
