### ISSUE TITLE
Try to use with a pure dart project

### ISSUE THREAD

**Issue by gdo** [fzyzcjy/flutter_rust_bridge#2001]
### Describe the bug

Hello, I try this commands to use flutter_rust_bridge with a pure dart project

But dart throw an exception, which command did I miss ?

regards

### Steps to reproduce

flutter_rust_bridge_codegen --version
> flutter_rust_bridge_codegen 2.0.0-dev.37

dart create -t console demo
cd demo
flutter_rust_bridge_codegen integrate

edit bin/demo.dart with
```
import 'package:demo/src/rust/api/simple.dart';
import 'package:demo/src/rust/frb_generated.dart';

void main(List<String> arguments) async {
  await RustLib.init();
  print('Hello world: ${greet(name: "Tom")}!');
}
```

flutter_rust_bridge_codegen generate
dart run bin/demo.dart

### Logs

```shell
Unhandled exception:
Invalid argument(s): Failed to load dynamic library 'librust_lib_demo.so': librust_lib_demo.so: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      new ExternalLibrary.open (package:flutter_rust_bridge/src/platform_types/_io.dart:42:47)
#3      loadExternalLibraryRaw.<anonymous closure> (package:flutter_rust_bridge/src/loader/_io.dart:80:46)
#4      loadExternalLibraryRaw.tryAssumingNonPackaged (package:flutter_rust_bridge/src/loader/_io.dart:49:22)
#5      loadExternalLibraryRaw (package:flutter_rust_bridge/src/loader/_io.dart:79:12)
#6      loadExternalLibrary (package:flutter_rust_bridge/src/loader/_io.dart:14:10)
#7      BaseEntrypoint._loadDefaultExternalLibrary (package:flutter_rust_bridge/src/main_components/entrypoint.dart:129:13)
#8      BaseEntrypoint.initImpl (package:flutter_rust_bridge/src/main_components/entrypoint.dart:48:31)
#9      RustLib.init (package:demo/src/rust/frb_generated.dart:25:20)
#10     main (file:///home/gdo/programmation/rETd/rust/demo/bin/demo.dart:5:17)
#11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by fzyzcjy** [comment]
Hi, `flutter_rust_bridge_codegen integrate` creates a project with Flutter. To use pure dart, one way is to copy code in https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/dart_minimal as a starting point.

**Comment by gdo** [comment]
Thanks I will try

**Comment by fzyzcjy** [comment]
You are welcome!

**Comment by fzyzcjy** [comment]
Close because of inactivity, but feel free to reopen or ping me if having any questions!
