### ISSUE TITLE
Panic with stream and customized rust log struct

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#2162]
With latestest FRB V2.0.0, After reading the[ Stream doc](https://cjycode.com/flutter_rust_bridge/guides/types/translatable/stream), I test with such rust code:
```rust
#[frb]
pub struct LogEntry {
    #[frb(name = "type")]
    pub type_: String,
    pub message: String,
    pub time: String,
}

// impl SseEncode for LogEntry {
//     // fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
//     //     todo!()
//     // }
// }

use chrono::Local;

pub fn on_tick(sink: StreamSink<LogEntry>) -> Result<()> {
    let mut ticks = 0;
    let event_types = ["ERROR", "WARN", "INFO"];
    loop {
        let event_type = event_types[ticks % 3].to_string();
        let log_entry = LogEntry {
            type_: event_type.clone(),
            message: format!("this is a `{}` msg.", event_type),
            time: Local::now().format("%Y-%m-%d %H:%M:%S.%2f").to_string(),
        };
        sink.add(log_entry);
        sleep(Duration::from_secs(1));
        if ticks == usize::MAX {
            break;
        }
        ticks += 1;
    }
    Ok(())
}
```

and use it like this in Dart:
```Dart
  void startLogStream() {
    api.onTick().listen((logEntry) {
      try {
   
      } catch (e) {
        print('处理日志条目时出错: $e');
      }
    }, onError: (error) {
      print('日志流错误: $error');
    });
  }
```
Here,  even the `try` block is empty, it ran into panic:
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/17372655/0cb8e060-555b-478a-9209-0a8f1e6616f6)

and according to the debug stack, it seems related to the  flutter_rust_bridge:
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/17372655/ea9988df-d1b6-419e-9ad5-3b7f3e6c32f8)

Am I using the stream in the wrong way?

**Comment by fzyzcjy** [comment]
Firstly, try to get the full panic backtrace. (https://cjycode.com/flutter_rust_bridge/guides/how-to/stack-trace) Then we can check what is on that panic backtrace to see what panics.

**Comment by dbsxdbsx** [comment]
I add the following code in `api/simpl.rs`:
```rust
#[frb(init)]
pub fn lets_init_app_here() {
    std::env::set_var("RUST_BACKTRACE", "full");
}
```
and the debug output something like this:
```
[GETX] Instance "HomeViewController" has been created
thread '<unnamed>' panicked at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081\library\alloc\src\string.rs:2559:14:
a Display implementation returned an error unexpectedly: Error
stack backtrace:
   0:     0x7fffce537ad8 - <unknown>
   1:     0x7fffce556cc9 - <unknown>
   2:     0x7fffce5338e1 - <unknown>
   3:     0x7fffce5378b6 - <unknown>
   4:     0x7fffce5399b8 - <unknown>
   5:     0x7fffce539627 - <unknown>
   6:     0x7fffce539ee8 - <unknown>
   7:     0x7fffce539da7 - <unknown>
   8:     0x7fffce53844f - <unknown>
   9:     0x7fffce539a58 - <unknown>
  10:     0x7fffce57a734 - <unknown>
  11:     0x7fffce57ac50 - <unknown>
  12:     0x7fffce256c83 - <unknown>
  13:     0x7fffce28a741 - <unknown>
  14:     0x7fffce3049ee - <unknown>
  15:     0x7fffce295da3 - <unknown>
  16:     0x7fffce295d71 - <unknown>
  17:     0x7fffce32a77a - <unknown>
  18:     0x7fffce263511 - <unknown>
  19:     0x7fffce2fd3a5 - <unknown>
  20:     0x7fffce303623 - <unknown>
  21:     0x7fffce2f4294 - <unknown>
  22:     0x7fffce25dfa3 - <unknown>
  23:     0x7fffce329b80 - <unknown>
  24:     0x7fffce32b4ab - <unknown>
  25:     0x7fffce4ec771 - <unknown>
  26:     0x7fffce4ebd3a - <unknown>
  27:     0x7fffce543abd - <unknown>
[GETX] Instance "HomeViewController" has been initialized
  28:     0x7ff831277344 - BaseThreadInitThunk
  29:     0x7ff831d626b1 - RtlUserThreadStart
```

The `HomeViewController` is the dart class where the `startLogStream()` defined.

**Comment by dbsxdbsx** [comment]
And the generated Dart class is like this:
```dart
Stream<LogEntry> onTick() => RustLib.instance.api.crateApiSimpleOnTick();

class LogEntry {
  final String type;
  final String message;
  final String time;

  const LogEntry({
    required this.type,
    required this.message,
    required this.time,
  });

  @override
  int get hashCode => type.hashCode ^ message.hashCode ^ time.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogEntry &&
          runtimeType == other.runtimeType &&
          type == other.type &&
          message == other.message &&
          time == other.time;
}

```

**Comment by fzyzcjy** [comment]
Hmm, maybe try to get the symbols of the stacktrace and we can see what is going on. To do this, maybe google about it (e.g. ensure symbols are not stripped, or use a symbolicator afterwards, etc)

**Comment by dbsxdbsx** [comment]
what you said is a little hard to do.  But after debugging with commenting(out) one line by one line.  I found the issue is due to this line: `time: Local::now().format("%Y-%m-%d %H:%M:%S.%2f").to_string(),`.  It seems to be a wrong syntex with `.%2f`. 
So I finally change the rust code into this:
```rust
#[frb]
pub struct LogEntry {
    #[frb(name = "type")]
    pub type_: String,
    pub message: String,
    pub time: String,
}

use time::{format_description, OffsetDateTime};

pub fn on_tick(sink: StreamSink<LogEntry>) -> Result<()> {
    let mut ticks = 0;
    let event_types = ["ERROR", "WARN", "INFO"];
    loop {
        let event_type = event_types[ticks % 3].to_string();
        let format = format_description::parse(
            "[year]-[month]-[day] [hour]:[minute]:[second].[subsecond digits:2]",
        )
        .unwrap();

        let log_entry = LogEntry {
            type_: event_type.clone(),
            message: format!("this is a `{}` msg.", event_type),
            // time: Local::now().format("%Y-%m-%d %H:%M:%S.%2f").to_string(),
            time: OffsetDateTime::now_local()
                .unwrap()
                .format(&format)
                .unwrap(),
        };
        sink.add(log_entry).expect("添加日志出错");
        sleep(Duration::from_secs(1));
        if ticks == usize::MAX {
            break;
        }
        ticks += 1;
    }
    Ok(())
}
```
My issue is now perfectly solved. But Hopefully, the rust API panic info could be stopped at a more constructive place.

**Comment by fzyzcjy** [comment]
> Hopefully, the rust API panic info could be stopped at a more constructive place

If I guess correctly, the stack trace will point to that line of code. Thus IMHO the panic is already in the correct place.

**Comment by dbsxdbsx** [comment]
> > Hopefully, the rust API panic info could be stopped at a more constructive place
> 
> If I guess correctly, the stack trace will point to that line of code. Thus IMHO the panic is already in the correct place.

I'm afraid NO!  If you take my very first rust code snippet and use it with `onListen` in Dart, the following is all stack trace:
```
#0      SimpleDecoder.decode (package:flutter_rust_bridge/src/codec/base.dart:35:9)
#1      SseCodec._decode (package:flutter_rust_bridge/src/codec/sse.dart:42:55)
#2      SseCodec.decodeObject (package:flutter_rust_bridge/src/codec/sse.dart:32:12)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:876:13)
#5      Future._completeWithValue (dart:async/future_impl.dart:652:5)
#6      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:722:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
Maybe this is not a drawback of FRB, but flutter/dart, since I always got running panic within flutter/dart official std code.
But if feasible, I hope that the stack trace could point to a more constructive place---in my case, is the code in `rust/src/api/simple.rs`.

**Comment by fzyzcjy** [comment]
> the following is all stack trace of the running panic:Maybe this is not a drawback of FRB, but flutter/dart, since I always got running panic within flutter/dart official std code.

IIRC yes, Dart async makes stacktrace look like that...

**Comment by dbsxdbsx** [comment]
Oh~ Now I see, and I guess so, too.
