### ISSUE TITLE
libtau.so on Android.

### ISSUE THREAD

**Issue by Larpoux** [fzyzcjy/flutter_rust_bridge#2219]
A very simple question : I have no major problems on iOS, but my tries always fall on Android because it does not find my lib (libtau.so).
My questions are : 
- who creates this lib, and where must it be placed,
- is there somewhere where I can read how the setup is done on Android (I did not find informations on frb doc)

**Comment by Larpoux** [comment]
I Added these lines in my build.gradle : 
```gradle

// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
apply from: "../cargokit/gradle/plugin.gradle"

cargokit {
    manifestDir = "../rust"
    libname = "tau"
}
// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

```
And now I cannot compile : 
```
Please choose one (or "q" to quit): 1
Launching lib/main.dart on sdk gphone16k arm64 in debug mode...
INFO: Precompiled binaries are disabled
INFO: Building tau for aarch64-linux-android
SEVERE: ================================================================================
SEVERE: Cargokit BuildTool failed with error:
SEVERE: --------------------------------------------------------------------------------
SEVERE: External Command: rustup "run" "stable" "cargo" "build" "--manifest-path" "/Volumes/mac-J/larpoux/projmac/tau/tau_rust/rust/Cargo.toml" "-p" "tau" "--target" "aarch64-linux-android" "--target-dir" "/Volumes/mac-J/larpoux/projmac/tau/tau_rust/example/build/tau/build"
SEVERE: Returned Exit Code: 101
SEVERE: --------------------------------------------------------------------------------
SEVERE: STDOUT:
SEVERE: --------------------------------------------------------------------------------
SEVERE: STDERR:
SEVERE: Compiling log v0.4.22
SEVERE:    Compiling serde_json v1.0.120
SEVERE:    Compiling serde-value v0.6.0
SEVERE:    Compiling serde_yaml v0.8.26
SEVERE:    Compiling oslog v0.2.0
SEVERE:    Compiling arc-swap v1.7.1
SEVERE:    Compiling no_denormals v0.1.2
SEVERE:    Compiling convert_case v0.5.0
SEVERE: The following warnings were emitted during compilation:
SEVERE: 
SEVERE: warning: oslog@0.2.0: wrapper.c:1:10: fatal error: 'os/log.h' file not found
SEVERE: warning: oslog@0.2.0: #include <os/log.h>
SEVERE: warning: oslog@0.2.0:          ^~~~~~~~~~
SEVERE: warning: oslog@0.2.0: 1 error generated.
SEVERE: 
SEVERE: error: failed to run custom build command for `oslog v0.2.0`
SEVERE: 
SEVERE: Caused by:
SEVERE:   process didn't exit successfully: `/Volumes/mac-J/larpoux/projmac/tau/tau_rust/example/build/tau/build/debug/build/oslog-97669f303f47878b/build-script-build` (exit status: 1)
SEVERE:   --- stdout
SEVERE:   OUT_DIR = Some(/Volumes/mac-J/larpoux/projmac/tau/tau_rust/example/build/tau/build/aarch64-linux-android/debug/build/oslog-9f501ce24124e580/out)
SEVERE:   TARGET = Some(aarch64-linux-android)
SEVERE:   OPT_LEVEL = Some(0)
SEVERE:   HOST = Some(aarch64-apple-darwin)
SEVERE:   cargo:rerun-if-env-changed=CC_aarch64-linux-android
SEVERE:   CC_aarch64-linux-android = Some(/Volumes/mac-J/larpoux/android-sdk-macosx/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang)
SEVERE:   RUSTC_WRAPPER = None
SEVERE:   cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
SEVERE:   cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
SEVERE:   CRATE_CC_NO_DEFAULTS = None
SEVERE:   DEBUG = Some(true)
SEVERE:   cargo:rerun-if-env-changed=CFLAGS_aarch64-linux-android
SEVERE:   CFLAGS_aarch64-linux-android = Some(--target=aarch64-linux-android21)
SEVERE:   cargo:warning=wrapper.c:1:10: fatal error: 'os/log.h' file not found
SEVERE:   cargo:warning=#include <os/log.h>
SEVERE:   cargo:warning=         ^~~~~~~~~~
SEVERE:   cargo:warning=1 error generated.
SEVERE: 
SEVERE:   --- stderr
SEVERE: 
SEVERE: 
SEVERE:   error occurred: Command "/Volumes/mac-J/larpoux/android-sdk-macosx/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang" "-O0" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "--target=aarch64-linux-android" "--target=aarch64-linux-android21" "-o" "/Volumes/mac-J/larpoux/projmac/tau/tau_rust/example/build/tau/build/aarch64-linux-android/debug/build/oslog-9f501ce24124e580/out/d1fba762150c532c-wrapper.o" "-c" "wrapper.c" with args clang did not execute successfully (status code exit status: 1).
SEVERE: 
SEVERE: 
SEVERE: warning: build failed, waiting for other jobs to finish...
SEVERE: --------------------------------------------------------------------------------
SEVERE: #0      runCommand (package:build_tool/src/util.dart:118:5)
SEVERE: #1      RustBuilder.build (package:build_tool/src/builder.dart:139:5)
SEVERE: <asynchronous suspension>
SEVERE: #2      ArtifactProvider.getArtifacts (package:build_tool/src/artifacts_provider.dart:68:25)
SEVERE: <asynchronous suspension>
SEVERE: #3      BuildGradle.build (package:build_tool/src/build_gradle.dart:32:23)
SEVERE: <asynchronous suspension>
SEVERE: #4      BuildGradleCommand.runBuildCommand (package:build_tool/src/build_tool.dart:62:5)
SEVERE: <asynchronous suspension>
SEVERE: #5      BuildCommand.run (package:build_tool/src/build_tool.dart:34:5)
SEVERE: <asynchronous suspension>
SEVERE: #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
SEVERE: <asynchronous suspension>
SEVERE: #7      runMain (package:build_tool/src/build_tool.dart:248:5)
SEVERE: <asynchronous suspension>
SEVERE: --------------------------------------------------------------------------------
SEVERE: BuildTool arguments: [build-gradle]
SEVERE: ================================================================================

FAILURE: Build failed with an exception.

* Where:
Script '/Volumes/mac-J/larpoux/projmac/tau/tau_rust/cargokit/gradle/plugin.gradle' line: 65

* What went wrong:
Execution failed for task ':tau:cargokitCargoBuildTauDebug'.
> Process 'command '/Volumes/mac-J/larpoux/projmac/tau/tau_rust/cargokit/gradle/../run_build_tool.sh'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
Running Gradle task 'assembleDebug'...                             31.3s
Error: Gradle task assembleDebug failed with exit code 1
```

But perhaps I can find the solution by myself. Sorry to polluate your server

**Comment by fzyzcjy** [comment]
Hi, what about trying this recently added feature: https://cjycode.com/flutter_rust_bridge/quickstart

![image](https://github.com/user-attachments/assets/58729e5d-a458-4545-9f39-a02a6b980899)

Then a flutter package can be auto created.

Since you have existing code, one way may be create a new flutter package using that command, and then migrate the existing code to there.

**Comment by Larpoux** [comment]
I am sorry to bother you again, but I need help.
I created a new App using https://cjycode.com/flutter_rust_bridge/quickstart.
It works fine on iOS, but it feels on Android because it is not able to load `libtau.so`.
I checked that there are 3 files in my `apk` : 
- ./lib/x86/libtau.so
- ./lib/arm64-v8a/libtau.so
- ./lib/x86_64/libtau.so

The falling is : 
```dart
  @patch
  factory DynamicLibrary.open(String path) {
    return _open(path);
  }
```
And the value of `path` is `libtau.so`.

Probably I should ask help to people maintaining `FFI` and not to FRB people ?

**Comment by fzyzcjy** [comment]
Firstly, what android architecture are you using? (e.g. if it is 32bit arm then the file will not be there). Secondly, does the quickstart without any modification works (then we should check what change make it fail), or it does not work?

**Comment by Larpoux** [comment]
I use an Android emulator running `Android Api 35  arm64-v8a`.
No, I just run the app created with https://cjycode.com/flutter_rust_bridge/quickstart without doing any modification.

**Comment by fzyzcjy** [comment]
Hmm that's weird. We do test it on CI: https://github.com/fzyzcjy/flutter_rust_bridge/blob/9e5c6e54723700e8436bc76016173e0391befa8e/.github/workflows/ci.yaml#L761.

**Comment by Larpoux** [comment]
This is my command line:
```sh
flutter_rust_bridge_codegen create tau --org xyz.canardoux  --template plugin
```

**Comment by fzyzcjy** [comment]
I think that's pretty reasonable. Could you please try to run https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/flutter_package directly?

**Comment by Larpoux** [comment]
> Could you please try to run https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/flutter_package directly?

I get this error : 
```
Running Gradle task 'assembleDebug'...
../../../frb_dart/lib/src/platform_types/platform_types.dart:4:2: Error: Undefined name 'internal'.
@internal
 ^^^^^^^^
../../../frb_dart/lib/src/platform_types/platform_types.dart:4:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@internal
 ^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Volumes/mac-J/larpoux/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
Error: Gradle task assembleDebug failed with exit code 1
```

**Comment by fzyzcjy** [comment]
Hmm... Are you using latest flutter/dart version?

**Comment by Larpoux** [comment]
```
larpoux@Mac-mini:~/projmac/toto/papa$ dart --version
Dart SDK version: 3.4.4 (stable) (Wed Jun 12 15:54:31 2024 +0000) on "macos_arm64"
larpoux@Mac-mini:~/projmac/toto/papa$ flutter channel
Flutter channels:
  master (latest development branch, for contributors)
  main (latest development branch, follows master channel)
  beta (updated monthly, recommended for experienced users)
* stable (updated quarterly, for new users and for production app releases)
larpoux@Mac-mini:~/projmac/toto/papa$ flutter --version
Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (3 weeks ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3
larpoux@Mac-mini:~/projmac/toto/papa$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.91.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

**Comment by Larpoux** [comment]
I switched to the Main Flutter Channel but it's not better

**Comment by fzyzcjy** [comment]
I am indeed confused about the flutter compilation error, since dart is cross platform, and that example repo is always tested using ci on multiple platforms...

**Comment by Larpoux** [comment]
I tried also https://github.com/irondash/hello_rust_ffi_plugin, and the problem is same.

![Screenshot 2024-08-04 at 15 10 50](https://github.com/user-attachments/assets/c4855aa9-4c6f-4405-a460-3c04121d7fde)

I wonder if the problem is that it is looking for 
lib/arm64/libhello_rust_ffi_plugin.so
instead of
arm64-v8a/libhello_rust_ffi_plugin.so

**Comment by fzyzcjy** [comment]
Yes that looks reasonable - if the folder name is wrong then it should fail. Maybe this can be asked on cargokit?

**Comment by Larpoux** [comment]
Thank you @fzyzcjy  for the help. 💯 
I created a new virtual machine under Android API 33, and it runs fine 😄
I do not understand what happened with my my emulator under API 35, but I don't care.
Now I am going to try τ (Tau) under Android. Thank you again.

**Comment by Larpoux** [comment]
Now, I am back on τ .
I have again this following error: 
I remember that my first tries on Android, several month ago, gave also this error.
I more or less remember that I was able to turn around this, with a copy of `log.h` somewhere.
I am going to do that again, but I want you to know this issue.
```
INFO: Precompiled binaries are disabled
INFO: Building tau for aarch64-linux-android
SEVERE: ================================================================================
SEVERE: Cargokit BuildTool failed with error:
SEVERE: --------------------------------------------------------------------------------
SEVERE: External Command: rustup "run" "stable" "cargo" "build" "--manifest-path" "/Volumes/mac-J/larpoux/projmac/tau/tau_rust/rust/Cargo.toml" "-p" "tau" "--target" "aarch64-linux-android" "--target-dir" "/Volumes/mac-J/larpoux/projmac/tau/tau_rust/example/build/tau/build"
SEVERE: Returned Exit Code: 101
SEVERE: --------------------------------------------------------------------------------
SEVERE: STDOUT:
SEVERE: --------------------------------------------------------------------------------
SEVERE: STDERR:
SEVERE: Compiling oslog v0.2.0
SEVERE:    Compiling web-audio-api v1.0.0-rc.6
SEVERE:    Compiling flutter_logger v0.6.1
SEVERE:    Compiling extend v1.2.0
SEVERE:    Compiling sink v0.1.0
SEVERE: The following warnings were emitted during compilation:
SEVERE: 
SEVERE: warning: oslog@0.2.0: wrapper.c:1:10: fatal error: 'os/log.h' file not found
SEVERE: warning: oslog@0.2.0: #include <os/log.h>
SEVERE: warning: oslog@0.2.0:          ^~~~~~~~~~
SEVERE: warning: oslog@0.2.0: 1 error generated.
SEVERE: 
SEVERE: error: failed to run custom build command for `oslog v0.2.0`
SEVERE: 
SEVERE: Caused by:
SEVERE:   process didn't exit successfully: `/Volumes/mac-J/larpoux/projmac/tau/tau_rust/example/build/tau/build/debug/build/oslog-97669f303f47878b/build-script-build` (exit status: 1)
SEVERE:   --- stdout
SEVERE:   OUT_DIR = Some(/Volumes/mac-J/larpoux/projmac/tau/tau_rust/example/build/tau/build/aarch64-linux-android/debug/build/oslog-9f501ce24124e580/out)
SEVERE:   TARGET = Some(aarch64-linux-android)
SEVERE:   OPT_LEVEL = Some(0)
SEVERE:   HOST = Some(aarch64-apple-darwin)
SEVERE:   cargo:rerun-if-env-changed=CC_aarch64-linux-android
SEVERE:   CC_aarch64-linux-android = Some(/Volumes/mac-J/larpoux/android-sdk-macosx/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang)
SEVERE:   RUSTC_WRAPPER = None
SEVERE:   cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
SEVERE:   cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
SEVERE:   CRATE_CC_NO_DEFAULTS = None
SEVERE:   DEBUG = Some(true)
SEVERE:   cargo:rerun-if-env-changed=CFLAGS_aarch64-linux-android
SEVERE:   CFLAGS_aarch64-linux-android = Some(--target=aarch64-linux-android21)
SEVERE:   cargo:warning=wrapper.c:1:10: fatal error: 'os/log.h' file not found
SEVERE:   cargo:warning=#include <os/log.h>
SEVERE:   cargo:warning=         ^~~~~~~~~~
SEVERE:   cargo:warning=1 error generated.
SEVERE: 
SEVERE:   --- stderr
SEVERE: 
SEVERE: 
SEVERE:   error occurred: Command "/Volumes/mac-J/larpoux/android-sdk-macosx/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang" "-O0" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "--target=aarch64-linux-android" "--target=aarch64-linux-android21" "-o" "/Volumes/mac-J/larpoux/projmac/tau/tau_rust/example/build/tau/build/aarch64-linux-android/debug/build/oslog-9f501ce24124e580/out/d1fba762150c532c-wrapper.o" "-c" "wrapper.c" with args clang did not execute successfully (status code exit status: 1).
SEVERE: 
SEVERE: 
SEVERE: warning: build failed, waiting for other jobs to finish...
SEVERE: --------------------------------------------------------------------------------
SEVERE: #0      runCommand (package:build_tool/src/util.dart:118:5)
SEVERE: #1      RustBuilder.build (package:build_tool/src/builder.dart:139:5)
SEVERE: <asynchronous suspension>
SEVERE: #2      ArtifactProvider.getArtifacts (package:build_tool/src/artifacts_provider.dart:68:25)
SEVERE: <asynchronous suspension>
SEVERE: #3      BuildGradle.build (package:build_tool/src/build_gradle.dart:32:23)
SEVERE: <asynchronous suspension>
SEVERE: #4      BuildGradleCommand.runBuildCommand (package:build_tool/src/build_tool.dart:62:5)
SEVERE: <asynchronous suspension>
SEVERE: #5      BuildCommand.run (package:build_tool/src/build_tool.dart:34:5)
SEVERE: <asynchronous suspension>
SEVERE: #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
SEVERE: <asynchronous suspension>
SEVERE: #7      runMain (package:build_tool/src/build_tool.dart:248:5)
SEVERE: <asynchronous suspension>
SEVERE: --------------------------------------------------------------------------------
SEVERE: BuildTool arguments: [build-gradle]
SEVERE: ================================================================================

FAILURE: Build failed with an exception.

* Where:
Script '/Volumes/mac-J/larpoux/projmac/tau/tau_rust/cargokit/gradle/plugin.gradle' line: 65

* What went wrong:
Execution failed for task ':tau:cargokitCargoBuildTauDebug'.
> Process 'command '/Volumes/mac-J/larpoux/projmac/tau/tau_rust/cargokit/gradle/../run_build_tool.sh'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 33s
Error: Gradle task assembleDebug failed with exit code 1
```

**Comment by Larpoux** [comment]
Sorry, guys and girls.
My previous problem was not with FRB.
But because I had in my Cargo.toml : `oslog = "0.2.0"`.

Sorry to have disturb you

**Comment by fzyzcjy** [comment]
Happy to see it works and it's OK, no worries!

**Comment by fzyzcjy** [comment]
Btw to have logs, IIRC frb already auto provide a simple logging solution (at least good for debugging), so no need for oslog by default

**Comment by Larpoux** [comment]
Good day for me. I am able to compile/link/and run web-audio-api-rs both on Android and iOS.
Web-Audio-API-RS  actually doesn't work on Android but this is not a FRB problem.

**Comment by fzyzcjy** [comment]
That looks great!
