### ISSUE TITLE
Unhandled Exception when returning an Err in Stream function

### ISSUE THREAD

**Issue by Tienisto** [fzyzcjy/flutter_rust_bridge#2415]
### Describe the bug

The following Rust function throws an `Unhandled Exception` in Dart/Flutter:

```rust
pub async fn create_stream(stream_sink: StreamSink<i32>) -> Result<(), String> {
    tokio::time::sleep(Duration::from_secs(1)).await;

    let _ = stream_sink.add(42);

    tokio::time::sleep(Duration::from_secs(1)).await;

    Err("Some Error".to_string())
}
```

Throws:

```text
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Some Error
#0      SimpleDecoder.decode (package:flutter_rust_bridge/src/codec/base.dart:32:9)
#1      SseCodec._decode (package:flutter_rust_bridge/src/codec/sse.dart:45:55)
#2      SseCodec.decodeObject (package:flutter_rust_bridge/src/codec/sse.dart:35:12)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:861:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:890:13)
#5      Future._completeWithValue (dart:async/future_impl.dart:666:5)
#6      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:736:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

This is difficult to catch on Dart side:

```dart
createStream().listen((event) {
  print('>>> Stream event: $event');
}, onError: (error) {
  // this is not called!
  print('>>> Stream error: $error');
});
```

Reproduction Repo: https://github.com/Tienisto/frb_stream_error

### Steps to reproduce

Return `Err` in Rust that takes a `StreamSink`

### Logs

```shell
Code generator works fine.
```

**Comment by fzyzcjy** [comment]
Hmm what about

```rust
pub async fn create_stream(stream_sink: StreamSink<i32>) {
    tokio::time::sleep(Duration::from_secs(1)).await;

    let _ = stream_sink.add(42);

    tokio::time::sleep(Duration::from_secs(1)).await;

	stream_sink.add_error("Some Error".to_string())
}
```

**Comment by Tienisto** [comment]
Yeah, this fixed the problem! Maybe we should add a warning that the return value of a function with `StreamSink` should be removed / has no usage

**Comment by fzyzcjy** [comment]
That looks reasonable, and feel free to PR for this! The simplest form may be just add a few lines to the doc.
