### ISSUE TITLE
Failed to build code in connection with mongodb 3.1.1

### ISSUE THREAD

**Issue by omolayoabegunde** [fzyzcjy/flutter_rust_bridge#2472]
### Describe the bug

After creating the database model and the Flutter connection, running this command `flutter_rust_bridge_codegen` will produce the error. I navigated to the rust directory and built the rust code. It's just fine. Exiting the path and coming back to the main Flutter project is the problem.

### Steps to reproduce

flutter_rust_bridge_codegen generate
[2024-12-27T18:13:20.978Z WARN /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/commands/command_runner.rs:153] command="sh" "-c" "\"fvm\" \"--version\"" stdout= stderr=sh: line 1: fvm: command not found

[2024-12-27T18:13:20.978Z INFO /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/commands/fvm.rs:15] Has .fvmrc but no fvm binary installation, thus skip using fvm.
[21.2s] Parse ⠈
  └── [21.2s] Cargo expand & syn parse                                                                                                                                              [2024-12-27T18:13:42.844Z ERROR /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/utils/logs.rs:54] panicked at /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/codegen/parser/mir/parser/ty/concrete.rs:118:38:
index out of bounds: the len is 0 but the index is 0
thread 'main' panicked at /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/codegen/parser/mir/parser/ty/concrete.rs:118:38:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Logs

```shell
flutter_rust_bridge_codegen generate
[2024-12-27T18:13:20.978Z WARN /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/commands/command_runner.rs:153] command="sh" "-c" "\"fvm\" \"--version\"" stdout= stderr=sh: line 1: fvm: command not found

[2024-12-27T18:13:20.978Z INFO /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/commands/fvm.rs:15] Has .fvmrc but no fvm binary installation, thus skip using fvm.
[21.2s] Parse ⠈
  └── [21.2s] Cargo expand & syn parse                                                                                                                                              [2024-12-27T18:13:42.844Z ERROR /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/utils/logs.rs:54] panicked at /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/codegen/parser/mir/parser/ty/concrete.rs:118:38:
index out of bounds: the len is 0 but the index is 0
thread 'main' panicked at /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/codegen/parser/mir/parser/ty/concrete.rs:118:38:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### OS

Fedora

### Version of `flutter_rust_bridge_codegen`

2.7.0

### Flutter info

```shell
flutter_rust_bridge_codegen generate
[2024-12-27T18:13:20.978Z WARN /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/commands/command_runner.rs:153] command="sh" "-c" "\"fvm\" \"--version\"" stdout= stderr=sh: line 1: fvm: command not found

[2024-12-27T18:13:20.978Z INFO /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/commands/fvm.rs:15] Has .fvmrc but no fvm binary installation, thus skip using fvm.
[21.2s] Parse ⠈
  └── [21.2s] Cargo expand & syn parse                                                                                                                                              [2024-12-27T18:13:42.844Z ERROR /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/utils/logs.rs:54] panicked at /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/codegen/parser/mir/parser/ty/concrete.rs:118:38:
index out of bounds: the len is 0 but the index is 0
thread 'main' panicked at /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/codegen/parser/mir/parser/ty/concrete.rs:118:38:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by fzyzcjy** [comment]
Hi, could you please provide a minimal reproducible sample? Then this can be debugged.

**Comment by omolayoabegunde** [comment]
[2024-12-28T13:43:32.701Z ERROR /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/utils/logs.rs:54] panicked at /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/codegen/ir/hir/flat/function.rs:41:69:
called `Result::unwrap()` on an `Err` value: attr="# [frb (async)]"

Caused by:
    expected one of: `non_final`, `sync`, `dart_async`, `stream_dart_await`, `getter`, `setter`, `init`, `ignore`, `opaque`, `non_opaque`, `non_hash`, `non_eq`, `positional`, `proxy`, `external`, `type_64bit_int`, `rust_opaque_codec_moi`, `serialize`, `semi_serialize`, `ui_state`, `ui_mutation`, `mirror`, `dart_metadata`, `default`, `dart_code`, `name`, `dart2rust`, `rust2dart`
thread 'main' panicked at /home/rapture/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-2.7.0/src/library/codegen/ir/hir/flat/function.rs:41:69:
called `Result::unwrap()` on an `Err` value: attr="# [frb (async)]"

Caused by:
    expected one of: `non_final`, `sync`, `dart_async`, `stream_dart_await`, `getter`, `setter`, `init`, `ignore`, `opaque`, `non_opaque`, `non_hash`, `non_eq`, `positional`, `proxy`, `external`, `type_64bit_int`, `rust_opaque_codec_moi`, `serialize`, `semi_serialize`, `ui_state`, `ui_mutation`, `mirror`, `dart_metadata`, `default`, `dart_code`, `name`, `dart2rust`, `rust2dart`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by omolayoabegunde** [comment]
Thanks for your prompt response. I change it from frb("sync") to frb, it generated successfully.

**Comment by fzyzcjy** [comment]
Close since solved :)
