### ISSUE TITLE
Error while decoding tuple inside Option

### ISSUE THREAD

**Issue by VladTheJunior** [fzyzcjy/flutter_rust_bridge#2473]
### Describe the bug

Error occurs with Option<(bool, u32, DateTime<Utc>)> , if I use (bool, u32, DateTime<Utc>) it works fine. 
Without full_dep there is also no errors. As temp fix now I just use struct instead of tuple

### Steps to reproduce

1. Enable full_dep: true
2.  function on rust side
```
#[flutter_rust_bridge::frb(sync)] // Synchronous mode for simplicity of the demo
pub fn test() -> Option<(bool, u32, DateTime<Utc>)> {
    Some((true, 25, Utc::now()))
}
```
3. call it in dart
```
print(test());
```

### Logs

```shell
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type '(bool, int, DateTime)' in type cast
#0      RustLibApiImpl.dco_decode_box_autoadd_record_bool_u_32_chrono_utc (package:test/src/rust/frb_generated.dart:154:16)
#1      RustLibApiImpl.dco_decode_opt_box_autoadd_record_bool_u_32_chrono_utc (package:test/src/rust/frb_generated.dart:169:11)
#2      _DcoSimpleDecoder.decodeSuccess (package:flutter_rust_bridge/src/codec/dco.dart:47:35)
#3      SimpleDecoder.decode (package:flutter_rust_bridge/src/codec/base.dart:29:16)
#4      DcoCodec.decodeObject (package:flutter_rust_bridge/src/codec/dco.dart:25:45)
#5      DcoCodec.decodeWireSyncType (package:flutter_rust_bridge/src/codec/dco.dart:30:7)
#6      BaseHandler.executeSync (package:flutter_rust_bridge/src/main_components/handler.dart:34:25)
#7      RustLibApiImpl.crateApiSimpleTest (package:test/src/rust/frb_generated.dart:118:20)
#8      test (package:test/src/rust/api/simple.dart:9:55)
#9      main (package:test/main.dart:9:9)
```

### OS

Windows

### Version of `flutter_rust_bridge_codegen`

2.7.0

**Comment by fzyzcjy** [comment]
> Without full_dep there is also no errors.

Then it seems to be caused by how tuple+option is handled in CST/DCO codec. As long as the use case does not have observable performance degrading, using full_dep=false is not an issue.

**Comment by VladTheJunior** [comment]
I can't switch back to full_dep=false, it simpler to rewrite code using struct. 
But is it bug related to frb, or some another lib, or is it even dart side related?

**Comment by fzyzcjy** [comment]
Both full_dep=false and ful_dep=true support (almost) the same feature set; it is just different codecs. The bug may be related to CST/DCO codec.

**Comment by fzyzcjy** [comment]
Close since discussions are made above and there are clear workaround
