### ISSUE TITLE
[Bug] library "libflutter_rust_bridge_example.so" not found

### ISSUE THREAD

**Issue by sisou** [fzyzcjy/flutter_rust_bridge#385]
### Describe the bug

Following the `with_flutter` example/tutorial does not work. Running the integration test fails with the same error:

```
integration_test/main.dart starts!
00:22 +0: end-to-end test run and wait to see if there is memory problem                                                                                                                                          
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following ArgumentError was thrown running a test:
Invalid argument(s): Failed to load dynamic library 'libflutter_rust_bridge_example.so': dlopen
failed: library "libflutter_rust_bridge_example.so" not found

When the exception was thrown, this was the stack:
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      dylib (package:flutter_rust_bridge_example/main.dart:19:26)
#3      dylib (package:flutter_rust_bridge_example/main.dart)
#4      api (package:flutter_rust_bridge_example/main.dart:20:47)
#5      api (package:flutter_rust_bridge_example/main.dart)
#6      _MyAppState._callExampleFfiTwo (package:flutter_rust_bridge_example/main.dart:55:32)
#7      _MyAppState.initState (package:flutter_rust_bridge_example/main.dart:39:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4893:57)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3524:20)
#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#14     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#15     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1175:5)
#16     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1189:7)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#18     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#19     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#20     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#22     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#23     LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:1458:13)
#24     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#28     _invoke (dart:ui/hooks.dart:151:10)
#29     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#30     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)

The test description was:
  run and wait to see if there is memory problem
════════════════════════════════════════════════════════════════════════════════════════════════════
00:22 +0 -1: end-to-end test run and wait to see if there is memory problem [E]                                                                                                                                   
  Test failed. See exception logs above.
  The test description was: run and wait to see if there is memory problem
```

### Codegen logs with `RUST_LOG=debug` env variable

```shell
= This bug is not with the bridge codegen =
```

### To Reproduce

I followed all steps for Android from the CI and the first tutorial:

```bash
cd frb_example/with_flutter
cargo install cargo-ndk
rustup target add x86_64-linux-android aarch64-linux-android armv7-linux-androideabi
flutter pub get
cd rust
cargo ndk -o ../android/app/src/main/jniLibs build
cd ..
flutter run # connects to Android Studio emulated Android 11 device

# alternatively run integration test
flutter test integration_test/main.dart --verbose
```

### Expected behavior

App displays a mandelbrot image in the first card. No errors in the console.

### Generated binding code

```shell
= generated binding code was not changed from what is shipped in the example =
```

### OS

Fedora Workstation 35

### Version of `flutter_rust_bridge_codegen`

1.22.1

### Flutter info

```shell
[✓] Flutter (Channel stable, 2.10.3, on Fedora Linux 35 (Workstation Edition)
    5.16.12-200.fc35.x86_64, locale en_US.UTF-8)
    • Flutter version 2.10.3 at $HOME/Android/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (6 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at $HOME/Android/Sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: $HOME/bin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.0 (Fedora 13.0.0-3.fc35)
    • cmake version 3.22.2
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.1)
    • Android Studio at $HOME/bin/android-studio
    • Flutter plugin version 65.1.2
    • Dart plugin version 211.7808
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API
      30) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Fedora Linux 35
      (Workstation Edition) 5.16.12-200.fc35.x86_64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome
      99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Version of `clang++`

13.0.0 (Fedora 13.0.0-3.fc35)

### Version of `cbindgen`

0.20.0

### Version of `ffigen`

4.1.3

### Additional context

```
rustc 1.59.0 (9d1b2106e 2022-02-23)
cargo 1.59.0 (49d8809dc 2022-02-10)
```

**Comment by fzyzcjy** [comment]
Nice and detailed issue report :) Let me have a look

**Comment by fzyzcjy** [comment]
> connects to Android Studio emulated Android 11 device

Wait, have we generated x86/x64 architecture `.so` files? Maybe try to generate for those platforms, or use a real phone.

**Comment by fzyzcjy** [comment]
If that fails to work, please examine the Flutter generated `.apk` file, and see whether there are expected `.so` files inside or not.

**Comment by sisou** [comment]
I did not realize that the simulator was not 64-bit. 

Checking `flutter devices` showed me that the emulator is a `x86` architecture.

I needed to install the `i686-linux-android` rustup target, and compile the rust code with `cargo ndk -t x86 ...`.

Then `flutter run` was able to pack the correct `.so` file.

Would it be possible to throw a build error when the file for the targeted architecture is not available?

**Comment by fzyzcjy** [comment]
> Would it be possible to throw a build error when the file for the targeted architecture is not available?

What about modifying the build script

**Comment by sisou** [comment]
I have now searched far and wide through the interwebs, and I could not find any way to access the currently built-for architecture in a `build.gradle` file to check if the file exists. So if you have any pointers, please share :wink:

**Comment by Desdaemon** [comment]
@sisou IIRC what `cargo-ndk` does under the hood is running `cargo build` for each of the specified architectures, then copy the .so files into the jniLibs/<arch> folder; you can for example check if the folder and/or file exists then throw an error.
