### ISSUE TITLE
Add CI for `codegen` that runs on Windows and on MacOS (originally only on Linux) - because users also use those two platforms

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#42]

**Comment by fzyzcjy** [comment]
seems not ok

```
[2021-10-07T00:44:40Z WARN  flutter_rust_bridge_codegen::commands] command output: Output { status: ExitStatus(ExitStatus(65280)), stdout: "Running in Directory: '/home/runner/work/flutter_rust_bridge/flutter_rust_bridge/frb_codegen'\n[SEVERE] : Couldn't find dynamic library in default locations.\n[SEVERE] : Please supply one or more path/to/llvm in ffigen's config under the key 'llvm-path'.\n", stderr: "Unhandled exception:\nException: Couldn't find dynamic library in default locations.\n#0      findDylibAtDefaultLocations (package:ffigen/src/config_provider/spec_utils.dart:330:3)\n#1      Config._getSpecs.<anonymous closure> (package:ffigen/src/config_provider/config.dart:203:29)\n#2      Config._extract (package:ffigen/src/config_provider/config.dart:189:50)\n#3      new Config.fromYaml (package:ffigen/src/config_provider/config.dart:139:17)\n#4      getConfigFromCustomYaml (package:ffigen/src/executables/ffigen.dart:120:17)\n#5      getConfig (package:ffigen/src/executables/ffigen.dart:69:14)\n#6      main (package:ffigen/src/executables/ffigen.dart:47:14)\n#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)\n#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)\n" }
```

**Comment by fzyzcjy** [comment]
stuck for an hour. after cancel see:

```
Run KyleMayes/install-llvm-action@v1.4.1

Installing LLVM and Clang 12 (12.0.1)...
Downloading and extracting 'https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/LLVM-12.0.1-win64.exe'...
C:\ProgramData\Chocolatey\bin\7z.exe x D:\a\_temp\3a7e2deb-c4e8-455e-b444-0deb94570b31 "-oC:\Program Files\LLVM"

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 190997504 bytes (183 MiB)

Extracting archive: D:\a\_temp\3a7e2deb-c4e8-455e-b444-0deb94570b31
--
Path = D:\a\_temp\3a7e2deb-c4e8-455e-b444-0deb94570b31
Type = Nsis
Physical Size = 190997504
Method = LZMA:25
Solid = +
Headers Size = 220752
Embedded Stub Size = 114688
SubType = NSIS-3


Would you like to replace the existing file:
  Path:     C:\Program Files\LLVM\bin\LLVM-C.dll
  Size:     69279744 bytes (67 MiB)
  Modified: 2021-07-09 10:39:50
with the file from archive:
  Path:     bin\LLVM-C.dll
  Size:     69279744 bytes (67 MiB)
  Modified: 2021-07-09 10:39:50
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 
```

**Comment by fzyzcjy** [comment]
win error:

```
Run cargo run --package flutter_rust_bridge_codegen --bin flutter_rust_bridge_codegen -- \
ParserError: D:\a\_temp\45a11494-533a-450d-bbcc-a7163cd00fcb.ps1:3
Line |
   3 |    --rust-input ../frb_example/pure_dart/rust/src/api.rs \
     |      ~
     | Missing expression after unary operator '--'.

Error: Process completed with exit code 1.
```

**Comment by fzyzcjy** [comment]
windows:

```
[2021-10-07T01:56:40Z DEBUG flutter_rust_bridge_codegen::commands] execute ffigen c_path=C:\Users\RUNNER~1\AppData\Local\Temp\.tmpvrriHH.h dart_path=C:\Users\RUNNER~1\AppData\Local\Temp\.tmpIbeJMY
[2021-10-07T01:56:40Z DEBUG flutter_rust_bridge_codegen::commands] execute command: "dart" "pub" "global" "run" "ffigen" "--config" "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\.tmp7LwFOW"
[2021-10-07T01:56:40Z WARN  flutter_rust_bridge_codegen::commands] command output: Output { status: ExitStatus(ExitStatus(65)), stdout: "", stderr: "No active package ffigen.\n" }
thread 'main' panicked at 'command execution failed. command="dart" "pub" "global" "run" "ffigen" "--config" "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\.tmp7LwFOW"', src\commands.rs:25:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\flutter_rust_bridge_codegen.exe --rust-input ../frb_example/pure_dart/rust/src/api.rs --dart-output ../frb_example/pure_dart/dart/lib/bridge_generated.dart --dart-format-line-length 120` (exit code: 101)
Error: Process completed with exit code 1.
```
