### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lattice0** [fzyzcjy/flutter_rust_bridge#538]
### Describe the bug

```
pub fn return_a() -> A {
    todo!()
}

#[derive(Debug, Clone)]
pub struct A {
    pub event_type: EventType,
}

#[derive(Debug, Clone)]
pub enum EventType {
    ProfileF64(ProfileEvent<f64>),
}

#[derive(Debug, Clone)]
pub struct ProfileEvent<T> {
    pub value: T,
}

```

gives

```
[2022-06-29T01:37:38Z INFO  flutter_rust_bridge_codegen] Phase: Parse source code to AST
[2022-06-29T01:37:38Z INFO  flutter_rust_bridge_codegen] Phase: Parse AST to IR
thread 'main' panicked at 'parse_type failed for ty=ProfileEvent<f64>', src/parser/ty.rs:125:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

is there something wrong? 

I also tried

```
pub fn return_profile_event() -> ProfileEvent<f64> {
    todo!()
}

#[derive(Debug, Clone)]
pub struct ProfileEvent<T> {
    pub value: T,
}
```

and got

```
[2022-06-29T01:39:34Z INFO  flutter_rust_bridge_codegen] Phase: Parse source code to AST
[2022-06-29T01:39:34Z INFO  flutter_rust_bridge_codegen] Phase: Parse AST to IR
thread 'main' panicked at 'Failed to parse function output type `ProfileEvent<f64>`', src/parser/mod.rs:148:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
[2022-06-29T01:40:15Z DEBUG flutter_rust_bridge_codegen::source_graph] Trying to parse "/home/dev/project/libsomething/src/glutin_renderer/renderer.rs"
[2022-06-29T01:40:15Z DEBUG flutter_rust_bridge_codegen::source_graph] WARNING: flatten_use_tree() found an import rename (use a::b as c). flatten_use_tree() will now abort.
[2022-06-29T01:40:15Z DEBUG flutter_rust_bridge_codegen::source_graph] WARNING: This happened while parsing Path(UsePath { ident: Ident(glium), colon2_token: Colon2, tree: Path(UsePath { ident: Ident(glutin), colon2_token: Colon2, tree: Path(UsePath { ident: Ident(event), colon2_token: Colon2, tree: Group(UseGroup { brace_token: Brace, items: [Name(UseName { ident: Ident(ElementState) }), Comma, Rename(UseRename { ident: Ident(Event), as_token: As, rename: Ident(GliumEvent) }), Comma, Name(UseName { ident: Ident(KeyboardInput) }), Comma, Name(UseName { ident: Ident(VirtualKeyCode) }), Comma, Name(UseName { ident: Ident(WindowEvent) }), Comma] }) }) }) })
[2022-06-29T01:40:15Z DEBUG flutter_rust_bridge_codegen::source_graph] WARNING: This use statement will be ignored.
[2022-06-29T01:40:15Z DEBUG flutter_rust_bridge_codegen::source_graph] Trying to parse "/home/dev/project/libsomething/src/types.rs"
[2022-06-29T01:40:15Z DEBUG flutter_rust_bridge_codegen::parser] parse_function function name: Ident(return_profile_event)
thread 'main' panicked at 'Failed to parse function output type `ProfileEvent<f64>`', src/parser/mod.rs:148:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by fzyzcjy** [comment]
Could you please try

```
pub struct A {
    pub event_type: EventType,
}
```

change to 

```
pub struct A {
    pub event_type: Box<EventType>,
}
```

**Comment by fzyzcjy** [comment]
I guess it is because generics may not be supported currently, but I am not sure, since things like `Vec<u8>` works.

What about trying `type ProfileEventOfF64 = ProfileEvent<f64>;` and use that. Does it error?

**Comment by lattice0** [comment]
```

pub fn return_a() -> A {
    todo!()
}

#[derive(Debug, Clone)]
pub struct A {
    pub event_type: Box<EventType>,
}

#[derive(Debug, Clone)]
pub enum EventType {
    ProfileF64(ProfileEvent<f64>),
}

#[derive(Debug, Clone)]
pub struct ProfileEvent<T> {
    pub value: T,
}
```

gives


```
[2022-06-29T02:05:45Z INFO  flutter_rust_bridge_codegen] Phase: Parse source code to AST
[2022-06-29T02:05:45Z INFO  flutter_rust_bridge_codegen] Phase: Parse AST to IR
thread 'main' panicked at 'parse_type failed for ty=ProfileEvent<f64>', src/parser/ty.rs:125:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**and**

```
pub fn return_a() -> A {
    todo!()
}

#[derive(Debug, Clone)]
pub struct A {
    pub event_type: Box<EventType>,
}

type ProfileEventF64 = ProfileEvent<f64>;

#[derive(Debug, Clone)]
pub enum EventType {
    ProfileF64(ProfileEventF64),
}

#[derive(Debug, Clone)]
pub struct ProfileEvent<T> {
    pub value: T,
}
```

gives
```
[2022-06-29T02:07:11Z INFO  flutter_rust_bridge_codegen] Phase: Parse source code to AST
[2022-06-29T02:07:11Z INFO  flutter_rust_bridge_codegen] Phase: Parse AST to IR
thread 'main' panicked at 'parse_type failed for ty=ProfileEventF64', src/parser/ty.rs:125:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

as well

**Comment by fzyzcjy** [comment]
If `ProfileEventF64` (or ProfileEvent) is not generics will it error?

**Comment by lattice0** [comment]
```

pub fn return_a() -> A {
    todo!()
}

#[derive(Debug, Clone)]
pub struct A {
    pub event_type: Box<EventType>,
}

struct ProfileEventF64 {
    value: f64
}

#[derive(Debug, Clone)]
pub enum EventType {
    ProfileF64(ProfileEventF64),
}
```

works.

So generics are not supported at all?

**Comment by fzyzcjy** [comment]
Juding from experiment, at least not for arbitrary. But we know `Vec<f64>` works.

So feel free to PR!

**Comment by lattice0** [comment]
```
pub fn return_event() -> Event {
    todo!()
}

pub struct Event {
    pub event_type: Box<EventType>,
}

macro_rules! impl_profile_event {
    ($type:ty,$name:ident) => {
        pub struct $name {
            pub value: $type,
        }
    };
}

impl_profile_event!(f64, ProfileEventF64);

pub enum EventType {
    ProfileF64(Box<ProfileEventF64>),
}
```

gives

```
[2022-06-29T02:28:00Z INFO  flutter_rust_bridge_codegen] Phase: Parse source code to AST
[2022-06-29T02:28:00Z INFO  flutter_rust_bridge_codegen] Phase: Parse AST to IR
thread 'main' panicked at 'parse_type failed for ty=Box<ProfileEventF64>', src/parser/ty.rs:125:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think the parsing occurs before macro expansion maybe?

Because this works:
```

pub fn return_event() -> Event {
    todo!()
}

pub struct Event {
    pub event_type: Box<EventType>,
}

pub struct ProfileEventF64 {
    pub value: f64,
}

pub enum EventType {
    /// General floating point things
    ProfileF64(Box<ProfileEventF64>),
}
```

so I guess I can't use generics neither macros :(

I'm still learning the library, one day I'll help, because for sure I'm gonna use in my app :)

**Comment by fzyzcjy** [comment]
> I think the parsing occurs before macro expansion maybe?

Yes. Seems no way to let parse happen after macro expansion - same as all other libs in rust I guess. If you find some lib which supports so please tell me!

> I'm still learning the library, one day I'll help, because for sure I'm gonna use in my app :)

Take your time and feel free to ask questions :)
