### ISSUE TITLE
[Bug] Returning enum from function?

### ISSUE THREAD

**Issue by terhechte** [fzyzcjy/flutter_rust_bridge#551]
### Describe the bug

I'm trying to return an enum with associated values:

``` rs
/// api.rs
pub enum State {
  Setup { name: String }
  Working(u8)
  Done
}

pub fn process(step: u8) -> State {
 ...
}
```

However, when I try to do that, I get a weird error regarding a pub spec in async (see logs). When I remove the associated values (`name: String` and `u8`) from the enum, I don't get the error. I also tried boxing the values or boxing the enum to no avail. Is this not supported?

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
[2022-07-05T13:54:21Z INFO  lib_flutter_rust_bridge_codegen::commands] Running build_runner at /Users/terhechte/Development/flutter_test
[2022-07-05T13:54:21Z WARN  lib_flutter_rust_bridge_codegen::commands] command="sh" "-c" "cd \"/Users/terhechte/Development/flutter_test\" && dart run build_runner build --delete-conflicting-outputs" stdout= stderr=Could not find a file named "pubspec.yaml" in "/Users/terhechte/.pub-cache/hosted/pub.dartlang.org/async-2.8.2".
    #0      new Pubspec.load (package:pub/src/pubspec.dart:307:7)
    #1      new Package.load (package:pub/src/package.dart:128:29)
    #2      SystemCache.load (package:pub/src/system_cache.dart:105:20)
    #3      Entrypoint._createPackageGraph (package:pub/src/entrypoint.dart:119:63)
    #4      Entrypoint.packageGraph (package:pub/src/entrypoint.dart:114:54)
    #5      getExecutableForCommand (package:pub/src/executable.dart:338:19)
    #6      RunCommand.run (package:dartdev/src/commands/run.dart:250:32)
    #7      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
    #8      DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:30)
    #9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
    #10     new Future.sync (dart:async/future.dart:301:31)
    #11     CommandRunner.run (package:args/command_runner.dart:119:14)
    #12     runDartdev (package:dartdev/dartdev.dart:66:29)
    #13     main (file:///opt/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
    #14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
    #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
    
    
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to run build_runner for /Users/terhechte/Development/flutter_test: ', /Users/terhechte/.cargo/registry/src/github.com-1ecc6299db9ec823/flutter_rust_bridge_codegen-1.36.0/src/main.rs:20:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: Recipe `gen` failed on line 16 with exit code 101
```

### OS

macOS

**Comment by fzyzcjy** [comment]
> [2022-07-05T13:54:21Z WARN  lib_flutter_rust_bridge_codegen::commands] command="sh" "-c" "cd \"/Users/terhechte/Development/flutter_test\" && dart run build_runner build --delete-conflicting-outputs" stdout= stderr=Could not find a file named "pubspec.yaml" in "/Users/terhechte/.pub-cache/hosted/pub.dartlang.org/async-2.8.2".

Sounds like your pub cache has problem? what about `flutter clean` everything and reinstall pub dependency packages

**Comment by terhechte** [comment]
Thanks! Adding ‘build_runner’ and ‘flutter clean’ did the trick!
