### ISSUE TITLE
No function named `new_with_null_ptr`

### ISSUE THREAD

**Issue by TENX-S** [fzyzcjy/flutter_rust_bridge#560]
frb version: 1.37.1
rustc: 1.62.0 stable
macOS 12.4

<img width="1080" alt="Screen Shot 2022-07-09 at 08 57 15" src="https://user-images.githubusercontent.com/40336192/178085834-9e855dd0-12d5-4a7d-b764-f05cc959762f.png">

**Comment by fzyzcjy** [comment]
could you please provide a minimal reproducible sample, especially what is the api.rs?

**Comment by TENX-S** [comment]
api.rs:
```rust
#[derive(Debug, Serialize, Deserialize)]
pub enum Scope {
    Project,
    Setting,
    Trash,
    Request,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Command {
    pub scope: Box<Scope>,
    pub body: String,
}

pub fn execute(command: Command) -> ZeroCopyBuffer<Vec<u8>> {
    println!("{:#?}", command);
    ZeroCopyBuffer(vec![1,2,3])
}
```

**Comment by fzyzcjy** [comment]
Interesting. Could you please make a PR and add failing tests into the pure_dart example? Notice there are already examples there about such enums, so maybe just modify the existing ones as little as possible.

**Comment by TENX-S** [comment]
I'll give it a try

**Comment by TENX-S** [comment]
when running codegen:
```
flutter_rust_bridge_codegen --rust-input rust/src/api.rs --dart-output dart/lib/bridge_generated.dart --dart-format-line-length 120
```

I got this error:
```shell
thread 'main' panicked at 'parse_type failed for ty=N', /Users/tenx/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/flutter_rust_bridge_codegen-1.37.1/src/parser/ty.rs:142:32
stack backtrace:
   0:        0x10a497384 - std::backtrace_rs::backtrace::libunwind::trace::hee82a97921985ffc
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10a497384 - std::backtrace_rs::backtrace::trace_unsynchronized::hd2f3f197f68d4196
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10a497384 - std::sys_common::backtrace::_print_fmt::hef7f7070435a43cf
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x10a497384 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6ab6a4b798848da1
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x10a4b673b - core::fmt::write::h3cfeb2e4a41b5943
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
   5:        0x10a493738 - std::io::Write::write_fmt::h207c490a0e714424
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
   6:        0x10a498e4d - std::sys_common::backtrace::_print::h2c39637d8acc9668
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x10a498e4d - std::sys_common::backtrace::print::ha24f17eeb0536253
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x10a498e4d - std::panicking::default_hook::{{closure}}::h2dad0ca14a5f6fb3
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
   9:        0x10a498b31 - std::panicking::default_hook::he28ca1b524a71648
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:314:9
  10:        0x10a4993ce - std::panicking::rust_panic_with_hook::hc50fd680dab3e13f
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:698:17
  11:        0x10a4992c3 - std::panicking::begin_panic_handler::{{closure}}::h73da24fc37eba97b
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:588:13
  12:        0x10a497807 - std::sys_common::backtrace::__rust_end_short_backtrace::hff104f8fa804dc90
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
  13:        0x10a498f9a - rust_begin_unwind
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
  14:        0x10a4d4613 - core::panicking::panic_fmt::hf5e95a7953f70bca
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
  15:        0x10a0ed297 - lib_flutter_rust_bridge_codegen::parser::ty::TypeParser::parse_type::hafc593043beac4c0
  16:        0x10a05a726 - lib_flutter_rust_bridge_codegen::parser::Parser::parse_function::h4bf526d0c7ee842f
  17:        0x10a036580 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h5e0fbe58b23990c7
  18:        0x10a059bb1 - lib_flutter_rust_bridge_codegen::parser::parse::h0e78003c3f2504a8
  19:        0x10a04a264 - lib_flutter_rust_bridge_codegen::config::Opts::get_ir_file::h024d98da0573bb62
  20:        0x10a0d5190 - lib_flutter_rust_bridge_codegen::utils::get_symbols_if_no_duplicates::h59cf6fc050ceef3b
  21:        0x10a01755c - flutter_rust_bridge_codegen::main::h5deb4a1e7da4fd7f
  22:        0x10a018a86 - std::sys_common::backtrace::__rust_begin_short_backtrace::h68bd5760e096a65e
  23:        0x10a015291 - std::rt::lang_start::{{closure}}::hb98f135e5b2aec3b
  24:        0x10a48ddde - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h95efaa71c50a181d
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:280:13
  25:        0x10a48ddde - std::panicking::try::do_call::h9e262f45d279a668
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  26:        0x10a48ddde - std::panicking::try::hcfa2ff7c3ef05946
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  27:        0x10a48ddde - std::panic::catch_unwind::h6e5f05af2d5ed125
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  28:        0x10a48ddde - std::rt::lang_start_internal::{{closure}}::ha6428ebd453bcc4b
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:48
  29:        0x10a48ddde - std::panicking::try::do_call::h1897e56454854402
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  30:        0x10a48ddde - std::panicking::try::h18317894fcdd1ee4
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  31:        0x10a48ddde - std::panic::catch_unwind::h953eb8e106926f6b
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  32:        0x10a48ddde - std::rt::lang_start_internal::h3a2ed64a839cce39
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:20
  33:        0x10a017899 - _main

flutter_rust_bridge/frb_example/pure_dart git:master*
❯

flutter_rust_bridge/frb_example/pure_dart git:master*
❯ ls'
quote>

flutter_rust_bridge/frb_example/pure_dart git:master*
❯ ls
 .
├──  dart
├──  README.md
└──  rust

flutter_rust_bridge/frb_example/pure_dart git:master*
❯ flutter_rust_bridge_codegen --rust-input rust/src/api.rs --dart-output dart/lib/bridge_generated.dart --dart-format-line-length 120
thread 'main' panicked at 'parse_type failed for ty=N', /Users/tenx/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/flutter_rust_bridge_codegen-1.37.1/src/parser/ty.rs:142:32
stack backtrace:
   0:        0x10f6c6384 - std::backtrace_rs::backtrace::libunwind::trace::hee82a97921985ffc
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10f6c6384 - std::backtrace_rs::backtrace::trace_unsynchronized::hd2f3f197f68d4196
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10f6c6384 - std::sys_common::backtrace::_print_fmt::hef7f7070435a43cf
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x10f6c6384 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6ab6a4b798848da1
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x10f6e573b - core::fmt::write::h3cfeb2e4a41b5943
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
   5:        0x10f6c2738 - std::io::Write::write_fmt::h207c490a0e714424
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
   6:        0x10f6c7e4d - std::sys_common::backtrace::_print::h2c39637d8acc9668
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x10f6c7e4d - std::sys_common::backtrace::print::ha24f17eeb0536253
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x10f6c7e4d - std::panicking::default_hook::{{closure}}::h2dad0ca14a5f6fb3
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
   9:        0x10f6c7b31 - std::panicking::default_hook::he28ca1b524a71648
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:314:9
  10:        0x10f6c83ce - std::panicking::rust_panic_with_hook::hc50fd680dab3e13f
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:698:17
  11:        0x10f6c82c3 - std::panicking::begin_panic_handler::{{closure}}::h73da24fc37eba97b
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:588:13
  12:        0x10f6c6807 - std::sys_common::backtrace::__rust_end_short_backtrace::hff104f8fa804dc90
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
  13:        0x10f6c7f9a - rust_begin_unwind
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
  14:        0x10f703613 - core::panicking::panic_fmt::hf5e95a7953f70bca
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
  15:        0x10f31c297 - lib_flutter_rust_bridge_codegen::parser::ty::TypeParser::parse_type::hafc593043beac4c0
  16:        0x10f289726 - lib_flutter_rust_bridge_codegen::parser::Parser::parse_function::h4bf526d0c7ee842f
  17:        0x10f265580 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h5e0fbe58b23990c7
  18:        0x10f288bb1 - lib_flutter_rust_bridge_codegen::parser::parse::h0e78003c3f2504a8
  19:        0x10f279264 - lib_flutter_rust_bridge_codegen::config::Opts::get_ir_file::h024d98da0573bb62
  20:        0x10f304190 - lib_flutter_rust_bridge_codegen::utils::get_symbols_if_no_duplicates::h59cf6fc050ceef3b
  21:        0x10f24655c - flutter_rust_bridge_codegen::main::h5deb4a1e7da4fd7f
  22:        0x10f247a86 - std::sys_common::backtrace::__rust_begin_short_backtrace::h68bd5760e096a65e
  23:        0x10f244291 - std::rt::lang_start::{{closure}}::hb98f135e5b2aec3b
  24:        0x10f6bcdde - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h95efaa71c50a181d
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:280:13
  25:        0x10f6bcdde - std::panicking::try::do_call::h9e262f45d279a668
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  26:        0x10f6bcdde - std::panicking::try::hcfa2ff7c3ef05946
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  27:        0x10f6bcdde - std::panic::catch_unwind::h6e5f05af2d5ed125
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  28:        0x10f6bcdde - std::rt::lang_start_internal::{{closure}}::ha6428ebd453bcc4b
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:48
  29:        0x10f6bcdde - std::panicking::try::do_call::h1897e56454854402
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  30:        0x10f6bcdde - std::panicking::try::h18317894fcdd1ee4
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  31:        0x10f6bcdde - std::panic::catch_unwind::h953eb8e106926f6b
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  32:        0x10f6bcdde - std::rt::lang_start_internal::h3a2ed64a839cce39
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:20
  33:        0x10f246899 - _main

flutter_rust_bridge/frb_example/pure_dart git:master*
❯ ls
 .
├──  dart
├──  README.md
└──  rust

flutter_rust_bridge/frb_example/pure_dart git:master*
❯ flutter_rust_bridge_codegen --rust-input rust/src/api.rs --dart-output dart/lib/bridge_generated.dart --dart-format-line-length 120
thread 'main' panicked at 'parse_type failed for ty=N', /Users/tenx/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/flutter_rust_bridge_codegen-1.37.1/src/parser/ty.rs:142:32
stack backtrace:
   0:        0x100a78384 - std::backtrace_rs::backtrace::libunwind::trace::hee82a97921985ffc
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x100a78384 - std::backtrace_rs::backtrace::trace_unsynchronized::hd2f3f197f68d4196
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x100a78384 - std::sys_common::backtrace::_print_fmt::hef7f7070435a43cf
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x100a78384 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6ab6a4b798848da1
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x100a9773b - core::fmt::write::h3cfeb2e4a41b5943
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
   5:        0x100a74738 - std::io::Write::write_fmt::h207c490a0e714424
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
   6:        0x100a79e4d - std::sys_common::backtrace::_print::h2c39637d8acc9668
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x100a79e4d - std::sys_common::backtrace::print::ha24f17eeb0536253
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x100a79e4d - std::panicking::default_hook::{{closure}}::h2dad0ca14a5f6fb3
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
   9:        0x100a79b31 - std::panicking::default_hook::he28ca1b524a71648
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:314:9
  10:        0x100a7a3ce - std::panicking::rust_panic_with_hook::hc50fd680dab3e13f
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:698:17
  11:        0x100a7a2c3 - std::panicking::begin_panic_handler::{{closure}}::h73da24fc37eba97b
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:588:13
  12:        0x100a78807 - std::sys_common::backtrace::__rust_end_short_backtrace::hff104f8fa804dc90
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
  13:        0x100a79f9a - rust_begin_unwind
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
  14:        0x100ab5613 - core::panicking::panic_fmt::hf5e95a7953f70bca
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
  15:        0x1006ce297 - lib_flutter_rust_bridge_codegen::parser::ty::TypeParser::parse_type::hafc593043beac4c0
  16:        0x10063b726 - lib_flutter_rust_bridge_codegen::parser::Parser::parse_function::h4bf526d0c7ee842f
  17:        0x100617580 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h5e0fbe58b23990c7
  18:        0x10063abb1 - lib_flutter_rust_bridge_codegen::parser::parse::h0e78003c3f2504a8
  19:        0x10062b264 - lib_flutter_rust_bridge_codegen::config::Opts::get_ir_file::h024d98da0573bb62
  20:        0x1006b6190 - lib_flutter_rust_bridge_codegen::utils::get_symbols_if_no_duplicates::h59cf6fc050ceef3b
  21:        0x1005f855c - flutter_rust_bridge_codegen::main::h5deb4a1e7da4fd7f
  22:        0x1005f9a86 - std::sys_common::backtrace::__rust_begin_short_backtrace::h68bd5760e096a65e
  23:        0x1005f6291 - std::rt::lang_start::{{closure}}::hb98f135e5b2aec3b
  24:        0x100a6edde - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h95efaa71c50a181d
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:280:13
  25:        0x100a6edde - std::panicking::try::do_call::h9e262f45d279a668
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  26:        0x100a6edde - std::panicking::try::hcfa2ff7c3ef05946
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  27:        0x100a6edde - std::panic::catch_unwind::h6e5f05af2d5ed125
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  28:        0x100a6edde - std::rt::lang_start_internal::{{closure}}::ha6428ebd453bcc4b
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:48
  29:        0x100a6edde - std::panicking::try::do_call::h1897e56454854402
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  30:        0x100a6edde - std::panicking::try::h18317894fcdd1ee4
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  31:        0x100a6edde - std::panic::catch_unwind::h953eb8e106926f6b
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  32:        0x100a6edde - std::rt::lang_start_internal::h3a2ed64a839cce39
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:20
  33:        0x1005f8899 - _main
```

**Comment by TENX-S** [comment]
#561

**Comment by TENX-S** [comment]
Is there a plan to publish a new version, may be 1.37.2?

**Comment by fzyzcjy** [comment]
You are right, I forget it
