### ISSUE TITLE
wasm target - Error: Not found: 'dart:ffi'

### ISSUE THREAD

**Issue by thomas725** [fzyzcjy/flutter_rust_bridge#761]
Hi there!

I'm trying to get [my flutter-playground](https://gitlab.com/thomas351/flutter-playground/) to work with the wasm target, but fail like this:

```
$ dart run flutter_rust_bridge:serve
> which wasm-pack
/usr/bin/wasm-pack
> cargo read-manifest
> wasm-pack build -t no-modules -d /home/thomas/Development/git/flutter-playground/web/pkg --no-typescript --out-name native --dev native -- -Z build-std=std,panic_abort
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling native v0.1.0 (/home/thomas/Development/git/flutter-playground/native)
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
[WARN]: :-) origin crate has no README
[INFO]: Installing wasm-bindgen...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: :-) Done in 0.71s
[INFO]: :-) Your wasm pkg is ready to publish at /home/thomas/Development/git/flutter-playground/web/pkg.
> flutter build web --profile

💪 Building with sound null safety 💪
Compiling lib/main.dart for the Web...                          
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
lib/ffi.dart:4:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
lib/bridge_generated.dart:11:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi' as ffi;
       ^
lib/bridge_generated.dart:202:18:
Error: Type 'ffi.DynamicLibrary' not found.
  NativePlatform(ffi.DynamicLibrary dylib) : super(NativeWire(dylib));
                 ^^^^^^^^^^^^^^^^^^

...

lib/bridge_generated.dart:227:11:
Error: 'Pointer' isn't a type.
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          ^^^^^^^
Error: Compilation failed.

Exception: Failed to compile application for the Web.

  Command: flutter build web --profile
#0      system (file:///home/thomas/.pub-cache/hosted/pub.dartlang.org/flutter_rust_bridge-1.48.1/bin/serve.dart:75:5)
<asynchronous suspension>
#1      build (file:///home/thomas/.pub-cache/hosted/pub.dartlang.org/flutter_rust_bridge-1.48.1/bin/serve.dart:273:5)
<asynchronous suspension>
#2      main (file:///home/thomas/.pub-cache/hosted/pub.dartlang.org/flutter_rust_bridge-1.48.1/bin/serve.dart:215:5)
<asynchronous suspension>
```

I do have `ffi: ^2.0.1` in the `dependencies` section of my `pubspec.yaml` file. Can somebody help me debug this problem?

Running `flutter run -d linux` works fine.
The android target also works, but only after switching back to `rustup default stable`.

I did follow the [Web Setup docs page](http://cjycode.com/flutter_rust_bridge/template/setup_web.html):
```
rustup toolchain install nightly
rustup +nightly component add rust-src
rustup +nightly target add wasm32-unknown-unknown
sudo pacman -S wasm-pack
rustup default nightly
```

**Comment by fzyzcjy** [comment]
There is no dart:ffi for web indeed...

**Comment by Desdaemon** [comment]
I think I forgot to mention that you will also need to run codegen with the `--wasm` flag as well. I'll update the book soon.

**Comment by thomas725** [comment]
hmmm, but if I move it over into the `dev_dependencies` section, running `just` to refresh the bridge code gives:
```
[2022-10-02T06:29:59Z ERROR flutter_rust_bridge_codegen] fatal: please add ffi to your dependencies. (version >=2.0.1, <3.0.0)
error: Recipe `gen` failed on line 18 with exit code 1
```

**Comment by thomas725** [comment]
I think I need even more instructions ^^
```
error: The following required arguments were not provided:
    --dart-decl-output <DART_DECL_OUTPUT>
```
What is dart-decl, and what target should I give?

**Comment by Desdaemon** [comment]
@thomas725 It's the platform-agnostic portion of the bridge file, i.e. it only depends on `dart:core` and some other modules. The convention I use in examples is to place it next to the bridge file -- you can name it any valid Dart module file name.

**Comment by thomas725** [comment]
Ah, I see you modified [the template](https://github.com/Desdaemon/flutter_rust_bridge_template) 24 days ago for the wasm target. I'll try to study and understand what you did there.
