### ISSUE TITLE
[Bug] pure_dart example fails to lookup symbol

### ISSUE THREAD

**Issue by jwinarske** [fzyzcjy/flutter_rust_bridge#772]
### Describe the bug

Attempting to run pure_dart example on M1 Mac results in:

```
% ./main.exe ../../../target/debug//libflutter_rust_bridge_example.dylib
flutter_rust_bridge example program start (dylibPath=../../../target/debug//libflutter_rust_bridge_example.dylib)
construct api
Unhandled exception:
Invalid argument(s): Failed to lookup symbol 'store_dart_post_cobject': dlsym(RTLD_DEFAULT, store_dart_post_cobject): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:34)
#1      FlutterRustBridgeExampleSingleBlockTestWire._store_dart_post_cobjectPtr (package:flutter_rust_bridge_example/bridge_generated.io.dart:945)
#2      FlutterRustBridgeExampleSingleBlockTestWire._store_dart_post_cobject (package:flutter_rust_bridge_example/bridge_generated.io.dart)
#3      FlutterRustBridgeExampleSingleBlockTestWire.store_dart_post_cobject (package:flutter_rust_bridge_example/bridge_generated.io.dart)
#4      StoreDartPostCObjectExt.storeDartPostCObject (package:flutter_rust_bridge/src/ffi/io.dart:16)
#5      FlutterRustBridgeBase._setUpRustToDartComm (package:flutter_rust_bridge/src/basic.dart:39)
#6      new FlutterRustBridgeBase (package:flutter_rust_bridge/src/basic.dart:22)
#7      new FlutterRustBridgeExampleSingleBlockTestPlatform (package:flutter_rust_bridge_example/bridge_generated.io.dart:18)
#8      new FlutterRustBridgeExampleSingleBlockTestImpl (package:flutter_rust_bridge_example/bridge_generated.dart:16)
#9      initializeExternalLibrary (package:flutter_rust_bridge_example/ffi.io.dart:8)
#10     main (package:flutter_rust_bridge_example/main.dart:22)
#11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

The symbol is there, it's just prefixed with `_`:
```
% nm -gU ../../../target/debug//libflutter_rust_bridge_example.dylib |grep store_dart_post_cobject
000000000013f1bc T _store_dart_post_cobject
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
NA
```

**Comment by fzyzcjy** [comment]
Is it the same problem as https://github.com/fzyzcjy/flutter_rust_bridge/issues/754?

**Comment by jwinarske** [comment]
different

**Comment by jwinarske** [comment]
I'm not trying to run codegen here.  Just using as-is.

**Comment by fzyzcjy** [comment]
All right. Could you please try the debug suggestions there?

Btw, cc @Roms1383 - here is another case of M1 mac + store_dart_post_cobject error

**Comment by jwinarske** [comment]
My bad.  It is a duplicate of #754, so closing.

This does address the problem:

```
If I replace :

DynamicLibrary.executable() with DynamicLibrary.open(path) (like in non-IOS/MacOS) in frb_example/pure_dart/dart/lib/ffi.io.dart it works.
```

So it looks like that version of ffigen is not detecting the platform correctly.  Perhaps a roll of ffigen will address it.

**Comment by buf1024** [comment]
change file ffi.io.dart to should be solved problem:
```
return FlutterRustBridgeExampleSingleBlockTestImpl(
    !(Platform.isMacOS || Platform.isIOS) ? DynamicLibrary.executable() : DynamicLibrary.open(path),
  );
```
it seems the origin logic is incorrect.
