### ISSUE TITLE
[Bug] frb_codegen memory sanitizer error

### ISSUE THREAD

**Issue by jwinarske** [fzyzcjy/flutter_rust_bridge#776]
### Describe the bug

`RUSTFLAGS="-Z sanitizer=memory" cargo run`

```
  ==632210==WARNING: MemorySanitizer: use-of-uninitialized-value
      #0 0x55f541934d13 in core::option::Option$LT$T$GT$::is_some::h6504ac36d17313c0 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/core/src/option.rs:554:9
      #1 0x55f541939a96 in build_script_build::is_env_set::h8e7cbe63f4b7a2b6 /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.5.0/build.rs:81:5
      #2 0x55f541938717 in build_script_build::enable_simd_optimizations::h925c3a3c32cf8eef /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.5.0/build.rs:18:8
      #3 0x55f5419386e5 in build_script_build::main::h9eb6f0894224e0bd /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.5.0/build.rs:4:5
      #4 0x55f541940c5c in core::ops::function::FnOnce::call_once::hb927535bb1e13e02 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/core/src/ops/function.rs:251:5
      #5 0x55f54193d9e2 in std::sys_common::backtrace::__rust_begin_short_backtrace::he72e235dbb51202a /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/sys_common/backtrace.rs:122:18
      #6 0x55f541934121 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h1660c9fd80123a4e /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/rt.rs:166:18
      #7 0x55f54195609a in core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$F$GT$::call_once::hcf0f452e35b42714 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/core/src/ops/function.rs:286:13
      #8 0x55f54195609a in std::panicking::try::do_call::h9076463b86fc98c2 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/panicking.rs:464:40
      #9 0x55f54195609a in std::panicking::try::h59a38c38fab81132 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/panicking.rs:428:19
      #10 0x55f54195609a in std::panic::catch_unwind::h024c7f29e5fae637 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/panic.rs:137:14
      #11 0x55f54195609a in std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::h1bc9c4aefbf9b583 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/rt.rs:148:48
      #12 0x55f54195609a in std::panicking::try::do_call::hf630db2c23823f3c /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/panicking.rs:464:40
      #13 0x55f54195609a in std::panicking::try::h5c6c892f05382366 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/panicking.rs:428:19
      #14 0x55f54195609a in std::panic::catch_unwind::h893ebad4c00d9e60 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/panic.rs:137:14
      #15 0x55f54195609a in std::rt::lang_start_internal::h2fa3ed5bcd048bb3 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/rt.rs:148:20
      #16 0x55f541933ff5 in std::rt::lang_start::h8e4bd8244ea16f8c /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/rt.rs:165:17
      #17 0x55f541939f89 in main (/b/flutter_rust_bridge/target/debug/build/memchr-359aa0212e42dbd4/build-script-build+0x82f89) (BuildId: ce6f23565ee85b7326f5af230312587aa2bf2271)
      #18 0x7f85c99d2b74 in __libc_start_main (/lib64/libc.so.6+0x27b74) (BuildId: 08df60634339b221bb854d4e10b7278cafde70c4)
      #19 0x55f5418c60dd in _start (/b/flutter_rust_bridge/target/debug/build/memchr-359aa0212e42dbd4/build-script-build+0xf0dd) (BuildId: ce6f23565ee85b7326f5af230312587aa2bf2271)

  SUMMARY: MemorySanitizer: use-of-uninitialized-value /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/core/src/option.rs:554:9 in core::option::Option$LT$T$GT$::is_some::h6504ac36d17313c0
  Exiting
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
NA
```

### To Reproduce

`RUSTFLAGS="-Z sanitizer=memory" cargo run`

### Expected behavior

free of failures

### OS

Linux

### Version of `flutter_rust_bridge_codegen`

master tip of tree

**Comment by jwinarske** [comment]
Also

Input
```
pushd frb_codegen
RUST_LOG=debug RUSTFLAGS="-Z sanitizer=memory" cargo run --verbose -- --package flutter_rust_bridge_codegen --bin flutter_rust_bridge_codegen --features "chrono,uuid" --  --rust-input ../frb_example/pure_dart/rust/src/api.rs --dart-output ../frb_example/pure_dart/dart/lib/bridge_generated.dart --dart-decl-output ../frb_example/pure_dart/dart/lib/bridge_definitions.dart --dart-format-line-length 120 --wasm
```

Output Tail
```
  ==634305==WARNING: MemorySanitizer: use-of-uninitialized-value
      #0 0x55fd15667f44 in core::result::Result$LT$T$C$E$GT$::ok::h533a48bd58cf20ea /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/core/src/result.rs:647:9
      #1 0x55fd156674ef in build_script_build::rustc_target::h8a28dd8402b19409 /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.17/build.rs:45:5
      #2 0x55fd15666b2b in build_script_build::main::h097f8b0c393ca3d9 /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.17/build.rs:8:24
      #3 0x55fd15668acc in core::ops::function::FnOnce::call_once::h56774b0257e87073 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/core/src/ops/function.rs:251:5
      #4 0x55fd156690e2 in std::sys_common::backtrace::__rust_begin_short_backtrace::h3f51c0f387eb6885 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/sys_common/backtrace.rs:122:18
      #5 0x55fd1566b591 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hfcc3b30cf857dc14 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/rt.rs:166:18
      #6 0x55fd1567e6ca in core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$F$GT$::call_once::hcf0f452e35b42714 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/core/src/ops/function.rs:286:13
      #7 0x55fd1567e6ca in std::panicking::try::do_call::h9076463b86fc98c2 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/panicking.rs:464:40
      #8 0x55fd1567e6ca in std::panicking::try::h59a38c38fab81132 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/panicking.rs:428:19
      #9 0x55fd1567e6ca in std::panic::catch_unwind::h024c7f29e5fae637 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/panic.rs:137:14
      #10 0x55fd1567e6ca in std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::h1bc9c4aefbf9b583 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/rt.rs:148:48
      #11 0x55fd1567e6ca in std::panicking::try::do_call::hf630db2c23823f3c /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/panicking.rs:464:40
      #12 0x55fd1567e6ca in std::panicking::try::h5c6c892f05382366 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/panicking.rs:428:19
      #13 0x55fd1567e6ca in std::panic::catch_unwind::h893ebad4c00d9e60 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/panic.rs:137:14
      #14 0x55fd1567e6ca in std::rt::lang_start_internal::h2fa3ed5bcd048bb3 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/rt.rs:148:20
      #15 0x55fd1566b465 in std::rt::lang_start::h8f30ee362d283853 /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/std/src/rt.rs:165:17
      #16 0x55fd15667559 in main (/b/flutter_rust_bridge/target/debug/build/log-1f11837a51d2b725/build-script-build+0x75559) (BuildId: b76b699bf73f2dbc00524070af6e3fef747d2add)
      #17 0x7fd0a8fdab74 in __libc_start_main (/lib64/libc.so.6+0x27b74) (BuildId: 08df60634339b221bb854d4e10b7278cafde70c4)
      #18 0x55fd156010dd in _start (/b/flutter_rust_bridge/target/debug/build/log-1f11837a51d2b725/build-script-build+0xf0dd) (BuildId: b76b699bf73f2dbc00524070af6e3fef747d2add)

  SUMMARY: MemorySanitizer: use-of-uninitialized-value /rustc/8796e7a9cfd4c5c4f1de15ec1c53994ddf288665/library/core/src/result.rs:647:9 in core::result::Result$LT$T$C$E$GT$::ok::h533a48bd58cf20ea
  Exiting
```

**Comment by fzyzcjy** [comment]
Nice catch! So we have two TODOs now:

- [ ] Add memory sanitizer to github ci
- [ ] fix the bug

Looking forward to PR :)
