### ISSUE TITLE
[Build] with_flutter example: bridge not working for iOS and Android, but works for macOS.

### ISSUE THREAD

**Issue by endonym** [fzyzcjy/flutter_rust_bridge#816]
### Describe the bug

Note: this might just be me being a noob but thought I'd report in case someone else is running into the same problem.

__Summary__
Running Apple Silicon
- iOS Build Fails
- Android runs but the bridge fails with errors
- macOS builds and runs successfully

__Android__
```

W/FlutterActivityAndFragmentDelegate(17911): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Debug service listening on ws://127.0.0.1:56228/4M1rEzUniWc=/ws
Syncing files to device sdk gphone64 arm64...
E/flutter (17911): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libflutter_rust_bridge_example.so': dlopen failed: library "libflutter_rust_bridge_example.so" not found
E/flutter (17911): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
E/flutter (17911): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
E/flutter (17911): #2      dylib (package:flutter_rust_bridge_example/ffi.io.dart:12:26)
E/flutter (17911): #3      dylib (package:flutter_rust_bridge_example/ffi.io.dart)
E/flutter (17911): #4      api (package:flutter_rust_bridge_example/ffi.io.dart:13:47)
E/flutter (17911): #5      api (package:flutter_rust_bridge_example/ffi.io.dart)
E/flutter (17911): #6      _MyAppState._callExampleFfiTwo (package:flutter_rust_bridge_example/main.dart:47:32)
E/flutter (17911): #7      _MyAppState.initState (package:flutter_rust_bridge_example/main.dart:31:5)
E/flutter (17911): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015:57)
E/flutter (17911): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
E/flutter (17911): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
E/flutter (17911): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
E/flutter (17911): #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1195:16)
E/flutter (17911): #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1164:5)
E/flutter (17911): #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1111:18)
E/flutter (17911): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2605:19)
E/flutter (17911): #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1110:13)
E/flutter (17911): #17     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:945:7)
E/flutter (17911): #18     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:925:7)
E/flutter (17911): #19     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (17911): #20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (17911): #21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (17911): #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

__iOS__
```
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        974ms
Xcode build done.                                            4.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/_3/tjdsqfln7gn1s79hk2bgfx240000gn/T/flutter_tools.m2mmbN/flutter_ios_build_temp_dirjlBG9w/temporary_xcresult_bundle

    ld: library not found for -lflutter_rust_bridge_example
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Building targets in dependency order
    warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on
    dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on
    dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')

    Result bundle written to path:
    	/var/folders/_3/tjdsqfln7gn1s79hk2bgfx240000gn/T/flutter_tools.m2mmbN/flutter_ios_build_temp_dirjlBG9w/temporary_xcresult_bundle


Error (Xcode): Library not found for -lflutter_rust_bridge_example


Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
[2022-11-02T10:48:35Z DEBUG lib_flutter_rust_bridge_codegen::commands] execute ffigen c_path=/var/folders/_3/tjdsqfln7gn1s79hk2bgfx240000gn/T/.tmp4iiPPi.h dart_path=/var/folders/_3/tjdsqfln7gn1s79hk2bgfx240000gn/T/.tmp5Xtcuy llvm_path=["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/msys64/mingw64"]
[2022-11-02T10:48:35Z DEBUG lib_flutter_rust_bridge_codegen::commands] ffigen config: 
            output: '/var/folders/_3/tjdsqfln7gn1s79hk2bgfx240000gn/T/.tmp5Xtcuy'
            name: 'FlutterRustBridgeExampleWire'
            description: 'generated by flutter_rust_bridge'
            headers:
              entry-points:
                - '/var/folders/_3/tjdsqfln7gn1s79hk2bgfx240000gn/T/.tmp4iiPPi.h'
              include-directives:
                - '/var/folders/_3/tjdsqfln7gn1s79hk2bgfx240000gn/T/.tmp4iiPPi.h'
            comments: false
            preamble: |
              // ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
            
            llvm-path:
               - '/opt/homebrew/opt/llvm'
               - '/usr/local/opt/llvm'
               - '/usr/lib/llvm-9'
               - '/usr/lib/llvm-10'
               - '/usr/lib/llvm-11'
               - '/usr/lib/llvm-12'
               - '/usr/lib/llvm-13'
               - '/usr/lib/llvm-14'
               - '/usr/lib/'
               - '/usr/lib64/'
               - 'C:/Program Files/llvm'
               - 'C:/msys64/mingw64'
    
[2022-11-02T10:48:35Z DEBUG lib_flutter_rust_bridge_codegen::commands] ffigen config_file: NamedTempFile("/var/folders/_3/tjdsqfln7gn1s79hk2bgfx240000gn/T/.tmpIsyVsI")
[2022-11-02T10:48:35Z DEBUG lib_flutter_rust_bridge_codegen::tools] Guessing toolchain the runner is run into
[2022-11-02T10:48:35Z DEBUG lib_flutter_rust_bridge_codegen::commands] execute command: bin=sh args="-c \"flutter\" \"pub\" \"run\" \"ffigen\" \"--config\" \"/var/folders/_3/tjdsqfln7gn1s79hk2bgfx240000gn/T/.tmpIsyVsI\"" current_dir=Some("~/IdeaProjects/scratch/flutter_rust_bridge/frb_example/with_flutter") cmd="sh" "-c" "\"flutter\" \"pub\" \"run\" \"ffigen\" \"--config\" \"/var/folders/_3/tjdsqfln7gn1s79hk2bgfx240000gn/T/.tmpIsyVsI\""
Running in Directory: '~/IdeaProjects/scratch/flutter_rust_bridge/frb_example/with_flutter'
Input Headers: [/var/folders/_3/tjdsqfln7gn1s79hk2bgfx240000gn/T/.tmp4iiPPi.h]
[SEVERE] : Header /var/folders/_3/tjdsqfln7gn1s79hk2bgfx240000gn/T/.tmp4iiPPi.h: Total errors/warnings: 180.
[SEVERE] :     /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:134:25: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [Nullability Issue]
```

### Generated binding code

```shell
with_flutter
```

### OS

MacOS 12.6

### Version of `flutter_rust_bridge_codegen`

1.49.0

### Flutter info

```shell
rust % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.6, on macOS 12.6 21G115 darwin-arm, locale en-GB)
    • Flutter version 3.3.6 on channel stable at ~/IdeaProjects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (8 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at ~/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/Adobe Dreamweaver 2021/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.67.1)
    • VS Code at ~/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 14 Pro Max (mobile)  • 48F89E7F-1D83-4909-8137-F3A6425D7305 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Version of `clang++`

Apple clang version 14.0.0 (clang-1400.0.29.102)

### Version of `ffigen`

^6.0.1

**Comment by fzyzcjy** [comment]
Looks like the dynamic/static lib is not loaded properly... Have you followed the book?

also /cc @Desdaemon who wrote the integration chapters

**Comment by endonym** [comment]
Hi @fzyzcjy and thanks for the quick response.  Super helpful. 

I am following [this tutorial you published](https://cjycode.com/flutter_rust_bridge/tutorial_with_flutter.html)

Is there a different book?  Or are you referring to rust's "the book" ... excuse my ignorance, I'm new to this stack.

**Comment by fzyzcjy** [comment]
https://cjycode.com/flutter_rust_bridge/template.html

chapter 4, 5 etc

**Comment by endonym** [comment]
There was another change in that macOS failed to run too.

```
Launching lib/main.dart on macOS in debug mode...
Building macOS application...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-0008292634A1801E }
{ platform:macOS, arch:x86_64, id:00006000-0008292634A1801E } // **<< this obviously isn't good, but it selected the right one... Just flagging in case this is the root cause.** 
clang: error: no such file or directory: 'native.dylib'
Command Ld failed with a nonzero exit code
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **

Exception: Build process failed

```

**Comment by endonym** [comment]
This afternoon I tried 'the intermediate' [Chapter 5](https://cjycode.com/flutter_rust_bridge/integrate.html) manually (and not using the `flutter_rust_bridge` brick).  I carefully followed the instruction and I will start with what I think is the central issue:  

Focusing on building for iOS __using Xcode 14.0.1__

___

A. When running 

```
flutter_rust_bridge_codegen \
    -r wallet_base/src/api.rs \
    -d lib/bridge_generated.dart \
    -c ios/Runner/bridge_generated.h \
    -c macos/Runner/bridge_generated.h
```

I get the error stream (180 lines):

```
[SEVERE] :     /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:134:25: warning
...
```

This is the common error with the `flutter_rust_bridge_template` and `with_flutter`, so it seems logical that it's the root cause. 

___ 

B. There was a point of confusion while I followed the instruction that I resolved, but I will note here as it may potentially help someone else.

The [usage](https://gitlab.com/kornelski/cargo-xcode#usage) instructions for `cargo xcode` talk of a parent/child project relation that doesn't naturally exist after following the previous instructions. It's later resolved by the Chapter 5 instructions.  I found that just having `cargo xcode` installed was enough, to not need to follow the "Usage" instruction.  What you need to do is very well covered in 5.4.1

___

C. The below error message was output with a boiler plate project created with Android Studio when using `flutter_rust_bridge_codegen`

`fatal: please update version of ffigen in your dev_dependencies. (version >=6.0.1, <7.0.0)`

The fix was obvious - but it might be useful to update installation instructions:
```
dev_dependencies:
  ffigen: ^6.0.1
```

___

D. Section 5.4.4 didn't work as I expected. 

Adding the below lines to `AppDelegate.swift` 

```
  let dummy = dummy_method_to_enforce_bundling()
  print(dummy)

```

resulted in an error on `flutter run`

```
Swift Compiler Error (Xcode): Cannot find 'dummy_method_to_enforce_bundling' in scope
~/StudioProjects/test_flutter/ios/Runner/AppDelegate.swift:9:20
```

I took out the `dummy_method_...` and `flutter run` failed with:

```
   Command RuleScriptExecution failed with a nonzero exit code
    note: Building targets in dependency order
    warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning,
    either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the
    script phase. (in target 'Runner' from project 'Runner')
    warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this
    warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency
    analysis" in the script phase. (in target 'Runner' from project 'Runner')

    Result bundle written to path:
      /var/folders/_3/tjdsqfln7gn1s79hk2bgfx240000gn/T/flutter_tools.Mdbqgz/flutter_ios_build_temp_dirJVmgZ6/temporary_xcresult_bundle

Uncategorized (Xcode): Command RuleScriptExecution failed with a nonzero exit code
```

There were `warnings` about a name collision with `$crate` that I'm happy to detail, but I suspect that's a known issue.

___

I think if there's a solution for (A), the problems will be resolved.  I am going to give a fresh project a run through tomorrow, both from `flutter_rust_bridge_template` and from Chapter 5 of the book.

This seems like a really great stack and I'm looking forward to getting it up and running ... once again, thanks for your quick responses today. 

All the best.

**Comment by fzyzcjy** [comment]
You are welcome, it looks quite weird and I do not have much bandwidth about such problems (env setup instead of real feature/bugs). Starting from a fresh project in flutter_rust_bridge_template looks like a feasible idea.

**Comment by endonym** [comment]
Quick question when you have a second.  Is there supposed to be a file generated called `lnative_static` in the `native` folder of `flutter_rust_bridge_template`? 

I found [this post](https://kb.vmware.com/s/article/2970163) from an unrelated project and it looks like the same issue, albeit a different library.  This issue might be entirely Xcode related; however, when I look for the lnative_static file it's not present. 

My understanding of `flutter_rust_bridge` is that I don't need to run `cargo build` in the `native` folder.  Please correct me if that's a false assumption. 

I'm just doing a fresh install of an x86 MacOS .. is it possible to (easily) give me a set of version dependencies that works on your machine?

**Comment by fzyzcjy** [comment]
> generated called lnative_static

I guess no. `-lsomething` means `-l` + `something`, not `-` + `lsomething`

> My understanding of flutter_rust_bridge is that I don't need to run cargo build in the native folder. Please correct me if that's a false assumption

It depends on how you setup it. The bridge itself is nothing but a code generator that generates some code that otherwise you need to write manually, so it is not aware of how the build system is setup.
