### ISSUE TITLE
[Bug] Cannot return `Self` from associated function

### ISSUE THREAD

**Issue by holly-hacker** [fzyzcjy/flutter_rust_bridge#838]
### Describe the bug

Assuming the following rust code
```rs
pub struct MyData(pub Vec<u8>);

impl MyData {
    pub fn create_new() -> Self {
        Self(vec![])
    }
}
```

This fails with the following message 
```
thread 'main' panicked at 'Failed to parse function output type `Self`', frb_codegen\src\parser\mod.rs:161:25
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
D:\Projects\Rust\darting_app\native> just gen
flutter pub get
Running "flutter pub get" in darting_app...                        513ms
flutter_rust_bridge_codegen --rust-input native/src/api.rs --dart-output lib/bridge_generated.dart --c-output ios/Runner/bridge_generated.h --c-output macos/Runner/bridge_generated.h --dart-decl-output lib/bridge_definitions.dart --wasm
[2022-11-10T12:47:37Z DEBUG flutter_rust_bridge_codegen] configs=[Opts { rust_input_path: "D:\\Projects\\Rust\\darting_app\\native/src/api.rs", dart_output_path: "D:\\Projects\\Rust\\darting_app\\lib/bridge_generated.dart", dart_decl_output_path: Some("D:\\Projects\\Rust\\darting_app\\lib/bridge_definitions.dart"), c_output_path: ["D:\\Projects\\Rust\\darting_app\\ios/Runner/bridge_generated.h", "D:\\Projects\\Rust\\darting_app\\macos/Runner/bridge_generated.h"], rust_crate_dir: "D:\\Projects\\Rust\\darting_app\\native", rust_output_path: "D:\\Projects\\Rust\\darting_app\\native/src\\bridge_generated.rs", class_name: "Native", dart_format_line_length: 80, skip_add_mod_to_lib: false, llvm_path: ["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/msys64/mingw64"], llvm_compiler_opts: "", manifest_path: "D:\\Projects\\Rust\\darting_app\\native\\Cargo.toml", dart_root: Some("D:\\Projects\\Rust\\darting_app"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: false, wasm_enabled: true, inline_rust: false }]
[2022-11-10T12:47:37Z DEBUG lib_flutter_rust_bridge_codegen::source_graph] Trying to parse "\\\\?\\D:\\Projects\\Rust\\darting_app\\native\\src\\api.rs"
[2022-11-10T12:47:37Z DEBUG lib_flutter_rust_bridge_codegen::source_graph] Trying to parse "\\\\?\\D:\\Projects\\Rust\\darting_app\\native\\src\\bridge_generated.rs"
[2022-11-10T12:47:37Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module web (tried \\?\D:\Projects\Rust\darting_app\native\src\web.rs, \\?\D:\Projects\Rust\darting_app\native\src\web\mod.rs, \\?\D:\Projects\Rust\darting_app\native\src\bridge_generated\web.rs, \\?\D:\Projects\Rust\darting_app\native\src\bridge_generated\web\mod.rs, )
[2022-11-10T12:47:37Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module io (tried \\?\D:\Projects\Rust\darting_app\native\src\io.rs, \\?\D:\Projects\Rust\darting_app\native\src\io\mod.rs, \\?\D:\Projects\Rust\darting_app\native\src\bridge_generated\io.rs, \\?\D:\Projects\Rust\darting_app\native\src\bridge_generated\io\mod.rs, )
[2022-11-10T12:47:37Z DEBUG lib_flutter_rust_bridge_codegen::source_graph] Trying to parse "\\\\?\\D:\\Projects\\Rust\\darting_app\\native\\src\\darts\\mod.rs"
[2022-11-10T12:47:37Z DEBUG lib_flutter_rust_bridge_codegen::source_graph] Trying to parse "\\\\?\\D:\\Projects\\Rust\\darting_app\\native\\src\\darts\\game\\mod.rs"
[2022-11-10T12:47:37Z DEBUG lib_flutter_rust_bridge_codegen::source_graph] Trying to parse "\\\\?\\D:\\Projects\\Rust\\darting_app\\native\\src\\darts\\game\\cricket.rs"
[2022-11-10T12:47:37Z DEBUG lib_flutter_rust_bridge_codegen::source_graph] Trying to parse "\\\\?\\D:\\Projects\\Rust\\darting_app\\native\\src\\darts\\player.rs"
[2022-11-10T12:47:37Z DEBUG lib_flutter_rust_bridge_codegen::parser] parse_function function name: Ident(create_new__static_method__MyData)
thread 'main' panicked at 'Failed to parse function output type `Self`', frb_codegen\src\parser\mod.rs:161:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: Recipe `gen` failed on line 13 with exit code 1
```

### OS

Windows 11 22000.1219 (21H2)

### Version of `flutter_rust_bridge_codegen`

1.49.1

### Version of `ffigen`

6.0.1

**Comment by fzyzcjy** [comment]
Does it work if replace Self with MyData?

This looks like sth that has not been implemented. Feel free to PR!

**Comment by holly-hacker** [comment]
Yes, if you specify the explicit type then works perfectly

**Comment by fzyzcjy** [comment]
looks like only need to modify parser a little bit. 

https://cjycode.com/flutter_rust_bridge/contributing/design.html explains a bit about overall struct

**Comment by holly-hacker** [comment]
Bump.
