### ISSUE TITLE
[Bug] Clang dynamic library not found

### ISSUE THREAD

**Issue by banool** [fzyzcjy/flutter_rust_bridge#850]
### Describe the bug

```
Invalid argument(s): Failed to load dynamic library '/opt/homebrew/opt/llvm/lib/libclang.dylib': dlopen(/opt/homebrew/opt/llvm/lib/libclang.dylib, 0x0001): Library not loaded: /opt/homebrew/opt/z3/lib/libz3.4.11.dylib
  Referenced from: <144BE538-A84A-30F9-B31A-E8275D654A1E> /opt/homebrew/Cellar/llvm/15.0.5/lib/libLLVM.dylib
  Reason: tried: '/opt/homebrew/opt/z3/lib/libz3.4.11.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/z3/lib/libz3.4.11.dylib' (no such file), '/opt/homebrew/opt/z3/lib/libz3.4.11.dylib' (no such file), '/usr/lib/libz3.4.11.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/z3/4.11.2/lib/libz3.4.11.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/z3/4.11.2/lib/libz3.4.11.dylib' (no such file), '/opt/homebrew/Cellar/z3/4.11.2/lib/libz3.4.11.dylib' (no such file), '/usr/lib/libz3.4.11.dylib' (no such file, not in dyld cache)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      initializeGlobals (package:ffigen/src/header_parser/data.dart:50:33)
#3      initParser (package:ffigen/src/header_parser/parser.dart:49:3)
#4      parse (package:ffigen/src/header_parser/parser.dart:23:3)
#5      main (package:ffigen/src/executables/ffigen.dart:55:19)
<asynchronous suspension>
```

See below repro for more info.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
https://gist.github.com/banool/bf8da2217eb719b54af8909282d803a7
```

### To Reproduce

Clone the repo:
```
https://github.com/banool/aclip
```

Run the codegen:
```
cd frontend
just
```

I have also tried the following:
```
LDFLAGS="-L/opt/homebrew/opt/llvm/lib" CPPFLAGS="-I/opt/homebrew/opt/llvm/include" just
```

Interestingly I see this problem:
```
/opt/homebrew/opt/llvm/bin/clang --version
dyld[48532]: Library not loaded: /opt/homebrew/opt/z3/lib/libz3.4.11.dylib
  Referenced from: <144BE538-A84A-30F9-B31A-E8275D654A1E> /opt/homebrew/Cellar/llvm/15.0.5/lib/libLLVM.dylib
  Reason: tried: '/opt/homebrew/opt/z3/lib/libz3.4.11.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/z3/lib/libz3.4.11.dylib' (no such file), '/opt/homebrew/opt/z3/lib/libz3.4.11.dylib' (no such file), '/usr/local/lib/libz3.4.11.dylib' (no such file), '/usr/lib/libz3.4.11.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/z3/4.11.2/lib/libz3.4.11.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/z3/4.11.2/lib/libz3.4.11.dylib' (no such file), '/opt/homebrew/Cellar/z3/4.11.2/lib/libz3.4.11.dylib' (no such file), '/usr/local/lib/libz3.4.11.dylib' (no such file), '/usr/lib/libz3.4.11.dylib' (no such file, not in dyld cache)
Abort trap: 6
```

**Comment by banool** [comment]
Disregard, I just found this: https://github.com/Homebrew/discussions/discussions/3920.

The solution was this:
```
brew reinstall z3
```
