### ISSUE TITLE
[Bug] Invalid argument(s): Failed to lookup symbol 'store_dart_post_cobject': undefined symbol: store_dart_post_cobject

### ISSUE THREAD

**Issue by ewgcat** [fzyzcjy/flutter_rust_bridge#977]
### Describe the bug
Invalid argument(s): Failed to lookup symbol 'store_dart_post_cobject': undefined symbol: store_dart_post_cobject
Here is the project repository:
 https://github.com/ewgcat/flutter_rust

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
Launching lib/main.dart on Android SDK built for arm64 in debug mode...
Running Gradle task 'assembleDebug'...
[2023-01-14T05:07:13Z INFO  cargo_ndk::cli] Using NDK at path: /Users/lishuaihua/Library/Android/sdk/ndk/25.1.8937393 (ANDROID_NDK_HOME)
[2023-01-14T05:07:13Z INFO  cargo_ndk::cli] NDK API level: 21
[2023-01-14T05:07:13Z INFO  cargo_ndk::cli] Building targets: arm64-v8a
[2023-01-14T05:07:13Z INFO  cargo_ndk::cli] Building arm64-v8a (aarch64-linux-android)
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
[2023-01-14T05:07:13Z INFO  cargo_ndk::cli] Copying libraries to ../android/app/src/main/jniLibs...
[2023-01-14T05:07:13Z INFO  cargo_ndk::cli] /Users/lishuaihua/Desktop/project/flutter_rust/rust/target/aarch64-linux-android/debug/librust_http.so -> ../android/app/src/main/jniLibs/arm64-v8a/librust_http.so
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:64736/pyXw87IUlj0=/ws
Syncing files to device Android SDK built for arm64...
D/EGL_emulation(28822): eglMakeCurrent: 0x703a133920: ver 3 0 (tinfo 0x703ecfb300)
D/EGL_emulation(28822): eglMakeCurrent: 0x703a1d9120: ver 3 0 (tinfo 0x70cfe82a60)

======== Exception caught by widgets library =======================================================
The following ArgumentError was thrown building Builder:
Invalid argument(s): Failed to lookup symbol 'store_dart_post_cobject': undefined symbol: store_dart_post_cobject

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/lishuaihua/Desktop/project/flutter_rust/lib/main.dart:17:12
When the exception was thrown, this was the stack: 
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:34:70)
#1      RustHttpWire._store_dart_post_cobjectPtr (package:flutter_rust/rust_http_generated.dart:128:76)
#2      RustHttpWire._store_dart_post_cobjectPtr (package:flutter_rust/rust_http_generated.dart)
#3      RustHttpWire._store_dart_post_cobject (package:flutter_rust/rust_http_generated.dart:130:41)
#4      RustHttpWire._store_dart_post_cobject (package:flutter_rust/rust_http_generated.dart)
#5      RustHttpWire.store_dart_post_cobject (package:flutter_rust/rust_http_generated.dart:122:12)
#6      StoreDartPostCObjectExt.storeDartPostCObject (package:flutter_rust_bridge/src/ffi/io.dart:18:5)
#7      FlutterRustBridgeBase._setUpRustToDartComm (package:flutter_rust_bridge/src/basic.dart:60:11)
#8      new FlutterRustBridgeBase (package:flutter_rust_bridge/src/basic.dart:28:5)
#9      new RustHttpPlatform (package:flutter_rust/rust_http_generated.dart:84:48)
#10     new RustHttpImpl (package:flutter_rust/rust_http_generated.dart:30:24)
#11     new _MyHomePageState (package:flutter_rust/main.dart:38:28)
#12     MyHomePage.createState (package:flutter_rust/main.dart:33:38)
#13     new StatefulElement (package:flutter/src/widgets/framework.dart:4891:25)
#14     StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:758:38)
...     Normal element mounting (275 frames)
#289    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#290    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#291    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (377 frames)
#668    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#669    Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#670    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1202:16)
#671    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1171:5)
#672    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1119:18)
#673    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
#674    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1118:13)
#675    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:953:7)
#676    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:933:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```

### Expected behavior

`final RustHttp rustHttp= RustHttpImpl(Platform.isAndroid ? DynamicLibrary.open('librust_http.so') : DynamicLibrary
          .executable());`

### Generated binding code

```shell
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.61.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'package:meta/meta.dart';
import 'package:meta/meta.dart';
import 'dart:ffi' as ffi;

abstract class RustHttp {
  Future<Ip> getItem({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetItemConstMeta;
}

class Ip {
  final String origin;

  Ip({
    required this.origin,
  });
}

class RustHttpImpl implements RustHttp {
  final RustHttpPlatform _platform;
  factory RustHttpImpl(ExternalLibrary dylib) =>
      RustHttpImpl.raw(RustHttpPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory RustHttpImpl.wasm(FutureOr<WasmModule> module) =>
      RustHttpImpl(module as ExternalLibrary);
  RustHttpImpl.raw(this._platform);
  Future<Ip> getItem({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_item(port_),
      parseSuccessData: _wire2api_ip,
      constMeta: kGetItemConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetItemConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_item",
        argNames: [],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  Ip _wire2api_ip(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return Ip(
      origin: _wire2api_String(arr[0]),
    );
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

// Section: finalizer

class RustHttpPlatform extends FlutterRustBridgeBase<RustHttpWire> {
  RustHttpPlatform(ffi.DynamicLibrary dylib) : super(RustHttpWire(dylib));

// Section: api2wire

// Section: finalizer

// Section: api_fill_to_wire

}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.

/// generated by flutter_rust_bridge
class RustHttpWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustHttpWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustHttpWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(
    int ptr,
  ) {
    return _get_dart_object(
      ptr,
    );
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(uintptr_t)>>(
          'get_dart_object');
  late final _get_dart_object =
      _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(
    int ptr,
  ) {
    return _drop_dart_object(
      ptr,
    );
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(uintptr_t)>>(
          'drop_dart_object');
  late final _drop_dart_object =
      _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(
    Object handle,
  ) {
    return _new_dart_opaque(
      handle,
    );
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<uintptr_t Function(ffi.Handle)>>(
          'new_dart_opaque');
  late final _new_dart_opaque =
      _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(
    ffi.Pointer<ffi.Void> obj,
  ) {
    return _init_frb_dart_api_dl(
      obj,
    );
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
          'init_frb_dart_api_dl');
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_get_item(
    int port_,
  ) {
    return _wire_get_item(
      port_,
    );
  }

  late final _wire_get_itemPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_get_item');
  late final _wire_get_item =
      _wire_get_itemPtr.asFunction<void Function(int)>();

  void free_WireSyncReturn(
    WireSyncReturn ptr,
  ) {
    return _free_WireSyncReturn(
      ptr,
    );
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
          'free_WireSyncReturn');
  late final _free_WireSyncReturn =
      _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();
}

class _Dart_Handle extends ffi.Opaque {}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
typedef DartPort = ffi.Int64;
typedef uintptr_t = ffi.UnsignedLong;
```

### OS

Mac OS 13.1

### Version of `flutter_rust_bridge_codegen`

1.61.0

### Flutter info

```shell
flutter doctor -v                                   
[✓] Flutter (Channel stable, 3.0.0, on macOS 13.1 22C65 darwin-arm (Rosetta),
    locale zh-Hans-CN)
    • Flutter version 3.0.0 at /Users/lishuaihua/fvm/versions/3.0.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (8 months ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/lishuaihua/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/lishuaihua/Library/Android/sdk
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • Android SDK built for arm64 (mobile) • emulator-5554 • android-arm64  •
      Android 10 (API 29) (emulator)
    • macOS (desktop)                      • macos         • darwin-arm64   •
      macOS 13.1 22C65 darwin-arm (Rosetta)
    • Chrome (web)                         • chrome        • web-javascript •
      Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are av
```

### Version of `clang++`

14.0.0

### Version of `ffigen`

6.1.0

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge/issues?q=store_dart_post_cobject Did the previous issue solutions solve your problem?

**Comment by ewgcat** [comment]
> https://github.com/fzyzcjy/flutter_rust_bridge/issues?q=store_dart_post_cobject Did the previous issue solutions solve your problem?

I hava a try,but It didn't solve my problem!

**Comment by fzyzcjy** [comment]
Maybe follow the tutorials in the doc, and see whether the tutorial works firstly :)

**Comment by ewgcat** [comment]
> Maybe follow the tutorials in the doc, and see whether the tutorial works firstly :)

cargo install cargo-ndk --version 2.6.0
ndkVersion "22.1.7171670"

**Comment by ewgcat** [comment]
cargo install cargo-ndk --version 2.6.0
ndkVersion "22.1.7171670" solve my problem!

**Comment by ewgcat** [comment]
Thanks!

**Comment by fzyzcjy** [comment]
You are welcome!
